### Setup

In [1]:
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from common.utils import DataPreprocessor, FeatureEngineer, set_seed
from common.exp_data_utils import ExperimentDataPreprocessor
from common.eval import Evaluator

MOVIELENS_DATA_DIR = "../datasets/hetrec2011-movielens-2k-v2/user_ratedmovies.dat"
RANDOM_SEED = 42

# Initialize data processors
set_seed(RANDOM_SEED)
data_preprocessor = DataPreprocessor()
feature_engineer = FeatureEngineer()
experiment_data_preprocessor = ExperimentDataPreprocessor()
evaluator = Evaluator()

/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Seed set to 42
Seed set to 42

random seed set to 42
numpy seed set to 42
torch seed set to 42
lightning seed set to 42
torch set to use deterministic algorithms

### Load and Process DataFrame

In [2]:
interaction_df = data_preprocessor.load_and_process_df(
    file_dir=MOVIELENS_DATA_DIR,
    year_range=(2006, 2008),
)
interaction_df.head()

Data count: 855598
Data count after filtering by year (2006, 2008): 480608
Num of distinct users: 2103
Num of distinct items: 9519
done!
------------------------------
Filtering by min user/item interactions (10/0):
Data count before: 480608
Data count after: 480448
done!
------------------------------
==== Final Data Info: ====
Data Year Range: (2006, 2008)
Rating Threshold: 4.0
Num of interactions: 480448
Num of distinct users: 2064
Num of distinct items: 9519

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second,timestamp,label
0,75,3,1.0,29,10,2006,23,17,16,2006-10-29 23:17:16,0
1,75,32,4.5,29,10,2006,23,23,44,2006-10-29 23:23:44,1
2,75,110,4.0,29,10,2006,23,30,8,2006-10-29 23:30:08,1
3,75,160,2.0,29,10,2006,23,16,52,2006-10-29 23:16:52,0
4,75,163,4.0,29,10,2006,23,29,30,2006-10-29 23:29:30,1

### Join Side Information

In [3]:
interaction_info_df = data_preprocessor.join_item_features(
    df=interaction_df, actor_k=5, threshold=5
)
interaction_info_df.head()

extracting item features...
merging features...
interaction data count before merging: 480448
interaction data count after merging: 478404
done!

,userID,movieID,rating,date_day,date_month,date_year,date_hour,date_minute,date_second,timestamp,label,actorID,country,directorID,directorName,genre
0,75,3,1.0,29,10,2006,23,17,16,2006-10-29 23:17:16,0,"[jack_lemmon, walter_matthau, annmargret, burg...",USA,donald_petrie,Donald Petrie,"[Comedy, Romance, [PAD], [PAD], [PAD], [PAD], ..."
1,75,32,4.5,29,10,2006,23,23,44,2006-10-29 23:23:44,1,"[[RARE], [RARE], [RARE], [RARE], [RARE]]",USA,[RARE],Siddharth Randeria,"[Sci-Fi, Thriller, [PAD], [PAD], [PAD], [PAD],..."
2,75,110,4.0,29,10,2006,23,30,8,2006-10-29 23:30:08,1,"[mel_gibson, sophie_marceau, patrick_mcgoohan,...",USA,[RARE],Mel Gibson,"[Action, Drama, War, [PAD], [PAD], [PAD], [PAD..."
3,75,160,2.0,29,10,2006,23,16,52,2006-10-29 23:16:52,0,"[[RARE], laura_linney, ernie_hudson_jr, tim_cu...",USA,frank_marshall,Frank Marshall,"[Action, Adventure, Mystery, Sci-Fi, [PAD], [P..."
4,75,163,4.0,29,10,2006,23,29,30,2006-10-29 23:29:30,1,"[antonio_banderas, salma_hayek, 1142520-joaqui...",USA,robert_rodriguez,Robert Rodriguez,"[Action, Romance, Thriller, [PAD], [PAD], [PAD..."

### Prepare Train/Valid/Test Set

In [4]:
# TODO: determine which method to use for splitting
# 1. Split by year
# 2. Stratified split by user, timestamp

train_df, valid_df, test_df = experiment_data_preprocessor.stratified_time_split(
    interaction_info_df,
    time_col="timestamp",
    train_ratio=0.75,
    val_ratio=0.1,
    test_ratio=0.15,
)

TRAIN_NUM_USERS = len(train_df["userID"].unique())
TRAIN_NUM_ITEMS = len(train_df["movieID"].unique())

Splitting data into train/valid/test by time period with ratio=(0.75 : 0.1 : 0.15):
train: 358027 (74.84%)
valid: 46916 (9.81%)
test: 73461 (15.36%)
------------------------------

Check target label distribution after splitting (%):
train label
0    0.555944
1    0.444056
Name: proportion, dtype: float64
valid label
0    0.610772
1    0.389228
Name: proportion, dtype: float64
test label
0    0.585277
1    0.414723
Name: proportion, dtype: float64

### Re-index User/Item ID & Encode Categorical Features

In [5]:
print("Train: fit_transform")
encoded_train_df = feature_engineer.fit_transform(train_df)
print("---"*10)
print("Valid: transform")
encoded_valid_df = feature_engineer.transform(valid_df)
print("---"*10)
print("Test: transform")
encoded_test_df = feature_engineer.transform(test_df)
print("---"*10)

Train: fit_transform
Re-index mapping dumped into ...
user: ../datasets/userid_mapping.csv
item: ../datasets/itemid_mapping.csv
Fitted: user/item mapping
Fitted: vocab2idx for actorID
Fitted: vocab2idx for country
Fitted: vocab2idx for directorID
Fitted: vocab2idx for genre
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
------------------------------
Valid: transform
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
------------------------------
Test: transform
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
------------------------------

In [6]:
# # NOTE: can check the encoding vocab idx content from the feature engineer
# oov_idx = feature_engineer.vocab2idx["movieID"]["[OOV]"]
# len(test_df[test_df["movieID"] == oov_idx])

### Prepare Additional Data for Train/Inference

#### Build bi-partite graph for training

In [7]:
# NOTE: At training, we use interaction graph from train_df for train and validation
train_graph = experiment_data_preprocessor.create_interaction_graph(encoded_train_df)

# NOTE: At inference, we can use graph of (train_df + valid_df)
# train_valid_graph = utils.create_interaction_graph(pd.concat([train_df, valid_df], axis=0))

Creating interaction graph...
Drop negative samples
  Num of all interactions: 358027
  Num of positive interactions: 158984

Building edges...
Building labels...
Interaction Graph: Data(edge_index=[2, 317967], edge_label=[158984])
Edge Index: tensor([[    0,     0,     0,  ..., 10758, 10762, 10763],
        [ 2089,  2202,  2318,  ...,  1760,  1645,  1760]])

#### Evaluate User Diversity Preference Scale

In [8]:
user_dps_df = evaluator.eval_user_diversity_preference_scale(encoded_train_df, feature_engineer.vocab2idx, normalized=True)
user_dps_df.head(1)

Calculating user diversity preference scale:   0%|          | 0/2064 [00:00<?, ?it/s]

Calculating user diversity preference scale: 100%|██████████| 2064/2064 [00:06<00:00, 339.09it/s]

,userID,actorID_wvec,actorID_dps,country_wvec,country_dps,directorID_wvec,directorID_dps,genre_wvec,genre_dps
0,0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, ...",0.577311,"[0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, ...",0.183214,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.494533,"[97.0, 41.5, 8.0, 5.0, 39.0, 45.5, 0.0, 44.5, ...",0.755545

#### Prepare Item Multihot Vec on Each Dimension

In [9]:
item_vec_df = evaluator.get_item_feature_multihot_vec(encoded_train_df, feature_engineer.vocab2idx)
item_vec_df.head(1)

,movieID,actorID_vec,country_vec,directorID_vec,genre_vec
0,1588,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

#### Prepare train/valid triplet data

In [10]:
train_triplet_df = experiment_data_preprocessor.prepare_triplet_df(encoded_train_df, k_negative_samples=5)
train_triplet_with_dps_df = train_triplet_df.merge(user_dps_df, on="userID", how="left")
train_triplet_with_dps_df = train_triplet_with_dps_df.merge(item_vec_df, left_on="pos_item_id", right_on="movieID", how="left")
# train_triplet_with_dps_df.head(1)

valid_triplet_df = experiment_data_preprocessor.prepare_triplet_df(encoded_valid_df, k_negative_samples=5)
valid_triplet_with_dps_df = valid_triplet_df.merge(user_dps_df, on="userID", how="left")
valid_triplet_with_dps_df = valid_triplet_with_dps_df.merge(item_vec_df, left_on="pos_item_id", right_on="movieID", how="inner")
valid_triplet_with_dps_df.head(1)

Original data count (positive samples): 158984
Num of triplets: 158984(pos samples) * 5(negative sampled items) = 794920
Original data count (positive samples): 18261
Num of triplets: 18261(pos samples) * 5(negative sampled items) = 91305

,userID,pos_item_id,neg_item_id,actorID_idx,country_idx,directorID_idx,genre_idx,neg_actorID_idx,neg_country_idx,neg_directorID_idx,...,country_dps,directorID_wvec,directorID_dps,genre_wvec,genre_dps,movieID,actorID_vec,country_vec,directorID_vec,genre_vec
0,0,962,4662,"[328, 704, 1, 1, 1]",37,464,"[2, 3, 6, 10, 12, 0, 0, 0]","[988, 648, 2087, 1, 924]",37,75,...,0.183214,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.494533,"[97.0, 41.5, 8.0, 5.0, 39.0, 45.5, 0.0, 44.5, ...",0.755545,962,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, ..."

#### Prepare prediction pool for inference/testing

In [11]:
# NOTE: Prepare prediction pool to evaluate the model
prediction_pool_df = experiment_data_preprocessor.prepare_prediction_df(encoded_test_df, K=500)
prediction_pool_df.tail()

Prediction DataFrame:
User Pool: 2064
Item Pool: 6959, negative sampled to 500 items for each user
Num of interactions: 2064(users) * 500(items) = 1032000

,userID,movieID,label,actorID_idx,country_idx,directorID_idx,genre_idx
1031995,2063,447,0,"[2136, 281, 1446, 61, 1]",36,1,"[9, 0, 0, 0, 0, 0, 0, 0]"
1031996,2063,3601,0,"[1578, 466, 911, 941, 887]",37,432,"[2, 19, 0, 0, 0, 0, 0, 0]"
1031997,2063,7982,0,"[1, 1, 1, 1, 1]",37,1,"[12, 0, 0, 0, 0, 0, 0, 0]"
1031998,2063,5969,0,"[1, 1383, 554, 1, 828]",37,534,"[9, 16, 0, 0, 0, 0, 0, 0]"
1031999,2063,5025,0,"[446, 1010, 637, 809, 547]",36,70,"[7, 12, 15, 18, 0, 0, 0, 0]"

### Prepare DataLoader

In [12]:
# NOTE: ensure reproducibility of DataLoader
import torch
from common.utils import seed_worker
g = torch.Generator()
g.manual_seed(RANDOM_SEED)

# TODO: determine which Dataset to use
from torch.utils.data import DataLoader
from common.datasets import TripletDataset, UserItemPairDataset, UserPosItemSampler, get_user_triplet_mapping

BATCH_SIZE = 1024

train_dataset = TripletDataset(train_triplet_with_dps_df)
valid_dataset = TripletDataset(valid_triplet_with_dps_df)
test_dataset = UserItemPairDataset(prediction_pool_df)
print("train data count:", len(train_dataset))
print("valid data count:", len(valid_dataset))
print("test data count:", len(test_dataset))

# TODO: Custom sampler
# MIN_POS_ITEMS = 2
# user_to_pos_items, user_pos_to_indices = get_user_triplet_mapping(train_triplet_with_dps_df, MIN_POS_ITEMS)
# train_sampler = UserPosItemSampler(user_to_pos_items, user_pos_to_indices, batch_size=BATCH_SIZE, min_pos_items=MIN_POS_ITEMS, max_pos_items=20, buffer=0)
# train_loader = DataLoader(train_dataset, batch_sampler=train_sampler, num_workers=4, worker_init_fn=seed_worker, generator=g)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, worker_init_fn=seed_worker, generator=g, num_workers=4)
valid_loader = DataLoader(valid_dataset, batch_size=BATCH_SIZE)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)

train data count: 794920
valid data count: 90805
test data count: 1032000

### Configure Model (LightningModule)

In [13]:
from lightning_models.mtdp_ngcf_v2 import MTDPRecSRM

EMB_DIM = 64
LR = 1e-3
EPOCHS = 50
NUM_LAYERS = 3
REG_WEIGHT = 1e-5

DPS_WEIGHTS = {
    "actor_dps": 0.25,
    "country_dps": 0.25,
    "director_dps": 0.25,
    "genre_dps": 0.25,
}

DPR_WEIGHTS = {
    "actor_dpr": 0.25,
    "country_dpr": 0.25,
    "director_dpr": 0.25,
    "genre_dpr": 0.25,
}

DPM_WEIGHTS = {
    "actor_pd": 0.25,
    "country_pd": 0.25,
    "director_pd": 0.25,
    "genre_pd": 0.25,
}

MT_WEIGHTS = {
    "bpr_loss": 1.0,
    "dps_loss": 0,
    "dpr_loss": 0,
    "dpm_loss": 0,
}

RESCALE_METHOD = None  # None, "log", "ema"

model = MTDPRecSRM(
    graph_data=train_graph,  # shape [2, num_edges]
    num_users=TRAIN_NUM_USERS,
    num_items=TRAIN_NUM_ITEMS,
    embedding_dim=EMB_DIM,
    num_layers=NUM_LAYERS,
    node_dropout=0.0,
    mess_dropout=0.1,
    lr=LR,
    reg_weight=REG_WEIGHT,
    dps_weights=DPS_WEIGHTS,
    dpr_weights=DPR_WEIGHTS,
    dpm_weights=DPM_WEIGHTS,
    mt_weights=MT_WEIGHTS,
    rescale_method=RESCALE_METHOD,
)

Seed set to 42

### Configure Trainer and Experiment

In [14]:
from common._mlflow import get_mlflow_logger, get_callbacks

EXPERIMENT_NAME = "rerank"
VERSION = "ngcf_v2"
RUN_NAME = "run00"
PATIENCE = 5
mlflow_logger = get_mlflow_logger(experiment_name=EXPERIMENT_NAME, run_name=RUN_NAME, tags={"version": VERSION})
trainer_callbacks = get_callbacks(
    exp_name=EXPERIMENT_NAME,
    version_name=VERSION,
    run_name=RUN_NAME,
    patience=PATIENCE,
    monitor_metric="val_loss",
    monitor_mode="min",
    hyper_param_str=f"",
)

In [15]:
from pytorch_lightning import Trainer

trainer = Trainer(
    max_epochs=EPOCHS,
    logger=mlflow_logger,
    log_every_n_steps=50,
    callbacks=trainer_callbacks,
    accelerator='auto',  # or 'auto', 'gpu'
    # devices=[0], # if gpu is available
)

Trainer will use only 1 of 2 GPUs because it is running inside an interactive / notebook environment. You may try to set `Trainer(devices=2)` but please note that multi-GPU inside interactive / notebook environments is considered experimental and unstable. Your mileage may vary.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

### Train Model

In [16]:
# Start training
trainer.fit(model, train_dataloaders=train_loader, val_dataloaders=valid_loader)

/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/adam/R11_Bai/DPRecSys/experiments/test_checkpoints/rerank exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

   | Name                | Type              | Params | Mode
-------------------------------------------------------------------
0  | ngcf_model          | NGCF              | 714 K  | train
1  | bpr_loss            | BPRLoss           | 0      | train
2  | reg_loss            | EmbLoss           | 0      | train
3  | dps_module          | DPSPredictor      | 1.0 K  | train
4  | dps_loss_fn         | DPSLoss           | 0      | train
5  | dpr_module          | DPRegularizer     | 263 K  | train
6  | dpr_loss_fn         | DPRLoss           | 0      | train
7  | dpm_module          | DPMatcher         | 0      | train
8  | dpm_loss_fn         | KLDivergenceLoss  | 0      | train
9  | loss_scaling_module | LogScaleLoss      | 0      | train
10 | ema_normalizer      | EMALossNormalizer | 0      | train
-------------------------------------------------------------------
978 K     Trainable params
0         Non-trainable params
978 K     Total params
3.914     Total estimated model params size (MB)
43        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Metric val_loss improved. New best score: 0.595
Epoch 0, global step 777: 'val_loss' reached 0.59470 (best 0.59470), saving model to '/home/adam/R11_Bai/DPRecSys/experiments/test_checkpoints/rerank/[ngcf_v2]-run00--best-checkpoint-epoch=00-val_loss=0.59.ckpt' as top 1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 1, global step 1554: 'val_loss' was not in top 1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 2, global step 2331: 'val_loss' was not in top 1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 3, global step 3108: 'val_loss' was not in top 1

Validation: |          | 0/? [00:00<?, ?it/s]

Epoch 4, global step 3885: 'val_loss' was not in top 1

Validation: |          | 0/? [00:00<?, ?it/s]

Monitored metric val_loss did not improve in the last 5 records. Best score: 0.595. Signaling Trainer to stop.
Epoch 5, global step 4662: 'val_loss' was not in top 1

🏃 View run run00 at: http://140.112.106.216:3683/#/experiments/19/runs/f908b3af600f4e90a31220800aba9654
🧪 View experiment at: http://140.112.106.216:3683/#/experiments/19

### Inference

In [17]:
# NOTE: the inference model MUST be the same as the training model
# best_model_experiment_name = "rerank"
# best_model_checkpoint_path = "[ngcf_v2]-test_run--best-checkpoint-epoch=00-val_loss=2.93.ckpt"
# best_model_path = f"test_checkpoints/{best_model_experiment_name}/{best_model_checkpoint_path}"
best_model_path = trainer.checkpoint_callback.best_model_path

model = MTDPRecSRM.load_from_checkpoint(checkpoint_path=best_model_path)
# start inference
trainer.test(model=model, dataloaders=test_loader)

Seed set to 42
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        test_ndcg10        │    0.3693173825740814     │
│        test_ndcg20        │    0.39844560623168945    │
│        test_ndcg5         │    0.32048583030700684    │
│     test_precision10      │    0.1355135589838028     │
│     test_precision20      │    0.11654554307460785    │
│      test_precision5      │    0.1472868174314499     │
│       test_recall10       │    0.11921688169240952    │
│       test_recall20       │    0.19435930252075195    │
│       test_recall5        │    0.06696981936693192    │
└───────────────────────────┴───────────────────────────┘

🏃 View run run00 at: http://140.112.106.216:3683/#/experiments/19/runs/f908b3af600f4e90a31220800aba9654
🧪 View experiment at: http://140.112.106.216:3683/#/experiments/19

[{'test_ndcg5': 0.32048583030700684,
  'test_ndcg10': 0.3693173825740814,
  'test_ndcg20': 0.39844560623168945,
  'test_precision5': 0.1472868174314499,
  'test_precision10': 0.1355135589838028,
  'test_precision20': 0.11654554307460785,
  'test_recall5': 0.06696981936693192,
  'test_recall10': 0.11921688169240952,
  'test_recall20': 0.19435930252075195}]

In [18]:
model.test_results["eval_score_df"].describe()

,user,ndcg@5,recall@5,precision@5,ndcg@10,recall@10,precision@10,ndcg@20,recall@20,precision@20
count,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000
mean,1031.500000,0.320486,0.066970,0.147287,0.369317,0.119217,0.135514,0.398446,0.194359,0.116546
std,595.969798,0.365965,0.116284,0.189426,0.323787,0.155684,0.143812,0.280284,0.193950,0.110165
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,515.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.235409,0.041667,0.050000
50%,1031.500000,0.000000,0.000000,0.000000,0.386853,0.073734,0.100000,0.401733,0.153010,0.100000
75%,1547.250000,0.630930,0.090909,0.200000,0.618171,0.176471,0.200000,0.594447,0.285714,0.200000
max,2063.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.900000,1.000000,1.000000,0.800000

In [19]:
prefix = "(mt)ngcf_v2_k5"
embedding_path = "embeddings/"

torch.save(model.user_emb.cpu(), f"{embedding_path}{prefix}_user_emb.pt")
torch.save(model.item_emb.cpu(), f"{embedding_path}{prefix}_item_emb.pt")

In [20]:
# Evaluate user diversity preference matching score (DPMS) at k
eval_df = evaluator.prepare_evaluation_data(model.test_results, feature_engineer.idx2vocab)

# Get user DPMS
user_dpms_df = evaluator.evaluate_dpms_at_k(
    eval_df=eval_df,
    feature_engineer=feature_engineer,
    ground_truth_dps_df=user_dps_df,
    k=20,
    actor_k=5,
    rare_threshold=5,
)

user_dpms_df.describe()

exploded 2064
extracting item features...
merging features...
interaction data count before merging: 41280
interaction data count after merging: 41280
done!
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
encoded 2064

Calculating user diversity preference scale: 100%|██████████| 2064/2064 [00:03<00:00, 685.68it/s]

combined_df 2064
Calculating DPMS for each feature...

,userID,actorID_dpms,country_dpms,directorID_dpms,genre_dpms,avg_dpms
count,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000
mean,1031.500000,0.163257,0.975495,0.160620,0.884718,0.546023
std,595.969798,0.074057,0.033267,0.101668,0.074649,0.052788
min,0.000000,0.000000,0.438207,0.000000,0.386221,0.298375
25%,515.750000,0.107092,0.972216,0.082536,0.856962,0.511858
50%,1031.500000,0.163787,0.984858,0.155008,0.905553,0.550741
75%,1547.250000,0.218617,0.991439,0.230501,0.934801,0.583744
max,2063.000000,0.375640,0.999578,0.569165,0.984803,0.701302

In [21]:
import joblib
dir = "tmp"
if not os.path.exists(dir):
    os.makedirs(dir)
joblib.dump(eval_df, os.path.join(dir, "eval_df.pkl"))
joblib.dump(user_dps_df, os.path.join(dir, "user_dps_df.pkl"))
joblib.dump(feature_engineer, os.path.join(dir, "feature_engineer.pkl"))

['tmp/feature_engineer.pkl']

In [1]:
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

import joblib
dir = "tmp"
eval_df = joblib.load(os.path.join(dir, "eval_df.pkl"))
user_dps_df = joblib.load(os.path.join(dir, "user_dps_df.pkl"))
feature_engineer = joblib.load(os.path.join(dir, "feature_engineer.pkl"))

/home/adam/R11_Bai/DPRecSys/.venv/lib/python3.11/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

In [2]:
from post_processing.dpa_rs import DPA_RS

reranker = DPA_RS(
    eval_df=eval_df,
    feature_engineer=feature_engineer,
    m=100,
    ground_truth_dps_df=user_dps_df
)

Seed set to 42

In [ ]:
result_df = reranker.rerank(
    top_k=20,
    max_iter=100,
    random_state=42,
)
result_df.head()

Preparing input DataFrame for DPA-RS...
exploded 2064
extracting item features...
merging features...
interaction data count before merging: 206400
interaction data count after merging: 206400
done!
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
encoded 2064
Combined DataFrame shape: (206400, 15)
Reranking items for each user...

Reranking users:   0%|          | 0/2064 [00:00<?, ?it/s](CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.338e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 7.730e+00
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.338e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 7.984e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.130e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 2.166e-01
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.130e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.101e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.056e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.146e-02
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.590e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.044e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.369e-03
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.044e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.085e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.044e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.939e-04
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.044e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.032e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.368e-05
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.692e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.039e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 9.857e-07
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.039e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.980e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.066e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.

===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.205e+01  -1.585e+02  +9e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +2.232e+00  -7.943e+01  +8e+02  3e-01  1e-02  1e+00  4e+00  0.2509  4e-01   1  2  2 |  0  0
 2  -3.369e+00  -1.626e+01  +2e+02  5e-02  1e-03  5e-01  1e+00  0.7681  1e-01   1  1  1 |  0  0
 3  -7.570e+00  -1.095e+01  +7e+01  1e-02  3e-04  1e-01  4e-01  0.8040  1e-01   2  2  2 |  0  0
 4  -7.397e+00  -9.419e+00  +5e+01  6e-03  2e-04  4e-02  2e-01  0.6514  5e-01   1  2  2 |  0  0
 5  -7.689e+00  -8.342e+00  +2e+01  2e-03  5e-05  7e-03  8e-02  0.9761  3e-01   1  2  2 |  0  0
 6  -7.718e+00  -7.835e+00  +3e+00  3e-04  9e-06  1e-03  1e-02  0.8314  2e-02   1  1  1 |  0  0
 7  -7.718e+00  -7.800e+00  +2e+00  2e-04  7e-06  8e-04  1e-02  0.5495  5e-01   1  1  1 |  0  0
 8  -7.728e+00  -7.738e+00  +2e-01  3e-05  8e-07  8e-05  1e-03  0.9157  4e-02   1  1  1 |  0  0
 9  -7.729e+00  -7.732e+00  +5e-02  6e-06  2e-07  2e-05  3e-04  0.8714  1e-01   1  1  1 |  0  0
10  -7.730e+00  -7.730e+00  +1e-02  1e-06  4e-08  4e-06  5e-05  0.8525  6e-02   1  1  1 |  0  0
11  -7.730e+00  -7.730e+00  +3e-03  3e-07  8e-09  8e-07  1e-05  0.9570  2e-01   2  1  1 |  0  0
12  -7.730e+00  -7.730e+00  +2e-04  2e-08  6e-10  6e-08  9e-07  0.9312  2e-03   2  1  1 |  0  0
13  -7.730e+00  -7.730e+00  +6e-05  7e-09  2e-10  2e-08  3e-07  0.6849  1e-02   2  1  1 |  0  0
14  -7.730e+00  -7.730e+00  +1e-05  2e-09  5e-11  4e-09  7e-08  0.8872  1e-01   1  1  1 |  0  0
15  -7.730e+00  -7.730e+00  +1e-06  2e-10  5e-12  4e-10  7e-09  0.9129  2e-02   2  1  1 |  0  0
16  -7.730e+00  -7.730e+00  +6e-08  7e-12  2e-13  2e-11  3e-10  0.9663  1e-02   2  1  1 |  0  0

OPTIMAL (within feastol=7.3e-12, reltol=8.4e-09, abstol=6.5e-08).
Runtime: 0.007946 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.459e+00  -1.064e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.661e+00  -3.651e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3876  4e-01   1  1  1 |  0  0
 2  +4.258e-01  -2.962e+00  +9e+01  2e-02  2e-03  1e+00  6e-01  0.8953  1e-01   1  1  1 |  0  0
 3  +9.094e-02  -1.805e+00  +5e+01  1e-02  1e-03  6e-01  3e-01  0.4913  2e-01   1  1  1 |  0  0
 4  -9.922e-02  -9.650e-01  +3e+01  4e-03  4e-04  2e-01  2e-01  0.5932  1e-01   1  1  2 |  0  0
 5  -1.604e-01  -5.020e-01  +1e+01  1e-03  2e-04  7e-02  6e-02  0.6703  9e-02   1  1  2 |  0  0
 6  -1.996e-01  -4.017e-01  +6e+00  7e-04  7e-05  3e-03  3e-02  0.9890  5e-01   1  1  1 |  0  0
 7  -2.047e-01  -2.743e-01  +2e+00  2e-04  2e-05  5e-04  1e-02  0.9092  3e-01   1  1  1 |  0  0
 8  -2.113e-01  -2.404e-01  +9e-01  1e-04  1e-05  2e-04  4e-03  0.7891  3e-01   1  1  1 |  0  0
 9  -2.144e-01  -2.260e-01  +4e-01  4e-05  4e-06  7e-05  2e-03  0.6944  1e-01   1  1  1 |  0  0
10  -2.148e-01  -2.224e-01  +2e-01  2e-05  3e-06  5e-05  1e-03  0.6753  5e-01   1  1  1 |  0  0
11  -2.161e-01  -2.182e-01  +6e-02  7e-06  7e-07  1e-05  3e-04  0.8236  1e-01   1  1  1 |  0  0
12  -2.164e-01  -2.171e-01  +2e-02  2e-06  3e-07  4e-06  1e-04  0.7901  2e-01   2  1  1 |  0  0
13  -2.165e-01  -2.167e-01  +6e-03  6e-07  6e-08  1e-06  3e-05  0.8330  9e-02   1  1  1 |  0  0
14  -2.165e-01  -2.166e-01  +1e-03  1e-07  1e-08  2e-07  6e-06  0.8737  1e-01   1  1  1 |  0  0
15  -2.166e-01  -2.166e-01  +2e-04  2e-08  2e-09  4e-08  1e-06  0.8514  1e-02   2  1  1 |  0  0
16  -2.166e-01  -2.166e-01  +2e-05  2e-09  2e-10  4e-09  1e-07  0.9660  8e-02   2  1  1 |  0  0
17  -2.166e-01  -2.166e-01  +2e-06  2e-10  2e-11  3e-10  8e-09  0.9247  2e-03   2  1  1 |  0  0
18  -2.166e-01  -2.166e-01  +8e-08  8e-12  9e-13  1e-11  4e-10  0.9862  4e-02   2  1  1 |  0  0
19  -2.166e-01  -2.166e-01  +2e-09  2e-13  1e-13  4e-13  1e-11  0.9706  1e-04   2  1  1 |  0  0

OPTIMAL (within feastol=2.5e-13, reltol=1.1e-08, abstol=2.3e-09).
Runtime: 0.009063 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.568e+00  -1.067e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.788e+00  -3.771e+01  +5e+02  2e-01  1e-02  2e+00  2e+00  0.3450  4e-01   1  1  1 |  0  0
 2  +9.394e-01  -2.322e+00  +8e+01  2e-02  1e-03  7e-01  5e-01  0.9230  1e-01   1  1  1 |  0  0
 3  +3.144e-01  -1.326e+00  +5e+01  8e-03  5e-04  3e-01  3e-01  0.5544  2e-01   1  1  2 |  0  0
 4  +3.539e-02  -5.587e-01  +2e+01  3e-03  2e-04  8e-02  9e-02  0.7174  1e-01   1  2  2 |  0  0
 5  -1.108e-02  -4.494e-01  +1e+01  2e-03  1e-04  3e-02  7e-02  0.6285  5e-01   1  2  1 |  0  0
 6  -2.334e-02  -2.243e-01  +6e+00  7e-04  4e-05  4e-03  3e-02  0.9178  4e-01   1  1  2 |  0  0
 7  -2.924e-02  -1.114e-01  +2e+00  3e-04  2e-05  1e-03  1e-02  0.8123  3e-01   1  1  1 |  0  0
 8  -2.911e-02  -5.328e-02  +7e-01  9e-05  5e-06  2e-04  4e-03  0.8625  2e-01   1  1  1 |  0  0
 9  -3.083e-02  -3.759e-02  +2e-01  2e-05  1e-06  5e-05  1e-03  0.8482  2e-01   1  1  1 |  0  0
10  -3.129e-02  -3.301e-02  +5e-02  6e-06  3e-07  1e-05  2e-04  0.8005  7e-02   1  1  1 |  0  0
11  -3.136e-02  -3.217e-02  +2e-02  3e-06  2e-07  5e-06  1e-04  0.7839  3e-01   1  1  1 |  0  0
12  -3.144e-02  -3.161e-02  +5e-03  6e-07  3e-08  1e-06  2e-05  0.8854  1e-01   1  1  1 |  0  0
13  -3.146e-02  -3.149e-02  +1e-03  1e-07  7e-09  2e-07  5e-06  0.8486  5e-02   1  1  1 |  0  0
14  -3.146e-02  -3.147e-02  +3e-04  3e-08  2e-09  6e-08  1e-06  0.9890  3e-01   2  1  1 |  0  0
15  -3.146e-02  -3.146e-02  +5e-05  5e-09  3e-10  9e-09  2e-07  0.8892  5e-02   2  1  1 |  0  0
16  -3.146e-02  -3.146e-02  +7e-06  8e-10  5e-11  1e-09  3e-08  0.9118  7e-02   2  1  1 |  0  0
17  -3.146e-02  -3.146e-02  +2e-06  2e-10  1e-11  4e-10  1e-08  0.8410  1e-01   2  1  1 |  0  0
18  -3.146e-02  -3.146e-02  +2e-07  3e-11  2e-12  4e-11  1e-09  0.9565  8e-02   2  1  1 |  0  0
19  -3.146e-02  -3.146e-02  +5e-08  6e-12  4e-13  1e-11  3e-10  0.8744  1e-01   1  1  1 |  0  0
20  -3.146e-02  -3.146e-02  +7e-09  8e-13  1e-13  1e-12  3e-11  0.9323  6e-02   2  1  1 |  0  0

OPTIMAL (within feastol=7.6e-13, reltol=2.1e-07, abstol=6.5e-09).
Runtime: 0.009554 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.655e+00  -1.082e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.587e+00  -3.340e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3802  3e-01   1  1  1 |  0  0
 2  +8.380e-01  -2.729e+00  +9e+01  2e-02  9e-04  4e-01  5e-01  0.8869  1e-01   1  1  1 |  0  0
 3  +3.033e-01  -1.764e+00  +5e+01  9e-03  5e-04  2e-01  3e-01  0.4910  2e-01   1  2  2 |  0  0
 4  +6.489e-02  -6.167e-01  +2e+01  3e-03  1e-04  5e-02  1e-01  0.6914  6e-02   1  2  2 |  0  0
 5  +9.506e-03  -5.149e-01  +1e+01  2e-03  9e-05  3e-02  7e-02  0.5527  6e-01   1  2  1 |  0  0
 6  -4.615e-03  -2.788e-01  +8e+00  1e-03  4e-05  4e-03  4e-02  0.8996  5e-01   1  2  2 |  0  0
 7  -4.250e-03  -9.551e-02  +3e+00  3e-04  1e-05  9e-04  1e-02  0.8594  2e-01   1  2  1 |  0  0
 8  -2.234e-03  -2.887e-02  +8e-01  1e-04  4e-06  2e-04  4e-03  0.8575  2e-01   1  2  2 |  0  0
 9  -2.852e-03  -1.365e-02  +3e-01  4e-05  2e-06  7e-05  2e-03  0.9618  4e-01   1  1  1 |  0  0
10  -3.238e-03  -5.384e-03  +6e-02  8e-06  3e-07  1e-05  3e-04  0.8542  6e-02   1  1  1 |  0  0
11  -3.328e-03  -4.008e-03  +2e-02  2e-06  1e-07  4e-06  1e-04  0.7526  9e-02   1  1  1 |  0  0
12  -3.342e-03  -3.674e-03  +1e-02  1e-06  5e-08  2e-06  5e-05  0.7887  4e-01   1  1  1 |  0  0
13  -3.367e-03  -3.400e-03  +1e-03  1e-07  5e-09  2e-07  5e-06  0.9362  4e-02   1  1  1 |  0  0
14  -3.369e-03  -3.372e-03  +1e-04  1e-08  5e-10  2e-08  5e-07  0.9438  6e-02   2  1  1 |  0  0
15  -3.369e-03  -3.369e-03  +1e-05  1e-09  6e-11  2e-09  6e-08  0.9018  1e-02   2  1  1 |  0  0
16  -3.369e-03  -3.369e-03  +4e-06  5e-10  2e-11  8e-10  2e-08  0.7972  2e-01   1  1  1 |  0  0
17  -3.369e-03  -3.369e-03  +9e-07  1e-10  5e-12  2e-10  4e-09  0.8133  4e-02   2  1  1 |  0  0
18  -3.369e-03  -3.369e-03  +5e-07  6e-11  2e-12  1e-10  2e-09  0.6840  3e-01   2  1  1 |  0  0
19  -3.369e-03  -3.369e-03  +1e-07  1e-11  5e-13  2e-11  5e-10  0.8208  4e-02   1  1  1 |  0  0
20  -3.369e-03  -3.369e-03  +4e-08  5e-12  3e-13  9e-12  2e-10  0.7147  2e-01   2  1  1 |  0  0
21  -3.369e-03  -3.369e-03  +1e-08  1e-12  8e-14  2e-12  5e-11  0.7708  3e-02   2  1  1 |  0  0
22  -3.369e-03  -3.369e-03  +5e-09  6e-13  4e-14  1e-12  3e-11  0.6907  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=6.5e-13, reltol=1.6e-06, abstol=5.3e-09).
Runtime: 0.010812 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.692e+00  -1.086e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.677e+00  -3.253e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3894  3e-01   1  1  1 |  0  0
 2  +7.704e-01  -2.801e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8818  9e-02   1  1  1 |  0  0
 3  +2.397e-01  -1.751e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5216  2e-01   2  2  2 |  0  0
 4  +5.757e-02  -6.255e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6796  7e-02   1  2  2 |  0  0
 5  +3.219e-03  -5.181e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5644  6e-01   1  2  1 |  0  0
 6  -5.715e-03  -2.750e-01  +8e+00  1e-03  4e-05  4e-03  4e-02  0.9049  5e-01   1  2  2 |  0  0
 7  -2.123e-03  -8.792e-02  +2e+00  3e-04  1e-05  8e-04  1e-02  0.8782  2e-01   1  2  1 |  0  0
 8  +3.461e-04  -2.592e-02  +8e-01  1e-04  4e-06  2e-04  4e-03  0.8422  2e-01   1  2  2 |  0  0
 9  +3.814e-05  -1.290e-02  +4e-01  5e-05  2e-06  8e-05  2e-03  0.8766  4e-01   1  1  1 |  0  0
10  -5.910e-05  -2.582e-03  +7e-02  9e-06  3e-07  2e-05  4e-04  0.8569  6e-02   1  1  1 |  0  0
11  -1.709e-04  -6.152e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8656  5e-02   1  1  1 |  0  0
12  -1.838e-04  -3.382e-04  +4e-03  5e-07  2e-08  1e-06  2e-05  0.8133  2e-01   1  1  1 |  0  0
13  -1.925e-04  -2.158e-04  +7e-04  8e-08  3e-09  1e-07  3e-06  0.9100  7e-02   2  1  1 |  0  0
14  -1.935e-04  -1.988e-04  +2e-04  2e-08  7e-10  3e-08  7e-07  0.9138  2e-01   2  1  1 |  0  0
15  -1.939e-04  -1.943e-04  +1e-05  1e-09  5e-11  2e-09  5e-08  0.9509  2e-02   1  1  1 |  0  0
16  -1.939e-04  -1.940e-04  +3e-06  3e-10  1e-11  6e-10  1e-08  0.8524  1e-01   2  1  1 |  0  0
17  -1.939e-04  -1.939e-04  +6e-07  8e-11  3e-12  1e-10  3e-09  0.8001  5e-02   2  1  1 |  0  0
18  -1.939e-04  -1.939e-04  +3e-07  4e-11  2e-12  7e-11  2e-09  0.6985  3e-01   2  1  1 |  0  0
19  -1.939e-04  -1.939e-04  +5e-08  6e-12  3e-13  1e-11  3e-10  0.8907  5e-02   1  1  1 |  0  0
20  -1.939e-04  -1.939e-04  +2e-08  2e-12  9e-14  3e-12  8e-11  0.8263  2e-01   2  1  1 |  0  0
21  -1.939e-04  -1.939e-04  +3e-09  4e-13  3e-14  6e-13  1e-11  0.8264  2e-02   1  1  1 |  0  0

OPTIMAL (within feastol=3.8e-13, reltol=1.6e-05, abstol=3.0e-09).
Runtime: 0.010285 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.687e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.706e+00  -3.212e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3938  3e-01   1  1  1 |  0  0
 2  +7.506e-01  -2.818e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8798  9e-02   1  1  1 |  0  0
 3  +2.226e-01  -1.741e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5316  2e-01   2  2  2 |  0  0
 4  +5.476e-02  -6.196e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6788  7e-02   1  2  2 |  0  0
 5  +2.065e-03  -5.132e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5628  6e-01   1  2  1 |  0  0
 6  -5.938e-03  -2.740e-01  +8e+00  1e-03  4e-05  4e-03  4e-02  0.9019  5e-01   1  2  2 |  0  0
 7  -1.946e-03  -8.598e-02  +2e+00  3e-04  1e-05  8e-04  1e-02  0.8832  2e-01   1  2  1 |  0  0
 8  +4.700e-04  -2.563e-02  +7e-01  9e-05  3e-06  2e-04  4e-03  0.8394  2e-01   1  2  2 |  0  0
 9  +1.469e-04  -1.266e-02  +4e-01  5e-05  2e-06  8e-05  2e-03  0.8810  4e-01   1  1  1 |  0  0
10  +1.250e-04  -2.393e-03  +7e-02  9e-06  3e-07  2e-05  4e-04  0.8537  6e-02   1  1  1 |  0  0
11  +6.598e-06  -3.976e-04  +1e-02  1e-06  5e-08  3e-06  6e-05  0.8755  4e-02   1  1  1 |  0  0
12  -5.853e-06  -1.271e-04  +3e-03  4e-07  2e-08  8e-07  2e-05  0.8377  2e-01   2  1  1 |  0  0
13  -1.230e-05  -3.529e-05  +7e-04  8e-08  3e-09  1e-07  3e-06  0.8768  8e-02   1  1  1 |  0  0
14  -1.322e-05  -1.949e-05  +2e-04  2e-08  8e-10  4e-08  9e-07  0.9047  2e-01   2  1  1 |  0  0
15  -1.365e-05  -1.408e-05  +1e-05  2e-09  6e-11  3e-09  6e-08  0.9522  2e-02   1  1  1 |  0  0
16  -1.368e-05  -1.375e-05  +2e-06  2e-10  9e-12  4e-10  1e-08  0.8494  2e-02   2  1  1 |  0  0
17  -1.368e-05  -1.371e-05  +7e-07  8e-11  3e-12  1e-10  3e-09  0.7685  1e-01   2  1  1 |  0  0
18  -1.368e-05  -1.369e-05  +1e-07  2e-11  7e-13  3e-11  7e-10  0.8876  1e-01   1  1  1 |  0  0
19  -1.368e-05  -1.369e-05  +4e-08  5e-12  2e-13  8e-12  2e-10  0.8737  1e-01   2  1  1 |  0  0
20  -1.368e-05  -1.368e-05  +4e-09  5e-13  5e-14  8e-13  2e-11  0.9395  5e-02   1  1  1 |  0  0

OPTIMAL (within feastol=5.0e-13, reltol=2.9e-04, abstol=4.0e-09).
Runtime: 0.009654 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.688e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.711e+00  -3.205e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3946  3e-01   1  1  1 |  0  0
 2  +7.454e-01  -2.822e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8795  9e-02   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 7.371e-08
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.066e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.909e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.050e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 5.616e-09
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.050e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.710e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.030e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 4.335e-10
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.030e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.799e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.077e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.385e-11
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.077e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.006e-02 seconds
Reranking users:   0%|          | 1/2064 [00:00<10:39,  3.22it/s](CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.007e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 5.469e+00
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.007e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 9.928e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.049e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 2.319e-01
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.049e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 8.348e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.056e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.124e-02
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.145e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.050e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.804e-02
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.050e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.170e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.687e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.713e+00  -3.202e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3950  3e-01   1  1  1 |  0  0
 2  +7.440e-01  -2.823e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8793  9e-02   1  1  1 |  0  0
 3  +2.164e-01  -1.736e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5355  2e-01   2  2  2 |  0  0
 4  +5.357e-02  -6.184e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6783  7e-02   1  2  2 |  0  0
 5  +1.269e-03  -5.121e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5640  6e-01   1  2  1 |  0  0
 6  -6.152e-03  -2.728e-01  +7e+00  1e-03  4e-05  4e-03  4e-02  0.9019  5e-01   1  2  2 |  0  0
 7  -1.967e-03  -8.527e-02  +2e+00  3e-04  1e-05  8e-04  1e-02  0.8848  2e-01   1  2  1 |  0  0
 8  +4.484e-04  -2.569e-02  +7e-01  9e-05  3e-06  2e-04  4e-03  0.8369  2e-01   1  2  2 |  0  0
 9  +1.144e-04  -1.170e-02  +3e-01  4e-05  2e-06  8e-05  2e-03  0.8931  4e-01   1  1  1 |  0  0
10  +1.332e-04  -2.048e-03  +6e-02  8e-06  3e-07  1e-05  3e-04  0.8770  7e-02   1  1  1 |  0  0
11  +2.719e-05  -5.223e-04  +2e-02  2e-06  7e-08  3e-06  8e-05  0.7952  6e-02   2  1  1 |  0  0
12  +1.176e-05  -1.628e-04  +5e-03  6e-07  2e-08  1e-06  2e-05  0.8705  2e-01   1  1  1 |  0  0
13  +1.093e-06  -1.774e-05  +5e-04  7e-08  2e-09  1e-07  3e-06  0.9012  1e-02   1  1  1 |  0  0
14  +3.260e-07  -6.049e-06  +2e-04  2e-08  8e-10  4e-08  9e-07  0.7683  1e-01   2  1  1 |  0  0
15  +1.457e-07  -2.998e-06  +9e-05  1e-08  4e-10  2e-08  4e-07  0.6779  3e-01   2  1  1 |  0  0
16  -2.956e-08  -7.127e-07  +2e-05  2e-09  9e-11  4e-09  1e-07  0.9537  2e-01   1  1  1 |  0  0
17  -6.649e-08  -1.626e-07  +3e-06  3e-10  1e-11  6e-10  1e-08  0.9809  1e-01   1  1  1 |  0  0
18  -7.336e-08  -7.863e-08  +2e-07  2e-11  7e-13  3e-11  7e-10  0.9533  9e-03   1  1  1 |  0  0
19  -7.372e-08  -7.429e-08  +2e-08  2e-12  1e-13  3e-12  8e-11  0.8967  5e-03   2  1  1 |  0  0
20  -7.375e-08  -7.392e-08  +5e-09  7e-13  4e-14  1e-12  2e-11  0.8615  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=6.7e-13, reltol=6.8e-02, abstol=5.1e-09).
Runtime: 0.009857 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.687e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.713e+00  -3.201e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3950  3e-01   1  1  1 |  0  0
 2  +7.437e-01  -2.824e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8793  9e-02   1  1  1 |  0  0
 3  +2.160e-01  -1.736e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5358  2e-01   2  2  2 |  0  0
 4  +5.349e-02  -6.184e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6783  7e-02   1  2  2 |  0  0
 5  +1.211e-03  -5.120e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5641  6e-01   1  2  1 |  0  0
 6  -6.166e-03  -2.726e-01  +7e+00  1e-03  4e-05  4e-03  4e-02  0.9019  5e-01   1  2  2 |  0  0
 7  -1.970e-03  -8.522e-02  +2e+00  3e-04  1e-05  7e-04  1e-02  0.8849  2e-01   1  2  1 |  0  0
 8  +4.461e-04  -2.569e-02  +7e-01  9e-05  3e-06  2e-04  4e-03  0.8368  2e-01   1  2  2 |  0  0
 9  +1.118e-04  -1.164e-02  +3e-01  4e-05  2e-06  8e-05  2e-03  0.8937  4e-01   1  1  1 |  0  0
10  +1.336e-04  -2.035e-03  +6e-02  8e-06  3e-07  1e-05  3e-04  0.8791  7e-02   1  1  1 |  0  0
11  +2.930e-05  -5.569e-04  +2e-02  2e-06  8e-08  4e-06  8e-05  0.7812  7e-02   1  1  1 |  0  0
12  +1.327e-05  -1.810e-04  +6e-03  7e-07  3e-08  1e-06  3e-05  0.8702  2e-01   1  1  1 |  0  0
13  +1.255e-06  -1.942e-05  +6e-04  7e-08  3e-09  1e-07  3e-06  0.9021  9e-03   2  1  1 |  0  0
14  +4.395e-07  -6.642e-06  +2e-04  3e-08  9e-10  4e-08  1e-06  0.7676  1e-01   2  1  1 |  0  0
15  +2.469e-07  -3.389e-06  +1e-04  1e-08  5e-10  2e-08  5e-07  0.6666  3e-01   2  1  1 |  0  0
16  +4.839e-08  -7.865e-07  +2e-05  3e-09  1e-10  5e-09  1e-07  0.9353  2e-01   2  1  1 |  0  0
17  +4.662e-09  -1.314e-07  +4e-06  5e-10  2e-11  8e-10  2e-08  0.9797  1e-01   1  1  1 |  0  0
18  -5.047e-09  -1.290e-08  +2e-07  3e-11  1e-12  5e-11  1e-09  0.9501  8e-03   1  1  1 |  0  0
19  -5.612e-09  -6.149e-09  +2e-08  2e-12  1e-13  3e-12  8e-11  0.9342  3e-03   2  1  1 |  0  0
20  -5.640e-09  -5.764e-09  +4e-09  5e-13  3e-14  8e-13  2e-11  0.9058  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=4.5e-13, reltol=6.3e-01, abstol=3.6e-09).
Runtime: 0.009674 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.687e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.714e+00  -3.201e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3950  3e-01   1  1  1 |  0  0
 2  +7.435e-01  -2.824e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8793  9e-02   1  1  1 |  0  0
 3  +2.159e-01  -1.736e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5358  2e-01   2  2  2 |  0  0
 4  +5.347e-02  -6.184e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6783  7e-02   1  2  2 |  0  0
 5  +1.203e-03  -5.120e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5641  6e-01   1  2  1 |  0  0
 6  -6.168e-03  -2.726e-01  +7e+00  1e-03  4e-05  4e-03  4e-02  0.9019  5e-01   1  2  2 |  0  0
 7  -1.969e-03  -8.521e-02  +2e+00  3e-04  1e-05  7e-04  1e-02  0.8849  2e-01   1  2  1 |  0  0
 8  +4.458e-04  -2.569e-02  +7e-01  9e-05  3e-06  2e-04  4e-03  0.8368  2e-01   1  2  2 |  0  0
 9  +1.113e-04  -1.163e-02  +3e-01  4e-05  2e-06  8e-05  2e-03  0.8937  4e-01   1  1  1 |  0  0
10  +1.336e-04  -2.034e-03  +6e-02  8e-06  3e-07  1e-05  3e-04  0.8792  7e-02   1  1  1 |  0  0
11  +2.955e-05  -5.613e-04  +2e-02  2e-06  8e-08  4e-06  8e-05  0.7796  7e-02   1  1  1 |  0  0
12  +1.343e-05  -1.829e-04  +6e-03  7e-07  3e-08  1e-06  3e-05  0.8706  2e-01   1  1  1 |  0  0
13  +1.271e-06  -1.962e-05  +6e-04  7e-08  3e-09  1e-07  3e-06  0.9022  9e-03   1  1  1 |  0  0
14  +4.504e-07  -6.717e-06  +2e-04  3e-08  9e-10  4e-08  1e-06  0.7678  1e-01   2  1  1 |  0  0
15  +2.564e-07  -3.441e-06  +1e-04  1e-08  5e-10  2e-08  5e-07  0.6667  3e-01   2  1  1 |  0  0
16  +5.466e-08  -7.969e-07  +2e-05  3e-09  1e-10  5e-09  1e-07  0.9325  2e-01   2  1  1 |  0  0
17  +1.034e-08  -1.322e-07  +4e-06  5e-10  2e-11  9e-10  2e-08  0.9788  1e-01   2  1  1 |  0  0
18  +1.720e-10  -8.120e-09  +2e-07  3e-11  1e-12  5e-11  1e-09  0.9497  8e-03   2  1  1 |  0  0
19  -4.279e-10  -9.635e-10  +2e-08  2e-12  1e-13  3e-12  8e-11  0.9380  3e-03   2  1  1 |  0  0
20  -4.558e-10  -5.737e-10  +3e-09  4e-13  3e-14  7e-13  2e-11  0.9122  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=4.2e-13, reltol=7.4e+00, abstol=3.4e-09).
Runtime: 0.009765 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.687e+00  -1.087e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.714e+00  -3.201e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3951  3e-01   1  1  1 |  0  0
 2  +7.435e-01  -2.824e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8793  9e-02   1  1  1 |  0  0
 3  +2.159e-01  -1.736e+00  +5e+01  9e-03  4e-04  1e-01  3e-01  0.5359  2e-01   2  2  2 |  0  0
 4  +5.346e-02  -6.183e-01  +2e+01  3e-03  1e-04  4e-02  1e-01  0.6783  7e-02   1  2  2 |  0  0
 5  +1.198e-03  -5.120e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.5641  6e-01   1  2  1 |  0  0
 6  -6.169e-03  -2.726e-01  +7e+00  1e-03  4e-05  4e-03  4e-02  0.9019  5e-01   1  2  2 |  0  0
 7  -1.970e-03  -8.520e-02  +2e+00  3e-04  1e-05  7e-04  1e-02  0.8849  2e-01   1  2  1 |  0  0
 8  +4.457e-04  -2.569e-02  +7e-01  9e-05  3e-06  2e-04  4e-03  0.8368  2e-01   1  2  2 |  0  0
 9  +1.111e-04  -1.163e-02  +3e-01  4e-05  2e-06  8e-05  2e-03  0.8938  4e-01   1  1  1 |  0  0
10  +1.337e-04  -2.036e-03  +6e-02  8e-06  3e-07  1e-05  3e-04  0.8792  7e-02   1  1  1 |  0  0
11  +2.952e-05  -5.609e-04  +2e-02  2e-06  8e-08  4e-06  8e-05  0.7798  7e-02   2  1  1 |  0  0
12  +1.339e-05  -1.824e-04  +6e-03  7e-07  3e-08  1e-06  3e-05  0.8712  2e-01   1  1  1 |  0  0
13  +1.267e-06  -1.956e-05  +6e-04  7e-08  3e-09  1e-07  3e-06  0.9022  9e-03   1  1  1 |  0  0
14  +4.494e-07  -6.694e-06  +2e-04  3e-08  9e-10  4e-08  1e-06  0.7683  1e-01   1  1  1 |  0  0
15  +2.561e-07  -3.431e-06  +1e-04  1e-08  5e-10  2e-08  5e-07  0.6668  3e-01   2  1  1 |  0  0
16  +5.494e-08  -7.947e-07  +2e-05  3e-09  1e-10  5e-09  1e-07  0.9322  2e-01   2  1  1 |  0  0
17  +1.075e-08  -1.320e-07  +4e-06  5e-10  2e-11  9e-10  2e-08  0.9786  1e-01   2  1  1 |  0  0
18  +5.735e-10  -7.738e-09  +2e-07  3e-11  1e-12  5e-11  1e-09  0.9496  8e-03   1  1  1 |  0  0
19  -2.814e-11  -5.607e-10  +2e-08  2e-12  1e-13  3e-12  7e-11  0.9385  3e-03   2  1  1 |  0  0
20  -5.593e-11  -1.723e-10  +3e-09  4e-13  3e-14  7e-13  2e-11  0.9131  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=4.2e-13, reltol=6.0e+01, abstol=3.3e-09).
Runtime: 0.009921 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.196e+01  -1.475e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +3.004e+00  -7.379e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2565  4e-01   1  2  2 |  0  0
 2  -1.435e+00  -1.595e+01  +2e+02  5e-02  2e-03  5e-01  1e+00  0.7113  1e-01   1  1  1 |  0  0
 3  -4.574e+00  -8.439e+00  +8e+01  1e-02  4e-04  1e-01  4e-01  0.7262  6e-02   2  2  2 |  0  0
 4  -5.152e+00  -6.955e+00  +4e+01  6e-03  2e-04  5e-02  2e-01  0.6273  2e-01   1  2  2 |  0  0
 5  -5.365e+00  -5.920e+00  +1e+01  2e-03  5e-05  1e-02  6e-02  0.7314  7e-02   1  2  2 |  0  0
 6  -5.438e+00  -5.614e+00  +4e+00  5e-04  2e-05  4e-03  2e-02  0.7315  7e-02   1  1  1 |  0  0
 7  -5.451e+00  -5.555e+00  +2e+00  3e-04  9e-06  2e-03  1e-02  0.6705  4e-01   1  1  2 |  0  0
 8  -5.466e+00  -5.479e+00  +3e-01  4e-05  1e-06  2e-04  1e-03  0.8957  2e-02   1  1  1 |  0  0
 9  -5.468e+00  -5.472e+00  +1e-01  1e-05  4e-07  5e-05  5e-04  0.8009  2e-01   1  1  1 |  0  0
10  -5.468e+00  -5.469e+00  +2e-02  3e-06  9e-08  1e-05  1e-04  0.7692  2e-02   1  1  1 |  0  0
11  -5.468e+00  -5.469e+00  +1e-02  2e-06  5e-08  6e-06  7e-05  0.6113  3e-01   1  1  1 |  0  0
12  -5.469e+00  -5.469e+00  +4e-03  5e-07  2e-08  2e-06  2e-05  0.7483  4e-02   2  1  1 |  0  0
13  -5.469e+00  -5.469e+00  +2e-03  2e-07  6e-09  6e-07  8e-06  0.7365  2e-01   1  1  1 |  0  0
14  -5.469e+00  -5.469e+00  +5e-04  6e-08  2e-09  2e-07  2e-06  0.7494  6e-02   2  1  1 |  0  0
15  -5.469e+00  -5.469e+00  +1e-04  2e-08  4e-10  4e-08  6e-07  0.8787  1e-01   2  1  1 |  0  0
16  -5.469e+00  -5.469e+00  +3e-05  4e-09  1e-10  1e-08  1e-07  0.7908  4e-02   2  1  1 |  0  0
17  -5.469e+00  -5.469e+00  +4e-06  5e-10  2e-11  1e-09  2e-08  0.9475  1e-01   2  1  1 |  0  0
18  -5.469e+00  -5.469e+00  +6e-07  8e-11  2e-12  2e-10  3e-09  0.8556  1e-02   1  1  1 |  0  0
19  -5.469e+00  -5.469e+00  +6e-08  8e-12  2e-13  2e-11  3e-10  0.9697  7e-02   2  1  1 |  0  0
20  -5.469e+00  -5.469e+00  +6e-09  8e-13  2e-14  2e-12  3e-11  0.9023  3e-03   2  1  1 |  0  0

OPTIMAL (within feastol=7.9e-13, reltol=1.1e-09, abstol=6.1e-09).
Runtime: 0.009737 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.482e+00  -1.083e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.877e+00  -3.959e+01  +4e+02  2e-01  2e-02  2e+00  2e+00  0.3630  4e-01   1  1  1 |  0  0
 2  +6.343e-01  -2.051e+00  +7e+01  1e-02  1e-03  9e-01  4e-01  0.9569  1e-01   1  1  1 |  0  0
 3  +3.171e-01  -1.972e+00  +6e+01  1e-02  1e-03  7e-01  3e-01  0.2646  4e-01   1  1  1 |  0  0
 4  -6.444e-02  -7.635e-01  +2e+01  3e-03  3e-04  2e-01  1e-01  0.7418  8e-02   1  1  1 |  0  0
 5  -9.653e-02  -7.544e-01  +2e+01  3e-03  3e-04  1e-01  1e-01  0.3296  7e-01   1  2  1 |  0  0
 6  -1.811e-01  -5.964e-01  +1e+01  2e-03  1e-04  3e-02  6e-02  0.7213  4e-01   1  2  1 |  0  0
 7  -2.006e-01  -3.940e-01  +5e+00  7e-04  6e-05  2e-03  2e-02  0.9740  4e-01   1  1  1 |  0  0
 8  -2.161e-01  -2.937e-01  +2e+00  3e-04  2e-05  7e-04  1e-02  0.8030  3e-01   1  1  1 |  0  0
 9  -2.250e-01  -2.593e-01  +9e-01  1e-04  1e-05  3e-04  4e-03  0.6943  2e-01   1  1  1 |  0  0
10  -2.257e-01  -2.493e-01  +6e-01  7e-05  7e-06  2e-04  3e-03  0.6623  5e-01   1  1  1 |  0  0
11  -2.304e-01  -2.364e-01  +2e-01  2e-05  2e-06  4e-05  8e-04  0.8948  2e-01   1  1  1 |  0  0
12  -2.313e-01  -2.335e-01  +6e-02  7e-06  6e-07  1e-05  3e-04  0.7001  1e-01   1  1  1 |  0  0
13  -2.317e-01  -2.322e-01  +1e-02  2e-06  1e-07  3e-06  7e-05  0.9890  2e-01   1  1  1 |  0  0
14  -2.319e-01  -2.319e-01  +5e-04  6e-08  6e-09  1e-07  3e-06  0.9764  2e-02   1  1  1 |  0  0
15  -2.319e-01  -2.319e-01  +1e-05  1e-09  1e-10  2e-09  6e-08  0.9776  1e-04   2  1  1 |  0  0
16  -2.319e-01  -2.319e-01  +1e-06  1e-10  1e-11  2e-10  5e-09  0.9148  5e-03   2  1  1 |  0  0
17  -2.319e-01  -2.319e-01  +6e-08  7e-12  4e-12  1e-11  3e-10  0.9494  8e-03   2  1  1 |  0  0
18  -2.319e-01  -2.319e-01  +3e-09  3e-12  4e-12  7e-13  2e-11  0.9665  2e-02   2  1  1 |  0  0

OPTIMAL (within feastol=3.8e-12, reltol=1.4e-08, abstol=3.2e-09).
Runtime: 0.008310 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.626e+00  -1.080e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.339e+00  -3.420e+01  +4e+02  2e-01  1e-02  2e+00  2e+00  0.3901  3e-01   1  1  1 |  0  0
 2  +9.687e-01  -3.166e+00  +9e+01  2e-02  1e-03  5e-01  5e-01  0.8624  1e-01   1  1  1 |  0  0
 3  +3.528e-01  -1.862e+00  +5e+01  1e-02  6e-04  2e-01  3e-01  0.5138  2e-01   1  2  2 |  0  0
 4  +7.253e-02  -7.385e-01  +2e+01  3e-03  2e-04  8e-02  1e-01  0.6575  7e-02   1  2  2 |  0  0
 5  +1.688e-02  -6.269e-01  +2e+01  3e-03  1e-04  4e-02  8e-02  0.5393  6e-01   1  2  2 |  0  0
 6  -1.469e-02  -3.440e-01  +8e+00  1e-03  6e-05  2e-02  4e-02  0.6044  2e-01   1  2  1 |  0  0
 7  -2.506e-02  -1.249e-01  +3e+00  4e-04  2e-05  4e-03  1e-02  0.7251  4e-02   1  1  1 |  0  0
 8  -2.973e-02  -7.860e-02  +1e+00  2e-04  9e-06  3e-04  6e-03  0.9890  5e-01   1  1  1 |  0  0
 9  -3.062e-02  -4.161e-02  +3e-01  4e-05  2e-06  7e-05  1e-03  0.8103  4e-02   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.092e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.104e-02
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.092e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.120e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.052e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.750e-03
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.052e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.088e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.052e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 8.632e-04
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.052e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.153e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.029e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.681e-04
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.029e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.136e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.089e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.200e-05
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.089e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.091e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.037e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 6.078e-06
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.037e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.111e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.046e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.187e-06
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.046e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.150e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.068e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.846e+00  -1.141e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.770e+00  -2.841e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4725  2e-01   1  1  1 |  0  0
 2  +6.908e-01  -4.903e+00  +1e+02  3e-02  9e-04  2e-01  6e-01  0.7637  5e-02   1  1  1 |  0  0
 3  +1.286e-01  -2.717e+00  +6e+01  1e-02  4e-04  9e-02  3e-01  0.5540  2e-01   2  2  2 |  0  0
 4  +4.057e-02  -9.677e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.6492  5e-02   2  2  2 |  0  0
 5  -1.110e-02  -3.729e-01  +9e+00  1e-03  4e-05  7e-03  4e-02  0.8156  2e-01   2  2  2 |  0  0
 6  -1.870e-02  -1.476e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.7725  2e-01   2  2  2 |  0  0
 7  -1.368e-02  -4.791e-02  +8e-01  1e-04  3e-06  5e-04  4e-03  0.7727  5e-02   1  2  2 |  0  0
 8  -1.184e-02  -2.974e-02  +4e-01  6e-05  2e-06  2e-04  2e-03  0.7421  4e-01   1  2  2 |  0  0
 9  -1.140e-02  -1.582e-02  +1e-01  2e-05  4e-07  4e-05  5e-04  0.8892  2e-01   1  1  1 |  0  0
10  -1.109e-02  -1.292e-02  +4e-02  7e-06  2e-07  1e-05  2e-04  0.8964  3e-01   1  2  2 |  0  0
11  -1.106e-02  -1.135e-02  +7e-03  1e-06  3e-08  2e-06  4e-05  0.8926  6e-02   1  1  1 |  0  0
12  -1.105e-02  -1.112e-02  +2e-03  3e-07  7e-09  5e-07  9e-06  0.9432  2e-01   1  1  1 |  0  0
13  -1.104e-02  -1.106e-02  +5e-04  7e-08  2e-09  1e-07  2e-06  0.8259  1e-01   2  2  2 |  0  0
14  -1.104e-02  -1.105e-02  +1e-04  2e-08  4e-10  3e-08  5e-07  0.8511  8e-02   2  1  1 |  0  0
15  -1.104e-02  -1.104e-02  +4e-05  6e-09  1e-10  1e-08  2e-07  0.8093  2e-01   2  1  1 |  0  0
16  -1.104e-02  -1.104e-02  +1e-05  2e-09  4e-11  3e-09  6e-08  0.8554  2e-01   2  1  1 |  0  0
17  -1.104e-02  -1.104e-02  +4e-06  6e-10  2e-11  1e-09  2e-08  0.8249  2e-01   2  1  1 |  0  0
18  -1.104e-02  -1.104e-02  +9e-07  1e-10  3e-12  2e-10  4e-09  0.8334  4e-02   1  1  1 |  0  0
19  -1.104e-02  -1.104e-02  +3e-07  5e-11  1e-12  9e-11  2e-09  0.9017  3e-01   2  1  1 |  0  0
20  -1.104e-02  -1.104e-02  +9e-08  1e-11  4e-13  2e-11  4e-10  0.8382  1e-01   2  1  1 |  0  0
21  -1.104e-02  -1.104e-02  +5e-08  7e-12  2e-13  1e-11  2e-10  0.8200  4e-01   1  1  1 |  0  0
22  -1.104e-02  -1.104e-02  +7e-09  1e-12  5e-14  2e-12  3e-11  0.9057  6e-02   1  1  1 |  0  0

OPTIMAL (within feastol=9.8e-13, reltol=6.1e-07, abstol=6.7e-09).
Runtime: 0.011167 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.846e+00  -1.163e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.183e+00  -2.725e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.5068  2e-01   1  1  1 |  0  0
 2  +5.761e-01  -5.757e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7243  5e-02   2  1  2 |  0  0
 3  +2.495e-02  -2.760e+00  +6e+01  1e-02  3e-04  7e-02  3e-01  0.6105  2e-01   2  2  2 |  0  0
 4  +6.410e-03  -9.956e-01  +2e+01  4e-03  9e-05  2e-02  1e-01  0.6675  8e-02   2  2  2 |  0  0
 5  -2.500e-02  -3.179e-01  +7e+00  1e-03  2e-05  4e-03  3e-02  0.8772  2e-01   2  2  2 |  0  0
 6  -1.216e-02  -8.763e-02  +2e+00  3e-04  6e-06  9e-04  9e-03  0.8041  8e-02   2  2  2 |  0  0
 7  -6.707e-03  -4.664e-02  +1e+00  1e-04  3e-06  4e-04  5e-03  0.7333  4e-01   2  2  2 |  0  0
 8  -5.155e-03  -1.575e-02  +3e-01  4e-05  8e-07  9e-05  1e-03  0.8756  2e-01   1  1  1 |  0  0
 9  -4.031e-03  -8.275e-03  +1e-01  2e-05  3e-07  3e-05  5e-04  0.9007  3e-01   2  2  2 |  0  0
10  -3.827e-03  -4.563e-03  +2e-02  3e-06  6e-08  5e-06  9e-05  0.9065  9e-02   1  1  1 |  0  0
11  -3.776e-03  -3.989e-03  +5e-03  8e-07  2e-08  1e-06  2e-05  0.8218  1e-01   1  1  2 |  0  0
12  -3.759e-03  -3.848e-03  +2e-03  3e-07  7e-09  6e-07  1e-05  0.8088  3e-01   1  2  2 |  0  0
13  -3.751e-03  -3.763e-03  +3e-04  4e-08  1e-09  8e-08  1e-06  0.9104  5e-02   2  1  2 |  0  0
14  -3.750e-03  -3.754e-03  +1e-04  1e-08  3e-10  3e-08  5e-07  0.7418  1e-01   2  1  1 |  0  0
15  -3.750e-03  -3.752e-03  +5e-05  8e-09  2e-10  1e-08  3e-07  0.7114  4e-01   1  1  1 |  0  0
16  -3.750e-03  -3.750e-03  +1e-05  2e-09  4e-11  3e-09  6e-08  0.9591  2e-01   2  1  1 |  0  0
17  -3.750e-03  -3.750e-03  +4e-06  5e-10  1e-11  1e-09  2e-08  0.9005  2e-01   2  1  1 |  0  0
18  -3.750e-03  -3.750e-03  +5e-07  8e-11  2e-12  2e-10  3e-09  0.9178  8e-02   2  1  1 |  0  0
19  -3.750e-03  -3.750e-03  +1e-07  2e-11  4e-13  3e-11  6e-10  0.9648  2e-01   2  1  1 |  0  0
20  -3.750e-03  -3.750e-03  +4e-08  6e-12  1e-13  1e-11  2e-10  0.7984  1e-01   1  1  1 |  0  0
21  -3.750e-03  -3.750e-03  +1e-08  2e-12  5e-14  4e-12  6e-11  0.7940  2e-01   2  1  1 |  0  0
22  -3.750e-03  -3.750e-03  +6e-09  1e-12  3e-14  2e-12  3e-11  0.8244  4e-01   1  1  1 |  0  0

OPTIMAL (within feastol=9.5e-13, reltol=1.7e-06, abstol=6.4e-09).
Runtime: 0.010853 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.820e+00  -1.173e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.794e+00  -2.662e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5262  2e-01   1  1  1 |  0  0
 2  +4.829e-01  -6.022e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7113  5e-02   2  2  2 |  0  0
 3  -3.043e-02  -2.676e+00  +6e+01  1e-02  3e-04  6e-02  3e-01  0.6439  2e-01   2  2  2 |  0  0
 4  -2.000e-02  -9.104e-01  +2e+01  4e-03  7e-05  2e-02  1e-01  0.7159  1e-01   2  2  2 |  0  0
 5  -5.590e-02  -7.085e-01  +1e+01  3e-03  5e-05  1e-02  7e-02  0.5136  5e-01   2  2  2 |  0  0
 6  -1.894e-02  -1.790e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.8088  7e-02   2  2  2 |  0  0
 7  -7.471e-03  -4.973e-02  +1e+00  2e-04  3e-06  5e-04  5e-03  0.8394  1e-01   2  2  2 |  0  0
 8  -2.794e-03  -2.024e-02  +4e-01  6e-05  1e-06  2e-04  2e-03  0.8189  3e-01   1  2  2 |  0  0
 9  -1.763e-03  -7.591e-03  +1e-01  2e-05  4e-07  4e-05  7e-04  0.8492  2e-01   1  1  1 |  0  0
10  -1.094e-03  -3.886e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8944  4e-01   2  2  2 |  0  0
11  -9.225e-04  -1.329e-03  +1e-02  1e-06  3e-08  3e-06  5e-05  0.9862  1e-01   1  1  1 |  0  0
12  -8.738e-04  -9.644e-04  +2e-03  3e-07  7e-09  6e-07  1e-05  0.8591  1e-01   2  2  2 |  0  0
13  -8.680e-04  -9.046e-04  +9e-04  1e-07  3e-09  2e-07  4e-06  0.7684  2e-01   1  1  1 |  0  0
14  -8.659e-04  -8.888e-04  +5e-04  8e-08  2e-09  2e-07  3e-06  0.6606  4e-01   1  1  1 |  0  0
15  -8.637e-04  -8.674e-04  +9e-05  1e-08  3e-10  3e-08  4e-07  0.9152  8e-02   1  1  1 |  0  0
16  -8.634e-04  -8.648e-04  +3e-05  5e-09  1e-10  1e-08  2e-07  0.7401  2e-01   1  1  1 |  0  0
17  -8.633e-04  -8.638e-04  +1e-05  2e-09  4e-11  3e-09  6e-08  0.8004  2e-01   2  1  1 |  0  0
18  -8.632e-04  -8.635e-04  +5e-06  8e-10  2e-11  1e-09  3e-08  0.8786  4e-01   2  1  1 |  0  0
19  -8.632e-04  -8.633e-04  +7e-07  1e-10  2e-12  2e-10  3e-09  0.9687  1e-01   2  1  1 |  0  0
20  -8.632e-04  -8.632e-04  +2e-07  2e-11  5e-13  5e-11  8e-10  0.8310  1e-01   2  1  1 |  0  0
21  -8.632e-04  -8.632e-04  +9e-08  1e-11  3e-13  3e-11  5e-10  0.6841  3e-01   2  1  1 |  0  0
22  -8.632e-04  -8.632e-04  +2e-08  3e-12  7e-14  5e-12  9e-11  0.9346  1e-01   2  1  1 |  0  0
23  -8.632e-04  -8.632e-04  +7e-09  1e-12  3e-14  2e-12  4e-11  0.7268  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.1e-12, reltol=8.6e-06, abstol=7.5e-09).
Runtime: 0.011493 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.795e+00  -1.177e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.614e+00  -2.621e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5366  2e-01   1  1  1 |  0  0
 2  +4.362e-01  -6.090e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7065  5e-02   2  2  2 |  0  0
 3  -5.806e-02  -2.575e+00  +5e+01  1e-02  2e-04  6e-02  3e-01  0.6676  2e-01   2  2  2 |  0  0
 4  -3.839e-02  -9.673e-01  +2e+01  4e-03  7e-05  2e-02  1e-01  0.6957  1e-01   2  2  2 |  0  0
 5  -6.385e-02  -7.154e-01  +1e+01  3e-03  5e-05  1e-02  7e-02  0.5171  4e-01   2  2  2 |  0  0
 6  -1.979e-02  -1.792e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.7900  5e-02   2  2  2 |  0  0
 7  -7.542e-03  -4.945e-02  +1e+00  2e-04  3e-06  5e-04  5e-03  0.8690  2e-01   2  2  2 |  0  0
 8  -1.935e-03  -1.661e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.8328  2e-01   1  2  2 |  0  0
 9  -1.346e-03  -9.978e-03  +2e-01  3e-05  6e-07  7e-05  1e-03  0.7086  4e-01   1  2  2 |  0  0
10  -4.767e-04  -2.483e-03  +5e-02  7e-06  1e-07  1e-05  2e-04  0.8572  1e-01   2  2  2 |  0  0
11  -2.727e-04  -1.194e-03  +2e-02  3e-06  6e-08  7e-06  1e-04  0.7434  3e-01   1  2  2 |  0  0
12  -2.111e-04  -4.868e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.8829  2e-01   1  1  1 |  0  0
13  -1.764e-04  -2.577e-04  +2e-03  3e-07  6e-09  6e-07  9e-06  0.9391  2e-01   1  2  2 |  0  0
14  -1.697e-04  -1.807e-04  +3e-04  4e-08  8e-10  8e-08  1e-06  0.9214  6e-02   1  1  1 |  0  0
15  -1.684e-04  -1.706e-04  +5e-05  8e-09  2e-10  1e-08  2e-07  0.9890  2e-01   1  1  1 |  0  0
16  -1.682e-04  -1.688e-04  +1e-05  2e-09  4e-11  4e-09  7e-08  0.7977  8e-02   1  1  1 |  0  0
17  -1.681e-04  -1.683e-04  +4e-06  6e-10  1e-11  1e-09  2e-08  0.8336  2e-01   2  1  1 |  0  0
18  -1.681e-04  -1.682e-04  +2e-06  3e-10  5e-12  5e-10  9e-09  0.8508  3e-01   2  1  1 |  0  0
19  -1.681e-04  -1.681e-04  +3e-07  4e-11  9e-13  8e-11  1e-09  0.9508  1e-01   2  1  1 |  0  0
20  -1.681e-04  -1.681e-04  +7e-08  1e-11  2e-13  2e-11  3e-10  0.9807  2e-01   3  1  1 |  0  0
21  -1.681e-04  -1.681e-04  +2e-08  3e-12  7e-14  5e-12  9e-11  0.7887  9e-02   1  1  1 |  0  0
22  -1.681e-04  -1.681e-04  +9e-09  1e-12  4e-14  3e-12  4e-11  0.8162  4e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=5.2e-05, abstol=8.8e-09).
Runtime: 0.011326 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.782e+00  -1.178e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.532e+00  -2.601e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5414  2e-01   1  1  1 |  0  0
 2  +4.138e-01  -6.108e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7047  5e-02   2  2  2 |  0  0
 3  -7.196e-02  -2.506e+00  +5e+01  1e-02  2e-04  5e-02  3e-01  0.6821  2e-01   2  2  2 |  0  0
 4  -5.008e-02  -1.000e+00  +2e+01  4e-03  7e-05  2e-02  1e-01  0.6824  1e-01   2  2  2 |  0  0
 5  -6.747e-02  -7.139e-01  +1e+01  3e-03  5e-05  1e-02  7e-02  0.5202  4e-01   2  2  2 |  0  0
 6  -2.056e-02  -1.800e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.7824  4e-02   2  2  2 |  0  0
 7  -7.805e-03  -4.982e-02  +1e+00  2e-04  3e-06  4e-04  5e-03  0.8862  2e-01   2  2  2 |  0  0
 8  -5.192e-03  -3.702e-02  +7e-01  1e-04  2e-06  3e-04  4e-03  0.4732  5e-01   1  2  2 |  0  0
 9  -1.603e-03  -1.133e-02  +2e-01  3e-05  7e-07  8e-05  1e-03  0.7727  1e-01   1  2  2 |  0  0
10  -3.554e-04  -2.629e-03  +5e-02  8e-06  2e-07  2e-05  3e-04  0.8918  1e-01   1  2  2 |  0  0
11  -1.545e-04  -1.062e-03  +2e-02  3e-06  6e-08  7e-06  1e-04  0.7466  2e-01   2  2  1 |  0  0
12  -6.596e-05  -2.923e-04  +5e-03  8e-07  2e-08  2e-06  3e-05  0.8785  1e-01   1  2  2 |  0  0
13  -4.187e-05  -1.305e-04  +2e-03  3e-07  6e-09  6e-07  1e-05  0.7866  2e-01   2  2  2 |  0  0
14  -3.537e-05  -5.849e-05  +5e-04  8e-08  2e-09  2e-07  3e-06  0.9011  2e-01   2  1  1 |  0  0
15  -3.253e-05  -3.730e-05  +1e-04  2e-08  3e-10  3e-08  6e-07  0.9103  1e-01   2  2  2 |  0  0
16  -3.210e-05  -3.287e-05  +2e-05  3e-09  5e-11  5e-09  9e-08  0.8761  4e-02   2  1  1 |  0  0
17  -3.203e-05  -3.223e-05  +5e-06  7e-10  1e-11  1e-09  2e-08  0.9374  2e-01   2  1  1 |  0  0
18  -3.200e-05  -3.204e-05  +9e-07  1e-10  3e-12  3e-10  4e-09  0.8792  8e-02   2  1  1 |  0  0
19  -3.200e-05  -3.201e-05  +2e-07  2e-11  5e-13  5e-11  8e-10  0.9325  1e-01   1  1  1 |  0  0
20  -3.200e-05  -3.200e-05  +3e-08  5e-12  1e-13  1e-11  2e-10  0.8865  1e-01   1  1  1 |  0  0
21  -3.200e-05  -3.200e-05  +6e-09  8e-13  2e-14  2e-12  3e-11  0.9286  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=8.5e-13, reltol=1.8e-04, abstol=5.7e-09).
Runtime: 0.010874 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.777e+00  -1.179e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.495e+00  -2.591e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5435  2e-01   1  2  1 |  0  0
 2  +4.038e-01  -6.112e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7040  5e-02   2  2  2 |  0  0
 3  -7.855e-02  -2.468e+00  +5e+01  1e-02  2e-04  5e-02  3e-01  0.6899  2e-01   2  2  2 |  0  0
 4  -5.629e-02  -1.016e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.6753  1e-01   2  2  2 |  0  0
 5  -6.897e-02  -7.116e-01  +1e+01  3e-03  5e-05  1e-02  7e-02  0.5213  4e-01   2  2  2 |  0  0
 6  -2.100e-02  -1.807e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.7790  4e-02   2  2  2 |  0  0
 7  -8.130e-03  -5.172e-02  +1e+00  2e-04  3e-06  5e-04  5e-03  0.8846  2e-01   2  2  2 |  0  0
 8  -6.502e-03  -4.469e-02  +9e-01  1e-04  3e-06  4e-04  4e-03  0.3141  6e-01   1  2  2 |  0  0
 9  -1.895e-03  -1.375e-02  +3e-01  4e-05  8e-07  1e-04  1e-03  0.8154  2e-01   1  2  2 |  0  0
10  -5.793e-04  -4.490e-03  +9e-02  1e-05  3e-07  3e-05  5e-04  0.9440  3e-01   1  2  2 |  0  0
11  -1.712e-04  -1.365e-03  +3e-02  4e-06  8e-08  8e-06  1e-04  0.7983  1e-01   2  2  2 |  0  0
12  -3.706e-05  -2.616e-04  +5e-03  8e-07  2e-08  2e-06  3e-05  0.8895  9e-02   1  2  2 |  0  0
13  -1.656e-05  -1.076e-04  +2e-03  3e-07  6e-09  6e-07  1e-05  0.7761  2e-01   2  2  2 |  0  0
14  -1.074e-05  -4.270e-05  +8e-04  1e-07  2e-09  2e-07  4e-06  0.8192  2e-01   1  1  1 |  0  0
15  -7.154e-06  -1.714e-05  +2e-04  4e-08  7e-10  7e-08  1e-06  0.9328  3e-01   2  2  2 |  0  0
16  -6.247e-06  -7.540e-06  +3e-05  5e-09  9e-11  9e-09  1e-07  0.9233  6e-02   1  1  1 |  0  0
17  -6.112e-06  -6.347e-06  +6e-06  8e-10  2e-11  2e-09  3e-08  0.9404  1e-01   2  1  1 |  0  0
18  -6.084e-06  -6.122e-06  +9e-07  1e-10  3e-12  3e-10  4e-09  0.8844  6e-02   1  1  1 |  0  0
19  -6.080e-06  -6.087e-06  +2e-07  3e-11  5e-13  5e-11  9e-10  0.9106  1e-01   1  1  1 |  0  0
20  -6.079e-06  -6.081e-06  +5e-08  7e-12  1e-13  1e-11  2e-10  0.8545  1e-01   1  1  1 |  0  0
21  -6.079e-06  -6.079e-06  +8e-09  1e-12  3e-14  2e-12  4e-11  0.9244  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=1.4e-03, abstol=8.5e-09).
Runtime: 0.011074 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation

(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 2.348e-07
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.068e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.031e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.067e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 4.662e-08
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.067e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.116e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.032e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 9.259e-09
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.032e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.111e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.048e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.870e-09
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.048e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.097e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.022e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 3.657e-10
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.022e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.083e-02 seconds
Reranking users:   0%|          | 2/2064 [00:00<13:14,  2.60it/s](CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.064e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 6.795e+00
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.064e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 7.710e-03 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.694e-01
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.184e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:13 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:13 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:13 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:13 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:13 PM: Finished problem compilation (took 1.048e-02 seconds).
(CVXPY) Jun 21 07:40:13 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:13 PM: Optimal value: 1.614e-02
(CVXPY) Jun 21 07:40:13 PM: Compilation took 1.048e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Solver (including time spent in interface) took 1.079e-02 seconds
(CVXPY) Jun 21 07:40:13 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:13 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:13 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:13 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:13 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:13 PM: Compiling problem (target solver=ECOS).

 9  -4.196e-04  -3.295e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8729  8e-02   1  2  2 |  0  0
10  -1.342e-04  -1.223e-03  +3e-02  4e-06  7e-08  8e-06  1e-04  0.9361  3e-01   1  2  2 |  0  0
11  -6.018e-05  -4.312e-04  +9e-03  1e-06  3e-08  3e-06  4e-05  0.7815  2e-01   1  1  1 |  0  0
12  -1.558e-05  -1.802e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.9431  4e-01   2  2  2 |  0  0
13  -2.807e-06  -2.327e-05  +5e-04  7e-08  1e-09  1e-07  2e-06  0.9623  9e-02   2  1  1 |  0  0
14  -7.330e-07  -4.196e-06  +8e-05  1e-08  2e-10  2e-08  4e-07  0.9821  2e-01   2  1  1 |  0  0
15  -3.397e-07  -1.148e-06  +2e-05  3e-09  6e-11  6e-09  9e-08  0.8309  8e-02   2  1  1 |  0  0
16  -2.639e-07  -4.610e-07  +5e-06  7e-10  1e-11  1e-09  2e-08  0.8671  1e-01   2  1  1 |  0  0
17  -2.401e-07  -2.808e-07  +1e-06  1e-10  3e-12  3e-10  5e-09  0.9074  1e-01   2  1  1 |  0  0
18  -2.356e-07  -2.411e-07  +1e-07  2e-11  4e-13  4e-11  6e-10  0.9268  7e-02   2  1  1 |  0  0
19  -2.350e-07  -2.364e-07  +3e-08  5e-12  1e-13  9e-12  2e-10  0.8604  1e-01   3  1  1 |  0  0
20  -2.349e-07  -2.352e-07  +6e-09  9e-13  2e-14  2e-12  3e-11  0.8829  9e-02   1  1  1 |  0  0

OPTIMAL (within feastol=9.4e-13, reltol=2.7e-02, abstol=6.3e-09).
Runtime: 0.010274 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.774e+00  -1.179e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.469e+00  -2.584e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5451  2e-01   1  2  1 |  0  0
 2  +3.966e-01  -6.114e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7035  5e-02   2  2  2 |  0  0
 3  -8.366e-02  -2.436e+00  +5e+01  1e-02  2e-04  5e-02  2e-01  0.6963  2e-01   2  2  2 |  0  0
 4  -6.156e-02  -1.037e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.6654  1e-01   2  2  2 |  0  0
 5  -6.374e-02  -6.288e-01  +1e+01  2e-03  4e-05  9e-03  6e-02  0.5929  3e-01   2  2  2 |  0  0
 6  -1.943e-02  -1.536e-01  +3e+00  5e-04  9e-06  2e-03  2e-02  0.7930  4e-02   2  2  2 |  0  0
 7  -8.702e-03  -6.427e-02  +1e+00  2e-04  4e-06  6e-04  6e-03  0.8120  3e-01   1  2  2 |  0  0
 8  -3.184e-03  -2.218e-02  +4e-01  7e-05  1e-06  2e-04  2e-03  0.7096  7e-02   2  2  2 |  0  0
 9  -1.247e-03  -9.654e-03  +2e-01  3e-05  6e-07  7e-05  1e-03  0.8120  3e-01   1  2  2 |  0  0
10  -3.238e-04  -2.397e-03  +5e-02  7e-06  1e-07  2e-05  2e-04  0.7747  3e-02   2  2  2 |  0  0
11  -5.824e-05  -4.867e-04  +1e-02  2e-06  3e-08  3e-06  5e-05  0.8995  1e-01   1  2  2 |  0  0
12  -1.563e-05  -1.234e-04  +3e-03  4e-07  7e-09  8e-07  1e-05  0.8594  1e-01   2  2  2 |  0  0
13  -3.037e-06  -2.652e-05  +6e-04  8e-08  2e-09  2e-07  3e-06  0.9111  1e-01   1  2  2 |  0  0
14  -1.470e-06  -1.140e-05  +2e-04  3e-08  7e-10  7e-08  1e-06  0.7697  2e-01   1  1  1 |  0  0
15  -6.227e-07  -5.409e-06  +1e-04  2e-08  3e-10  3e-08  6e-07  0.8054  4e-01   2  1  2 |  0  0
16  -1.838e-07  -1.104e-06  +2e-05  3e-09  6e-11  6e-09  1e-07  0.9547  2e-01   2  1  1 |  0  0
17  -5.835e-08  -1.518e-07  +2e-06  3e-10  6e-12  6e-10  1e-08  0.9565  6e-02   2  1  1 |  0  0
18  -4.809e-08  -5.829e-08  +2e-07  4e-11  7e-13  7e-11  1e-09  0.9209  3e-02   2  1  1 |  0  0
19  -4.700e-08  -4.922e-08  +5e-08  8e-12  2e-13  2e-11  3e-10  0.8278  6e-02   2  1  1 |  0  0
20  -4.681e-08  -4.778e-08  +2e-08  3e-12  7e-14  7e-12  1e-10  0.7032  2e-01   1  1  1 |  0  0
21  -4.673e-08  -4.705e-08  +8e-09  1e-12  3e-14  2e-12  4e-11  0.8738  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.1e-12, reltol=1.6e-01, abstol=7.5e-09).
Runtime: 0.011117 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.773e+00  -1.179e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.468e+00  -2.583e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5452  2e-01   1  2  1 |  0  0
 2  +3.962e-01  -6.114e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7035  5e-02   2  2  2 |  0  0
 3  -8.394e-02  -2.434e+00  +5e+01  1e-02  2e-04  5e-02  2e-01  0.6967  2e-01   2  2  2 |  0  0
 4  -6.188e-02  -1.039e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.6642  1e-01   2  2  2 |  0  0
 5  -6.262e-02  -6.160e-01  +1e+01  2e-03  4e-05  9e-03  6e-02  0.6031  3e-01   2  2  2 |  0  0
 6  -1.901e-02  -1.479e-01  +3e+00  5e-04  9e-06  2e-03  1e-02  0.7988  5e-02   2  2  2 |  0  0
 7  -9.076e-03  -6.937e-02  +1e+00  2e-04  4e-06  6e-04  7e-03  0.7726  3e-01   1  2  2 |  0  0
 8  -3.156e-03  -2.232e-02  +4e-01  7e-05  1e-06  2e-04  2e-03  0.7137  5e-02   2  2  2 |  0  0
 9  -1.338e-03  -1.040e-02  +2e-01  3e-05  6e-07  8e-05  1e-03  0.7779  3e-01   1  2  2 |  0  0
10  -3.695e-04  -2.727e-03  +6e-02  8e-06  2e-07  2e-05  3e-04  0.7622  3e-02   1  2  2 |  0  0
11  -6.955e-05  -5.809e-04  +1e-02  2e-06  3e-08  4e-06  6e-05  0.8952  1e-01   1  2  2 |  0  0
12  -1.735e-05  -1.360e-04  +3e-03  4e-07  8e-09  9e-07  1e-05  0.8422  9e-02   2  2  2 |  0  0
13  -3.262e-06  -2.888e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9241  2e-01   1  2  2 |  0  0
14  -1.405e-06  -1.091e-05  +2e-04  3e-08  7e-10  7e-08  1e-06  0.9037  3e-01   2  1  1 |  0  0
15  -5.032e-07  -4.506e-06  +9e-05  1e-08  3e-10  3e-08  5e-07  0.8135  3e-01   2  1  2 |  0  0
16  -1.267e-07  -9.140e-07  +2e-05  3e-09  5e-11  5e-09  9e-08  0.9351  1e-01   1  1  1 |  0  0
17  -2.091e-08  -1.126e-07  +2e-06  3e-10  6e-12  6e-10  1e-08  0.9491  7e-02   2  1  1 |  0  0
18  -1.069e-08  -2.024e-08  +2e-07  3e-11  7e-13  7e-11  1e-09  0.9310  4e-02   1  1  1 |  0  0
19  -9.603e-09  -1.157e-08  +5e-08  7e-12  1e-13  1e-11  2e-10  0.8634  8e-02   1  1  1 |  0  0
20  -9.448e-09  -1.020e-08  +2e-08  3e-12  6e-14  5e-12  9e-11  0.7249  1e-01   2  1  1 |  0  0
21  -9.390e-09  -9.758e-09  +9e-09  1e-12  3e-14  3e-12  4e-11  0.7437  3e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=9.2e-01, abstol=8.7e-09).
Runtime: 0.011071 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.773e+00  -1.179e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.467e+00  -2.583e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5452  2e-01   1  2  1 |  0  0
 2  +3.960e-01  -6.114e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.7035  5e-02   2  2  2 |  0  0
 3  -8.407e-02  -2.433e+00  +5e+01  1e-02  2e-04  5e-02  2e-01  0.6969  2e-01   2  2  2 |  0  0
 4  -6.203e-02  -1.041e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.6637  2e-01   2  2  2 |  0  0
 5  -6.211e-02  -6.104e-01  +1e+01  2e-03  4e-05  9e-03  6e-02  0.6074  3e-01   2  2  2 |  0  0
 6  -1.882e-02  -1.454e-01  +3e+00  5e-04  9e-06  2e-03  1e-02  0.8016  5e-02   2  2  2 |  0  0
 7  -9.284e-03  -7.195e-02  +1e+00  2e-04  4e-06  7e-04  7e-03  0.7511  3e-01   1  2  2 |  0  0
 8  -3.125e-03  -2.224e-02  +4e-01  7e-05  1e-06  2e-04  2e-03  0.7211  4e-02   1  2  2 |  0  0
 9  -1.343e-03  -1.049e-02  +2e-01  3e-05  6e-07  8e-05  1e-03  0.7695  3e-01   1  2  2 |  0  0
10  -3.775e-04  -2.787e-03  +6e-02  9e-06  2e-07  2e-05  3e-04  0.7605  3e-02   2  2  2 |  0  0
11  -7.012e-05  -5.876e-04  +1e-02  2e-06  4e-08  4e-06  6e-05  0.8973  1e-01   1  2  2 |  0  0
12  -1.751e-05  -1.373e-04  +3e-03  4e-07  8e-09  9e-07  1e-05  0.8459  9e-02   2  2  2 |  0  0
13  -3.350e-06  -2.970e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9274  2e-01   2  2  2 |  0  0
14  -1.102e-06  -8.480e-06  +2e-04  3e-08  5e-10  5e-08  9e-07  0.9715  3e-01   2  1  1 |  0  0
15  -3.726e-07  -3.291e-06  +7e-05  1e-08  2e-10  2e-08  3e-07  0.7830  2e-01   2  1  1 |  0  0
16  -1.043e-07  -8.000e-07  +2e-05  2e-09  5e-11  5e-09  8e-08  0.9105  2e-01   1  1  1 |  0  0
17  -1.376e-08  -1.089e-07  +2e-06  3e-10  7e-12  7e-10  1e-08  0.9593  1e-01   2  1  1 |  0  0
18  -3.144e-09  -1.173e-08  +2e-07  3e-11  6e-13  6e-11  1e-09  0.9448  4e-02   1  1  1 |  0  0
19  -2.195e-09  -4.236e-09  +5e-08  7e-12  1e-13  1e-11  2e-10  0.8557  1e-01   2  1  1 |  0  0
20  -2.010e-09  -2.586e-09  +1e-08  2e-12  5e-14  4e-12  7e-11  0.7944  1e-01   1  1  1 |  0  0
21  -1.963e-09  -2.225e-09  +6e-09  9e-13  2e-14  2e-12  3e-11  0.7791  3e-01   1  1  1 |  0  0

OPTIMAL (within feastol=9.3e-13, reltol=3.1e+00, abstol=6.2e-09).
Runtime: 0.010931 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.773e+00  -1.179e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.467e+00  -2.583e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5453  2e-01   1  2  1 |  0  0
 2  +3.959e-01  -6.114e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.7035  5e-02   2  2  2 |  0  0
 3  -8.413e-02  -2.433e+00  +5e+01  1e-02  2e-04  5e-02  2e-01  0.6970  2e-01   2  2  2 |  0  0
 4  -6.209e-02  -1.041e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.6635  2e-01   2  2  2 |  0  0
 5  -6.189e-02  -6.080e-01  +1e+01  2e-03  4e-05  9e-03  6e-02  0.6093  3e-01   2  2  2 |  0  0
 6  -1.874e-02  -1.442e-01  +3e+00  5e-04  9e-06  2e-03  1e-02  0.8029  5e-02   2  2  2 |  0  0
 7  -9.387e-03  -7.316e-02  +1e+00  2e-04  4e-06  7e-04  7e-03  0.7406  3e-01   1  2  2 |  0  0
 8  -3.118e-03  -2.224e-02  +4e-01  7e-05  1e-06  2e-04  2e-03  0.7270  4e-02   1  2  2 |  0  0
 9  -1.332e-03  -1.042e-02  +2e-01  3e-05  6e-07  8e-05  1e-03  0.7700  3e-01   1  2  2 |  0  0
10  -3.751e-04  -2.772e-03  +6e-02  8e-06  2e-07  2e-05  3e-04  0.7605  3e-02   2  2  2 |  0  0
11  -6.935e-05  -5.821e-04  +1e-02  2e-06  4e-08  4e-06  6e-05  0.8985  1e-01   1  2  2 |  0  0
12  -1.742e-05  -1.367e-04  +3e-03  4e-07  8e-09  9e-07  1e-05  0.8479  9e-02   2  2  2 |  0  0
13  -3.347e-06  -2.972e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9283  2e-01   1  2  2 |  0  0
14  -1.090e-06  -8.389e-06  +2e-04  3e-08  5e-10  5e-08  8e-07  0.9618  2e-01   2  1  1 |  0  0
15  -3.682e-07  -3.264e-06  +7e-05  1e-08  2e-10  2e-08  3e-07  0.7805  2e-01   1  1  1 |  0  0
16  -1.055e-07  -8.204e-07  +2e-05  3e-09  5e-11  5e-09  8e-08  0.9048  2e-01   2  1  1 |  0  0
17  -1.274e-08  -1.121e-07  +2e-06  3e-10  7e-12  7e-10  1e-08  0.9637  1e-01   1  1  1 |  0  0
18  -1.644e-09  -1.027e-08  +2e-07  3e-11  6e-13  6e-11  1e-09  0.9468  4e-02   1  1  1 |  0  0
19  -6.898e-10  -2.705e-09  +5e-08  7e-12  1e-13  1e-11  2e-10  0.8592  1e-01   2  1  1 |  0  0
20  -5.076e-10  -1.084e-09  +1e-08  2e-12  5e-14  4e-12  7e-11  0.7877  9e-02   2  1  1 |  0  0
21  -4.609e-10  -7.296e-10  +6e-09  9e-13  2e-14  2e-12  3e-11  0.7722  3e-01   1  1  1 |  0  0

OPTIMAL (within feastol=9.5e-13, reltol=1.4e+01, abstol=6.3e-09).
Runtime: 0.010790 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.239e+01  -1.445e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +2.127e+00  -7.226e+01  +6e+02  3e-01  1e-02  1e+00  3e+00  0.2640  4e-01   1  2  2 |  0  0
 2  -2.661e+00  -1.668e+01  +2e+02  5e-02  2e-03  5e-01  1e+00  0.7154  1e-01   1  1  1 |  0  0
 3  -5.877e+00  -9.975e+00  +8e+01  1e-02  4e-04  1e-01  4e-01  0.7184  8e-02   2  2  2 |  0  0
 4  -6.503e+00  -8.443e+00  +4e+01  7e-03  2e-04  6e-02  2e-01  0.5807  1e-01   1  2  2 |  0  0
 5  -6.701e+00  -7.325e+00  +1e+01  2e-03  5e-05  1e-02  7e-02  0.7798  1e-01   1  2  2 |  0  0
 6  -6.768e+00  -6.992e+00  +5e+00  7e-04  2e-05  3e-03  2e-02  0.8690  3e-01   1  1  1 |  0  0
 7  -6.789e+00  -6.831e+00  +9e-01  1e-04  4e-06  5e-04  4e-03  0.8240  2e-02   1  1  1 |  0  0
 8  -6.793e+00  -6.805e+00  +3e-01  3e-05  1e-06  1e-04  1e-03  0.8771  2e-01   1  1  1 |  0  0
 9  -6.795e+00  -6.796e+00  +3e-02  4e-06  1e-07  1e-05  1e-04  0.9160  3e-02   1  1  1 |  0  0
10  -6.795e+00  -6.795e+00  +1e-03  2e-07  4e-09  5e-07  6e-06  0.9646  7e-03   2  1  1 |  0  0
11  -6.795e+00  -6.795e+00  +2e-04  3e-08  8e-10  9e-08  1e-06  0.8229  1e-02   2  1  1 |  0  0
12  -6.795e+00  -6.795e+00  +4e-05  5e-09  1e-10  1e-08  2e-07  0.9112  1e-01   1  1  1 |  0  0
13  -6.795e+00  -6.795e+00  +2e-06  3e-10  7e-12  7e-10  9e-09  0.9526  1e-03   1  1  1 |  0  0
14  -6.795e+00  -6.795e+00  +8e-08  1e-11  3e-13  3e-11  4e-10  0.9688  1e-02   2  1  1 |  0  0
15  -6.795e+00  -6.795e+00  +6e-09  1e-12  3e-14  2e-12  3e-11  0.9208  5e-03   3  2  2 |  0  0

OPTIMAL (within feastol=9.6e-13, reltol=9.5e-10, abstol=6.5e-09).
Runtime: 0.007674 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.421e+00  -1.056e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +1.854e+00  -4.576e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3097  4e-01   1  1  1 |  0  0
 2  +5.103e-01  -3.442e+00  +9e+01  2e-02  2e-03  1e+00  6e-01  0.9180  2e-01   1  1  1 |  0  0
 3  +1.146e-01  -1.463e+00  +4e+01  8e-03  9e-04  5e-01  2e-01  0.6106  8e-02   1  1  1 |  0  0
 4  -5.028e-03  -1.045e+00  +3e+01  5e-03  6e-04  3e-01  2e-01  0.4004  2e-01   1  1  1 |  0  0
 5  -5.549e-02  -9.299e-01  +2e+01  3e-03  4e-04  7e-02  1e-01  0.8245  7e-01   1  1  1 |  0  0
 6  -1.076e-01  -4.369e-01  +9e+00  1e-03  1e-04  2e-02  4e-02  0.6540  6e-02   1  1  1 |  0  0
 7  -1.519e-01  -2.336e-01  +2e+00  3e-04  3e-05  5e-03  1e-02  0.7883  5e-02   1  1  1 |  0  0
 8  -1.550e-01  -2.137e-01  +2e+00  2e-04  2e-05  2e-03  8e-03  0.5412  5e-01   1  1  1 |  0  0
 9  -1.627e-01  -1.911e-01  +8e-01  9e-05  1e-05  9e-04  4e-03  0.6352  2e-01   1  1  1 |  0  0
10  -1.634e-01  -1.865e-01  +6e-01  7e-05  9e-06  6e-04  3e-03  0.3796  5e-01   1  1  1 |  0  0
11  -1.669e-01  -1.770e-01  +3e-01  3e-05  4e-06  2e-04  1e-03  0.6339  1e-01   1  1  1 |  0  0
12  -1.672e-01  -1.751e-01  +2e-01  3e-05  3e-06  1e-04  1e-03  0.4133  5e-01   1  1  1 |  0  0
13  -1.685e-01  -1.717e-01  +9e-02  1e-05  1e-06  4e-05  4e-04  0.7278  2e-01   1  1  1 |  0  0
14  -1.688e-01  -1.708e-01  +5e-02  6e-06  8e-07  2e-05  3e-04  0.5423  3e-01   1  1  1 |  0  0
15  -1.692e-01  -1.699e-01  +2e-02  2e-06  3e-07  7e-06  9e-05  0.7757  2e-01   1  1  1 |  0  0
16  -1.693e-01  -1.696e-01  +1e-02  1e-06  1e-07  3e-06  5e-05  0.6431  3e-01   1  1  1 |  0  0
17  -1.694e-01  -1.695e-01  +3e-03  4e-07  4e-08  8e-07  1e-05  0.7676  1e-01   2  1  1 |  0  0
18  -1.694e-01  -1.694e-01  +9e-04  1e-07  1e-08  2e-07  4e-06  0.8067  1e-01   2  1  1 |  0  0
19  -1.694e-01  -1.694e-01  +2e-04  3e-08  3e-09  6e-08  1e-06  0.7695  6e-02   2  1  1 |  0  0

(CVXPY) Jun 21 07:40:13 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.131e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.270e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.131e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 4.123e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.002e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.072e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.255e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.072e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.028e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.026e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.510e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.026e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.010e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.024e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.520e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.024e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.019e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.035e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 5.334e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.035e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 9.818e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.027e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 8.637e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.027e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.014e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.934e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.375e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.934e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.026e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.585e+00  -1.064e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.460e+00  -4.134e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3385  4e-01   1  1  1 |  0  0
 2  +9.766e-01  -2.157e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9461  1e-01   1  1  1 |  0  0
 3  +3.949e-01  -1.307e+00  +4e+01  8e-03  6e-04  4e-01  2e-01  0.5291  2e-01   1  2  1 |  0  0
 4  +1.364e-01  -6.526e-01  +2e+01  4e-03  3e-04  1e-01  1e-01  0.6008  1e-01   1  2  2 |  0  0
 5  +1.940e-02  -4.174e-01  +1e+01  2e-03  1e-04  2e-02  6e-02  0.9043  4e-01   1  2  2 |  0  0
 6  +5.477e-03  -1.973e-01  +5e+00  7e-04  5e-05  5e-03  3e-02  0.7472  3e-01   1  1  1 |  0  0
 7  +6.535e-03  -6.727e-02  +2e+00  3e-04  2e-05  5e-04  9e-03  0.9889  4e-01   1  1  1 |  0  0
 8  +2.130e-03  -2.927e-02  +8e-01  1e-04  7e-06  2e-04  4e-03  0.9890  4e-01   1  1  1 |  0  0
 9  -3.911e-04  -6.068e-03  +1e-01  2e-05  1e-06  3e-05  7e-04  0.8777  7e-02   1  1  1 |  0  0
10  -9.510e-04  -3.146e-03  +6e-02  7e-06  5e-07  1e-05  3e-04  0.7580  2e-01   1  1  1 |  0  0
11  -1.103e-03  -1.997e-03  +2e-02  3e-06  2e-07  5e-06  1e-04  0.8605  3e-01   1  1  1 |  0  0
12  -1.233e-03  -1.455e-03  +6e-03  7e-07  5e-08  1e-06  3e-05  0.8903  2e-01   1  1  1 |  0  0
13  -1.266e-03  -1.288e-03  +6e-04  8e-08  5e-09  1e-07  3e-06  0.9254  3e-02   1  1  1 |  0  0
14  -1.269e-03  -1.273e-03  +1e-04  2e-08  1e-09  3e-08  6e-07  0.9591  2e-01   2  1  1 |  0  0
15  -1.270e-03  -1.271e-03  +4e-05  5e-09  3e-10  9e-09  2e-07  0.9623  3e-01   2  1  1 |  0  0
16  -1.270e-03  -1.270e-03  +9e-06  1e-09  8e-11  2e-09  5e-08  0.8639  1e-01   2  1  1 |  0  0
17  -1.270e-03  -1.270e-03  +3e-06  3e-10  2e-11  5e-10  1e-08  0.9403  2e-01   1  1  1 |  0  0
18  -1.270e-03  -1.270e-03  +4e-07  5e-11  4e-12  8e-11  2e-09  0.8817  4e-02   2  1  1 |  0  0
19  -1.270e-03  -1.270e-03  +1e-07  2e-11  1e-12  3e-11  6e-10  0.9611  3e-01   2  1  1 |  0  0
20  -1.270e-03  -1.270e-03  +4e-08  5e-12  7e-13  8e-12  2e-10  0.7912  2e-01   1  1  1 |  0  0
21  -1.270e-03  -1.270e-03  +1e-08  2e-12  3e-13  3e-12  7e-11  0.9161  3e-01   1  1  1 |  0  0
22  -1.270e-03  -1.270e-03  +2e-09  2e-13  2e-13  4e-13  8e-12  0.9890  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=2.2e-13, reltol=1.3e-06, abstol=1.7e-09).
Runtime: 0.010521 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.607e+00  -1.069e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.506e+00  -4.147e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3391  4e-01   1  1  1 |  0  0
 2  +9.727e-01  -2.188e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9455  1e-01   1  1  1 |  0  0
 3  +4.686e-01  -1.560e+00  +5e+01  1e-02  7e-04  4e-01  3e-01  0.4429  2e-01   1  2  1 |  0  0
 4  +1.675e-01  -6.947e-01  +2e+01  4e-03  3e-04  2e-01  1e-01  0.5943  7e-02   1  1  2 |  0  0
 5  +3.128e-02  -4.954e-01  +1e+01  2e-03  1e-04  3e-02  7e-02  0.8292  5e-01   1  2  2 |  0  0
 6  +7.707e-03  -2.302e-01  +6e+00  9e-04  6e-05  9e-03  3e-02  0.7564  3e-01   1  1  1 |  0  0
 7  +7.133e-03  -7.851e-02  +2e+00  3e-04  2e-05  9e-04  1e-02  0.9560  3e-01   1  1  1 |  0  0
 8  +3.337e-03  -2.564e-02  +8e-01  1e-04  6e-06  2e-04  4e-03  0.9086  3e-01   1  1  1 |  0  0
 9  +8.116e-04  -9.957e-03  +3e-01  4e-05  2e-06  7e-05  1e-03  0.7705  2e-01   1  1  1 |  0  0
10  +3.927e-04  -3.733e-03  +1e-01  1e-05  9e-07  2e-05  5e-04  0.9890  4e-01   1  1  1 |  0  0
11  -2.746e-04  -1.039e-03  +2e-02  3e-06  2e-07  4e-06  1e-04  0.8828  8e-02   1  1  1 |  0  0
12  -3.819e-04  -5.549e-04  +5e-03  6e-07  4e-08  1e-06  2e-05  0.9419  2e-01   1  1  1 |  0  0
13  -4.014e-04  -4.600e-04  +2e-03  2e-07  1e-08  3e-07  7e-06  0.8331  2e-01   1  1  1 |  0  0
14  -4.107e-04  -4.197e-04  +2e-04  3e-08  2e-09  5e-08  1e-06  0.9010  6e-02   2  1  1 |  0  0
15  -4.121e-04  -4.132e-04  +3e-05  4e-09  3e-10  7e-09  2e-07  0.9384  7e-02   2  1  1 |  0  0
16  -4.122e-04  -4.125e-04  +8e-06  1e-09  7e-11  2e-09  4e-08  0.8262  1e-01   2  1  1 |  0  0
17  -4.122e-04  -4.124e-04  +4e-06  5e-10  4e-11  9e-10  2e-08  0.6812  3e-01   2  1  1 |  0  0
18  -4.123e-04  -4.123e-04  +2e-06  2e-10  2e-11  4e-10  9e-09  0.8566  3e-01   1  1  1 |  0  0
19  -4.123e-04  -4.123e-04  +4e-07  5e-11  3e-12  8e-11  2e-09  0.9890  2e-01   1  1  1 |  0  0
20  -4.123e-04  -4.123e-04  +4e-08  5e-12  8e-13  8e-12  2e-10  0.9196  2e-02   2  1  1 |  0  0
21  -4.123e-04  -4.123e-04  +8e-09  1e-12  3e-13  2e-12  4e-11  0.9890  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.0e-12, reltol=1.9e-05, abstol=7.8e-09).
Runtime: 0.009809 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.614e+00  -1.072e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.502e+00  -4.155e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3400  4e-01   1  1  1 |  0  0
 2  +9.553e-01  -2.198e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9463  1e-01   1  1  1 |  0  0
 3  +4.745e-01  -1.647e+00  +5e+01  1e-02  8e-04  5e-01  3e-01  0.4225  3e-01   1  2  1 |  0  0
 4  +1.671e-01  -6.979e-01  +2e+01  4e-03  3e-04  2e-01  1e-01  0.6037  6e-02   1  1  2 |  0  0
 5  +3.202e-02  -5.039e-01  +1e+01  2e-03  1e-04  4e-02  7e-02  0.8232  5e-01   1  2  2 |  0  0
 6  +7.723e-03  -2.288e-01  +6e+00  9e-04  6e-05  9e-03  3e-02  0.7620  3e-01   1  1  1 |  0  0
 7  +6.975e-03  -7.743e-02  +2e+00  3e-04  2e-05  9e-04  1e-02  0.9547  3e-01   1  1  1 |  0  0
 8  +3.518e-03  -2.615e-02  +8e-01  1e-04  7e-06  2e-04  4e-03  0.8800  3e-01   1  1  1 |  0  0
 9  +9.638e-04  -9.864e-03  +3e-01  4e-05  2e-06  7e-05  1e-03  0.7785  2e-01   1  1  1 |  0  0
10  +6.133e-04  -3.875e-03  +1e-01  2e-05  1e-06  3e-05  6e-04  0.9545  4e-01   1  1  1 |  0  0
11  -9.947e-05  -8.655e-04  +2e-02  3e-06  2e-07  4e-06  1e-04  0.9268  1e-01   1  1  1 |  0  0
12  -1.907e-04  -3.879e-04  +5e-03  7e-07  4e-08  1e-06  3e-05  0.9890  2e-01   1  1  1 |  0  0
13  -2.212e-04  -2.455e-04  +6e-04  8e-08  5e-09  1e-07  3e-06  0.8918  2e-02   2  1  1 |  0  0
14  -2.242e-04  -2.317e-04  +2e-04  3e-08  2e-09  4e-08  1e-06  0.8063  1e-01   1  1  1 |  0  0
15  -2.252e-04  -2.272e-04  +5e-05  7e-09  5e-10  1e-08  3e-07  0.8453  1e-01   2  1  1 |  0  0
16  -2.254e-04  -2.260e-04  +1e-05  2e-09  1e-10  3e-09  7e-08  0.9338  2e-01   2  1  1 |  0  0
17  -2.255e-04  -2.256e-04  +2e-06  3e-10  2e-11  5e-10  1e-08  0.8818  6e-02   2  1  1 |  0  0
18  -2.255e-04  -2.256e-04  +7e-07  9e-11  7e-12  2e-10  4e-09  0.9890  3e-01   2  1  1 |  0  0
19  -2.255e-04  -2.255e-04  +2e-07  2e-11  2e-12  4e-11  9e-10  0.8153  8e-02   2  1  1 |  0  0
20  -2.255e-04  -2.255e-04  +6e-08  8e-12  9e-13  1e-11  3e-10  0.8624  2e-01   2  1  1 |  0  0
21  -2.255e-04  -2.255e-04  +1e-08  2e-12  2e-13  3e-12  6e-11  0.9629  2e-01   2  1  1 |  0  0
22  -2.255e-04  -2.255e-04  +1e-09  4e-13  2e-13  3e-13  7e-12  0.9650  9e-02   2  1  1 |  0  0

OPTIMAL (within feastol=4.2e-13, reltol=6.4e-06, abstol=1.4e-09).
Runtime: 0.010204 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.621e+00  -1.074e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.497e+00  -4.171e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3402  4e-01   1  1  1 |  0  0
 2  +9.439e-01  -2.209e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9470  1e-01   1  1  1 |  0  0
 3  +4.616e-01  -1.688e+00  +5e+01  1e-02  8e-04  5e-01  3e-01  0.4252  3e-01   1  1  1 |  0  0
 4  +1.611e-01  -6.972e-01  +2e+01  4e-03  3e-04  2e-01  1e-01  0.6102  5e-02   1  1  2 |  0  0
 5  +2.969e-02  -4.937e-01  +1e+01  2e-03  1e-04  3e-02  7e-02  0.8334  5e-01   1  2  2 |  0  0
 6  +7.085e-03  -2.201e-01  +6e+00  8e-04  5e-05  8e-03  3e-02  0.7676  3e-01   1  1  1 |  0  0
 7  +6.544e-03  -7.294e-02  +2e+00  3e-04  2e-05  8e-04  1e-02  0.9553  3e-01   1  1  1 |  0  0
 8  +3.297e-03  -2.437e-02  +7e-01  1e-04  6e-06  2e-04  4e-03  0.8832  3e-01   1  1  1 |  0  0
 9  +8.330e-04  -9.179e-03  +3e-01  3e-05  2e-06  7e-05  1e-03  0.7807  2e-01   1  1  1 |  0  0
10  +5.338e-04  -3.815e-03  +1e-01  1e-05  1e-06  3e-05  6e-04  0.9206  4e-01   1  1  1 |  0  0
11  -1.414e-04  -8.279e-04  +2e-02  2e-06  2e-07  4e-06  9e-05  0.9361  1e-01   1  1  1 |  0  0
12  -2.143e-04  -4.233e-04  +5e-03  7e-07  5e-08  1e-06  3e-05  0.8935  2e-01   1  1  1 |  0  0
13  -2.399e-04  -3.049e-04  +2e-03  2e-07  1e-08  4e-07  8e-06  0.7752  1e-01   1  1  1 |  0  0
14  -2.452e-04  -2.764e-04  +8e-04  1e-07  7e-09  2e-07  4e-06  0.8220  4e-01   2  1  1 |  0  0
15  -2.504e-04  -2.539e-04  +9e-05  1e-08  8e-10  2e-08  4e-07  0.9578  7e-02   1  1  1 |  0  0
16  -2.509e-04  -2.518e-04  +2e-05  3e-09  2e-10  5e-09  1e-07  0.8519  1e-01   1  1  1 |  0  0
17  -2.510e-04  -2.514e-04  +1e-05  1e-09  9e-11  2e-09  5e-08  0.7367  2e-01   1  1  1 |  0  0
18  -2.510e-04  -2.511e-04  +4e-06  5e-10  3e-11  8e-10  2e-08  0.9088  3e-01   2  1  1 |  0  0
19  -2.510e-04  -2.511e-04  +6e-07  8e-11  5e-12  1e-10  3e-09  0.9890  2e-01   1  1  1 |  0  0
20  -2.510e-04  -2.510e-04  +6e-08  8e-12  1e-12  1e-11  3e-10  0.9078  2e-02   1  1  1 |  0  0
21  -2.510e-04  -2.510e-04  +1e-08  2e-12  4e-13  3e-12  7e-11  0.9890  2e-01   2  1  1 |  0  0
22  -2.510e-04  -2.510e-04  +3e-09  4e-13  1e-13  6e-13  1e-11  0.8561  5e-02   2  1  1 |  0  0

OPTIMAL (within feastol=3.8e-13, reltol=1.1e-05, abstol=2.7e-09).
Runtime: 0.010059 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.630e+00  -1.077e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.507e+00  -4.186e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3404  4e-01   1  1  1 |  0  0
 2  +9.359e-01  -2.224e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9474  1e-01   1  1  1 |  0  0
 3  +4.193e-01  -1.692e+00  +5e+01  1e-02  7e-04  4e-01  3e-01  0.4601  3e-01   1  1  1 |  0  0
 4  +1.460e-01  -6.904e-01  +2e+01  4e-03  3e-04  2e-01  1e-01  0.6170  6e-02   1  1  2 |  0  0
 5  +2.483e-02  -4.579e-01  +1e+01  2e-03  1e-04  3e-02  6e-02  0.8572  4e-01   1  2  2 |  0  0
 6  +5.980e-03  -2.059e-01  +5e+00  8e-04  5e-05  7e-03  3e-02  0.7684  3e-01   1  1  1 |  0  0
 7  +5.961e-03  -6.533e-02  +2e+00  3e-04  2e-05  7e-04  9e-03  0.9619  3e-01   1  1  1 |  0  0
 8  +2.834e-03  -2.067e-02  +6e-01  8e-05  5e-06  2e-04  3e-03  0.9208  3e-01   1  1  2 |  0  0
 9  +5.795e-04  -7.883e-03  +2e-01  3e-05  2e-06  5e-05  1e-03  0.7703  2e-01   1  1  1 |  0  0
10  +2.942e-04  -3.267e-03  +9e-02  1e-05  8e-07  2e-05  5e-04  0.9194  4e-01   1  1  1 |  0  0
11  -2.676e-04  -7.968e-04  +1e-02  2e-06  1e-07  3e-06  7e-05  0.9277  8e-02   1  1  1 |  0  0
12  -3.127e-04  -5.415e-04  +6e-03  8e-07  5e-08  1e-06  3e-05  0.7112  2e-01   1  1  1 |  0  0
13  -3.370e-04  -4.256e-04  +2e-03  3e-07  2e-08  5e-07  1e-05  0.7456  2e-01   1  1  1 |  0  0
14  -3.446e-04  -3.836e-04  +1e-03  1e-07  9e-09  2e-07  5e-06  0.8794  4e-01   2  1  1 |  0  0
15  -3.510e-04  -3.564e-04  +1e-04  2e-08  1e-09  3e-08  7e-07  0.9251  7e-02   2  1  1 |  0  0
16  -3.517e-04  -3.534e-04  +4e-05  6e-09  4e-10  1e-08  2e-07  0.7817  1e-01   2  1  1 |  0  0
17  -3.519e-04  -3.525e-04  +2e-05  2e-09  1e-10  3e-09  7e-08  0.8276  2e-01   1  1  1 |  0  0
18  -3.520e-04  -3.521e-04  +4e-06  5e-10  3e-11  9e-10  2e-08  0.9490  2e-01   2  1  1 |  0  0
19  -3.520e-04  -3.520e-04  +4e-07  6e-11  4e-12  1e-10  2e-09  0.9857  1e-01   1  1  1 |  0  0
20  -3.520e-04  -3.520e-04  +7e-08  1e-11  1e-12  2e-11  4e-10  0.8651  4e-02   3  1  1 |  0  0
21  -3.520e-04  -3.520e-04  +3e-08  3e-12  5e-13  5e-12  1e-10  0.9248  3e-01   2  1  1 |  0  0
22  -3.520e-04  -3.520e-04  +7e-09  9e-13  2e-13  1e-12  3e-11  0.8409  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=8.8e-13, reltol=1.9e-05, abstol=6.7e-09).
Runtime: 0.010160 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.643e+00  -1.081e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.545e+00  -4.195e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3410  4e-01   1  1  1 |  0  0
 2  +9.338e-01  -2.244e+00  +7e+01  2e-02  1e-03  8e-01  4e-01  0.9470  1e-01   1  1  1 |  0  0
 3  +2.974e-01  -1.597e+00  +5e+01  9e-03  6e-04  3e-01  3e-01  0.5836  3e-01   1  1  1 |  0  0
 4  +1.008e-01  -6.470e-01  +2e+01  3e-03  2e-04  1e-01  1e-01  0.6485  9e-02   1  2  2 |  0  0
 5  +1.779e-02  -3.665e-01  +1e+01  1e-03  9e-05  2e-02  5e-02  0.8916  4e-01   1  2  2 |  0  0
 6  +4.117e-03  -1.837e-01  +5e+00  7e-04  4e-05  5e-03  2e-02  0.7454  3e-01   1  1  1 |  0  0
 7  +4.889e-03  -5.784e-02  +2e+00  2e-04  1e-05  6e-04  8e-03  0.9471  3e-01   1  1  2 |  0  0
 8  +2.330e-03  -1.815e-02  +5e-01  7e-05  4e-06  1e-04  3e-03  0.9890  3e-01   1  1  1 |  0  0
 9  +1.335e-04  -5.277e-03  +1e-01  2e-05  1e-06  3e-05  7e-04  0.8231  1e-01   1  1  1 |  0  0
10  -2.565e-04  -1.733e-03  +4e-02  5e-06  3e-07  8e-06  2e-04  0.9416  2e-01   1  1  1 |  0  0
11  -4.717e-04  -8.251e-04  +9e-03  1e-06  8e-08  2e-06  5e-05  0.8251  8e-02   1  1  1 |  0  0
12  -5.116e-04  -6.291e-04  +3e-03  4e-07  3e-08  7e-07  1e-05  0.8296  2e-01   2  1  1 |  0  0
13  -5.293e-04  -5.532e-04  +6e-04  8e-08  5e-09  1e-07  3e-06  0.9127  1e-01   2  1  1 |  0  0
14  -5.328e-04  -5.361e-04  +8e-05  1e-08  7e-10  2e-08  4e-07  0.9496  9e-02   2  1  1 |  0  0
15  -5.333e-04  -5.341e-04  +2e-05  3e-09  2e-10  4e-09  1e-07  0.8108  6e-02   2  1  1 |  0  0
16  -5.334e-04  -5.337e-04  +9e-06  1e-09  7e-11  2e-09  4e-08  0.7257  2e-01   2  1  1 |  0  0
17  -5.334e-04  -5.335e-04  +3e-06  4e-10  3e-11  7e-10  2e-08  0.8768  3e-01   2  1  1 |  0  0
18  -5.334e-04  -5.334e-04  +7e-07  9e-11  6e-12  1e-10  3e-09  0.9890  2e-01   1  1  1 |  0  0
19  -5.334e-04  -5.334e-04  +7e-08  9e-12  7e-13  1e-11  3e-10  0.9212  3e-02   2  1  1 |  0  0
20  -5.334e-04  -5.334e-04  +1e-08  2e-12  3e-13  3e-12  7e-11  0.9890  2e-01   2  1  1 |  0  0
21  -5.334e-04  -5.334e-04  +5e-09  7e-13  2e-13  1e-12  3e-11  0.7326  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=7.1e-13, reltol=1.0e-05, abstol=5.4e-09).
Runtime: 0.009784 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.052e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.796e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.052e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.036e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.056e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.713e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.084e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.934e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 9.468e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.934e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.028e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.032e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.897e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.032e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.040e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 6.465e-05
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.092e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.076e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.166e-05
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.076e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.086e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.061e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.617e-06
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.061e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.079e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.010e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.697e+00  -1.102e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.034e+00  -4.091e+01  +5e+02  2e-01  1e-02  2e+00  2e+00  0.3502  4e-01   1  1  1 |  0  0
 2  +1.053e+00  -2.997e+00  +9e+01  2e-02  1e-03  6e-01  5e-01  0.9012  1e-01   1  1  1 |  0  0
 3  +1.674e-01  -1.360e+00  +4e+01  7e-03  4e-04  1e-01  2e-01  0.8107  3e-01   1  1  1 |  0  0
 4  +5.701e-02  -8.491e-01  +2e+01  4e-03  2e-04  4e-02  1e-01  0.7636  5e-01   1  2  2 |  0  0
 5  +1.457e-02  -2.342e-01  +6e+00  9e-04  5e-05  6e-03  3e-02  0.8520  2e-01   1  2  2 |  0  0
 6  +8.503e-03  -1.525e-01  +4e+00  6e-04  3e-05  3e-03  2e-02  0.6075  4e-01   1  2  2 |  0  0
 7  +8.560e-03  -1.103e-01  +3e+00  4e-04  2e-05  2e-03  2e-02  0.5720  5e-01   1  2  2 |  0  0
 8  +1.894e-03  -4.217e-02  +1e+00  2e-04  8e-06  5e-04  6e-03  0.6823  8e-02   1  2  2 |  0  0
 9  -3.917e-04  -1.425e-02  +4e-01  5e-05  3e-06  1e-04  2e-03  0.8393  2e-01   1  2  2 |  0  0
10  -1.170e-03  -5.912e-03  +1e-01  2e-05  9e-07  4e-05  6e-04  0.8034  2e-01   1  1  2 |  0  0
11  -1.697e-03  -2.521e-03  +2e-02  3e-06  2e-07  6e-06  1e-04  0.8764  6e-02   1  1  1 |  0  0
12  -1.771e-03  -1.939e-03  +4e-03  6e-07  3e-08  1e-06  2e-05  0.8476  6e-02   1  1  1 |  0  0
13  -1.785e-03  -1.851e-03  +2e-03  2e-07  1e-08  4e-07  8e-06  0.9890  4e-01   2  1  1 |  0  0
14  -1.794e-03  -1.803e-03  +2e-04  3e-08  2e-09  5e-08  1e-06  0.8878  2e-02   2  1  1 |  0  0
15  -1.795e-03  -1.798e-03  +6e-05  8e-09  5e-10  1e-08  3e-07  0.8357  2e-01   2  1  1 |  0  0
16  -1.796e-03  -1.797e-03  +3e-05  4e-09  2e-10  6e-09  1e-07  0.7535  2e-01   1  1  1 |  0  0
17  -1.796e-03  -1.796e-03  +5e-06  7e-10  4e-11  1e-09  3e-08  0.9123  1e-01   2  1  1 |  0  0
18  -1.796e-03  -1.796e-03  +1e-06  1e-10  8e-12  2e-10  5e-09  0.8649  6e-02   2  1  1 |  0  0
19  -1.796e-03  -1.796e-03  +4e-07  5e-11  3e-12  9e-11  2e-09  0.9890  4e-01   1  1  1 |  0  0
20  -1.796e-03  -1.796e-03  +6e-08  8e-12  8e-13  1e-11  3e-10  0.8680  2e-02   3  1  1 |  0  0
21  -1.796e-03  -1.796e-03  +2e-08  3e-12  4e-13  4e-12  9e-11  0.9890  3e-01   2  1  1 |  0  0
22  -1.796e-03  -1.796e-03  +5e-09  6e-13  1e-13  1e-12  2e-11  0.8147  7e-02   2  1  1 |  0  0

OPTIMAL (within feastol=6.2e-13, reltol=2.5e-06, abstol=4.6e-09).
Runtime: 0.010330 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.716e+00  -1.111e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.360e+00  -3.983e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3572  4e-01   1  1  1 |  0  0
 2  +1.141e+00  -3.613e+00  +1e+02  2e-02  1e-03  6e-01  5e-01  0.8646  1e-01   1  1  1 |  0  0
 3  +1.522e-01  -1.282e+00  +3e+01  6e-03  3e-04  1e-01  2e-01  0.8344  2e-01   1  2  1 |  0  0
 4  +6.371e-02  -8.689e-01  +2e+01  4e-03  2e-04  3e-02  1e-01  0.7079  5e-01   1  2  2 |  0  0
 5  +1.965e-02  -2.352e-01  +6e+00  9e-04  4e-05  6e-03  3e-02  0.8329  1e-01   1  2  2 |  0  0
 6  +9.713e-03  -1.485e-01  +4e+00  6e-04  3e-05  3e-03  2e-02  0.4898  2e-01   1  2  2 |  0  0
 7  +1.123e-02  -1.301e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.3283  7e-01   1  2  2 |  0  0
 8  +3.279e-03  -5.754e-02  +2e+00  2e-04  1e-05  9e-04  8e-03  0.6853  2e-01   1  2  2 |  0  0
 9  -8.729e-05  -1.648e-02  +4e-01  6e-05  3e-06  2e-04  2e-03  0.8454  1e-01   1  2  2 |  0  0
10  -8.678e-04  -6.944e-03  +2e-01  2e-05  1e-06  5e-05  8e-04  0.8271  2e-01   1  2  2 |  0  0
11  -1.439e-03  -3.666e-03  +6e-02  7e-06  4e-07  2e-05  3e-04  0.7965  2e-01   1  1  2 |  0  0
12  -1.635e-03  -2.125e-03  +1e-02  2e-06  8e-08  3e-06  6e-05  0.9096  1e-01   1  1  1 |  0  0
13  -1.703e-03  -1.778e-03  +2e-03  2e-07  1e-08  5e-07  9e-06  0.8672  2e-02   2  1  1 |  0  0
14  -1.710e-03  -1.725e-03  +4e-04  5e-08  2e-09  9e-08  2e-06  0.9098  1e-01   2  1  1 |  0  0
15  -1.712e-03  -1.715e-03  +7e-05  8e-09  4e-10  2e-08  3e-07  0.8842  6e-02   1  1  1 |  0  0
16  -1.713e-03  -1.714e-03  +2e-05  3e-09  2e-10  5e-09  1e-07  0.8738  3e-01   2  1  1 |  0  0
17  -1.713e-03  -1.713e-03  +7e-06  9e-10  5e-11  2e-09  4e-08  0.8304  2e-01   2  1  1 |  0  0
18  -1.713e-03  -1.713e-03  +2e-06  3e-10  1e-11  4e-10  1e-08  0.9453  2e-01   2  1  1 |  0  0
19  -1.713e-03  -1.713e-03  +3e-07  3e-11  2e-12  6e-11  1e-09  0.9068  5e-02   2  1  1 |  0  0
20  -1.713e-03  -1.713e-03  +8e-08  1e-11  9e-13  2e-11  4e-10  0.9278  2e-01   2  1  1 |  0  0
21  -1.713e-03  -1.713e-03  +3e-08  4e-12  3e-13  6e-12  1e-10  0.7649  2e-01   2  1  1 |  0  0
22  -1.713e-03  -1.713e-03  +1e-08  5e-12  3e-13  3e-12  5e-11  0.9073  3e-01   2  1  1 |  0  0
23  -1.713e-03  -1.713e-03  +1e-09  7e-13  5e-14  3e-13  7e-12  0.9890  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=7.2e-13, reltol=8.7e-07, abstol=1.5e-09).
Runtime: 0.010804 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.728e+00  -1.119e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.651e+00  -3.871e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3645  3e-01   1  1  1 |  0  0
 2  +1.202e+00  -4.092e+00  +1e+02  2e-02  1e-03  5e-01  6e-01  0.8361  1e-01   1  1  1 |  0  0
 3  +1.494e-01  -1.183e+00  +3e+01  5e-03  3e-04  8e-02  2e-01  0.8492  2e-01   1  2  1 |  0  0
 4  +7.062e-02  -8.756e-01  +2e+01  4e-03  2e-04  3e-02  1e-01  0.6383  5e-01   2  2  2 |  0  0
 5  +2.261e-02  -2.563e-01  +7e+00  1e-03  4e-05  7e-03  3e-02  0.8095  1e-01   1  2  2 |  0  0
 6  +1.067e-02  -1.489e-01  +4e+00  6e-04  2e-05  4e-03  2e-02  0.5052  2e-01   1  2  2 |  0  0
 7  +1.181e-02  -1.330e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2872  7e-01   1  2  2 |  0  0
 8  +3.820e-03  -5.678e-02  +2e+00  2e-04  9e-06  9e-04  8e-03  0.7042  2e-01   1  2  2 |  0  0
 9  +3.698e-04  -1.135e-02  +3e-01  4e-05  2e-06  1e-04  1e-03  0.8904  9e-02   1  2  2 |  0  0
10  -1.418e-04  -6.048e-03  +2e-01  2e-05  9e-07  5e-05  7e-04  0.7563  3e-01   1  2  1 |  0  0
11  -5.987e-04  -3.411e-03  +7e-02  9e-06  4e-07  2e-05  4e-04  0.6842  2e-01   1  2  2 |  0  0
12  -7.986e-04  -1.752e-03  +2e-02  3e-06  1e-07  6e-06  1e-04  0.9040  3e-01   1  1  1 |  0  0
13  -9.146e-04  -1.160e-03  +6e-03  8e-07  4e-08  2e-06  3e-05  0.8015  7e-02   1  1  1 |  0  0
14  -9.395e-04  -9.881e-04  +1e-03  2e-07  7e-09  3e-07  6e-06  0.9104  1e-01   1  1  1 |  0  0
15  -9.459e-04  -9.527e-04  +2e-04  2e-08  1e-09  4e-08  8e-07  0.8738  1e-02   1  1  1 |  0  0
16  -9.467e-04  -9.478e-04  +3e-05  4e-09  2e-10  7e-09  1e-07  0.9113  9e-02   1  1  1 |  0  0
17  -9.468e-04  -9.470e-04  +6e-06  8e-10  4e-11  1e-09  3e-08  0.8805  1e-01   2  1  1 |  0  0
18  -9.468e-04  -9.469e-04  +2e-06  3e-10  1e-11  6e-10  1e-08  0.9488  3e-01   2  1  1 |  0  0
19  -9.468e-04  -9.468e-04  +6e-07  8e-11  4e-12  1e-10  3e-09  0.8626  1e-01   1  1  1 |  0  0
20  -9.468e-04  -9.468e-04  +2e-07  2e-11  1e-12  4e-11  8e-10  0.9428  2e-01   2  1  1 |  0  0
21  -9.468e-04  -9.468e-04  +2e-08  3e-12  4e-13  5e-12  1e-10  0.8907  4e-02   2  1  1 |  0  0
22  -9.468e-04  -9.468e-04  +7e-09  8e-13  2e-13  1e-12  3e-11  0.9890  3e-01   2  1  1 |  0  0

OPTIMAL (within feastol=8.4e-13, reltol=6.9e-06, abstol=6.5e-09).
Runtime: 0.010251 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.732e+00  -1.125e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.828e+00  -3.790e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3701  3e-01   1  1  1 |  0  0
 2  +1.226e+00  -4.369e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8195  1e-01   1  1  1 |  0  0
 3  +1.522e-01  -1.120e+00  +3e+01  5e-03  2e-04  7e-02  2e-01  0.8549  1e-01   1  2  2 |  0  0
 4  +7.541e-02  -8.570e-01  +2e+01  4e-03  2e-04  3e-02  1e-01  0.6019  6e-01   2  2  2 |  0  0
 5  +2.309e-02  -2.664e-01  +7e+00  1e-03  4e-05  7e-03  4e-02  0.7900  1e-01   1  2  2 |  0  0
 6  +1.152e-02  -1.532e-01  +4e+00  6e-04  2e-05  4e-03  2e-02  0.5006  1e-01   1  2  2 |  0  0
 7  +1.252e-02  -1.390e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2540  7e-01   1  2  2 |  0  0
 8  +4.149e-03  -5.477e-02  +1e+00  2e-04  8e-06  9e-04  7e-03  0.7475  2e-01   1  2  2 |  0  0
 9  +1.613e-03  -1.438e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8744  2e-01   1  2  2 |  0  0
10  +3.296e-04  -5.555e-03  +1e-01  2e-05  8e-07  5e-05  7e-04  0.7247  1e-01   1  2  2 |  0  0
11  +1.051e-04  -2.555e-03  +7e-02  9e-06  4e-07  2e-05  3e-04  0.8573  4e-01   1  2  2 |  0  0
12  -2.014e-04  -8.957e-04  +2e-02  2e-06  1e-07  5e-06  9e-05  0.8320  1e-01   1  1  2 |  0  0
13  -2.657e-04  -4.253e-04  +4e-03  5e-07  2e-08  1e-06  2e-05  0.8845  1e-01   1  1  1 |  0  0
14  -2.858e-04  -3.156e-04  +8e-04  1e-07  4e-09  2e-07  4e-06  0.8368  3e-02   2  1  1 |  0  0
15  -2.887e-04  -2.952e-04  +2e-04  2e-08  9e-10  4e-08  8e-07  0.8912  1e-01   2  1  1 |  0  0
16  -2.896e-04  -2.906e-04  +3e-05  3e-09  1e-10  6e-09  1e-07  0.8641  3e-02   2  1  1 |  0  0
17  -2.897e-04  -2.899e-04  +6e-06  7e-10  3e-11  1e-09  3e-08  0.8816  1e-01   2  1  1 |  0  0
18  -2.897e-04  -2.898e-04  +1e-06  2e-10  7e-12  3e-10  6e-09  0.8670  9e-02   2  1  1 |  0  0
19  -2.897e-04  -2.897e-04  +5e-07  6e-11  3e-12  1e-10  2e-09  0.9306  4e-01   1  1  1 |  0  0
20  -2.897e-04  -2.897e-04  +1e-07  2e-11  1e-12  2e-11  5e-10  0.8346  6e-02   2  1  1 |  0  0
21  -2.897e-04  -2.897e-04  +3e-08  6e-12  4e-13  7e-12  2e-10  0.8545  2e-01   1  1  1 |  0  0
22  -2.897e-04  -2.897e-04  +7e-09  1e-12  2e-13  2e-12  4e-11  0.8078  4e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=2.5e-05, abstol=7.4e-09).
Runtime: 0.010369 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.731e+00  -1.127e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.912e+00  -3.745e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3733  3e-01   1  1  1 |  0  0
 2  +1.234e+00  -4.501e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8115  1e-01   1  1  1 |  0  0
 3  +1.591e-01  -1.103e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8526  1e-01   1  2  2 |  0  0
 4  +7.475e-02  -8.212e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6130  5e-01   2  2  2 |  0  0
 5  +2.249e-02  -2.468e-01  +7e+00  1e-03  4e-05  7e-03  3e-02  0.7832  1e-01   1  2  2 |  0  0
 6  +1.204e-02  -1.497e-01  +4e+00  6e-04  2e-05  4e-03  2e-02  0.4843  2e-01   1  2  2 |  0  0
 7  +1.285e-02  -1.358e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2547  7e-01   1  2  2 |  0  0
 8  +4.286e-03  -5.262e-02  +1e+00  2e-04  8e-06  8e-04  7e-03  0.7626  2e-01   1  2  2 |  0  0
 9  +1.891e-03  -1.421e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8748  2e-01   1  2  2 |  0  0
10  +5.009e-04  -4.822e-03  +1e-01  2e-05  7e-07  5e-05  7e-04  0.7588  1e-01   1  2  2 |  0  0
11  +2.868e-04  -2.107e-03  +6e-02  8e-06  3e-07  2e-05  3e-04  0.8346  3e-01   1  2  2 |  0  0
12  +6.860e-06  -5.547e-04  +1e-02  2e-06  7e-08  4e-06  7e-05  0.8360  8e-02   1  1  2 |  0  0
13  -3.930e-05  -2.077e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.8361  2e-01   1  1  1 |  0  0
14  -6.058e-05  -9.148e-05  +8e-04  1e-07  4e-09  2e-07  4e-06  0.8309  2e-02   2  1  1 |  0  0
15  -6.340e-05  -7.166e-05  +2e-04  3e-08  1e-09  5e-08  1e-06  0.8713  2e-01   2  1  1 |  0  0
16  -6.443e-05  -6.606e-05  +4e-05  5e-09  2e-10  1e-08  2e-07  0.8147  2e-02   2  1  1 |  0  0
17  -6.458e-05  -6.505e-05  +1e-05  2e-09  6e-11  3e-09  6e-08  0.8560  2e-01   2  1  1 |  0  0
18  -6.464e-05  -6.474e-05  +3e-06  3e-10  1e-11  6e-10  1e-08  0.8100  3e-02   2  1  1 |  0  0
19  -6.465e-05  -6.468e-05  +8e-07  1e-10  4e-12  2e-10  4e-09  0.8361  2e-01   1  1  1 |  0  0
20  -6.465e-05  -6.466e-05  +2e-07  2e-11  1e-12  4e-11  9e-10  0.8130  6e-02   2  1  1 |  0  0
21  -6.465e-05  -6.466e-05  +6e-08  7e-12  4e-13  1e-11  3e-10  0.8491  2e-01   2  1  1 |  0  0
22  -6.465e-05  -6.465e-05  +1e-08  2e-12  3e-13  3e-12  6e-11  0.8269  7e-02   1  1  1 |  0  0
23  -6.465e-05  -6.465e-05  +3e-09  4e-13  9e-14  8e-13  2e-11  0.8670  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=4.4e-13, reltol=5.3e-05, abstol=3.4e-09).
Runtime: 0.010880 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.730e+00  -1.128e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.947e+00  -3.723e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3749  3e-01   1  1  1 |  0  0
 2  +1.236e+00  -4.559e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8079  1e-01   1  1  1 |  0  0
 3  +1.622e-01  -1.097e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8514  1e-01   1  2  2 |  0  0
 4  +7.391e-02  -8.064e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6194  5e-01   2  2  2 |  0  0
 5  +2.184e-02  -2.391e-01  +7e+00  9e-04  4e-05  6e-03  3e-02  0.7821  1e-01   1  2  2 |  0  0
 6  +1.214e-02  -1.483e-01  +4e+00  6e-04  2e-05  4e-03  2e-02  0.4788  2e-01   1  2  2 |  0  0
 7  +1.287e-02  -1.345e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2564  7e-01   1  2  2 |  0  0
 8  +4.235e-03  -5.130e-02  +1e+00  2e-04  7e-06  8e-04  7e-03  0.7723  2e-01   1  2  2 |  0  0
 9  +1.997e-03  -1.440e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8738  2e-01   1  2  2 |  0  0
10  +5.276e-04  -4.533e-03  +1e-01  2e-05  7e-07  4e-05  6e-04  0.7788  1e-01   1  2  2 |  0  0
11  +3.112e-04  -1.902e-03  +6e-02  7e-06  3e-07  2e-05  3e-04  0.8284  3e-01   1  2  2 |  0  0
12  +5.174e-05  -4.436e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8298  6e-02   1  1  2 |  0  0
13  +1.384e-05  -1.547e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.8087  2e-01   1  1  1 |  0  0
14  -6.967e-06  -4.148e-05  +9e-04  1e-07  5e-09  2e-07  4e-06  0.8118  2e-02   1  1  1 |  0  0
15  -9.930e-06  -2.115e-05  +3e-04  4e-08  1e-09  7e-08  1e-06  0.8267  2e-01   2  1  1 |  0  0
16  -1.129e-05  -1.387e-05  +7e-05  8e-09  3e-10  2e-08  3e-07  0.7906  3e-02   2  1  1 |  0  0
17  -1.154e-05  -1.233e-05  +2e-05  3e-09  1e-10  5e-09  1e-07  0.8439  2e-01   2  1  1 |  0  0
18  -1.164e-05  -1.182e-05  +5e-06  6e-10  2e-11  1e-09  2e-08  0.7897  3e-02   1  1  1 |  0  0
19  -1.165e-05  -1.171e-05  +1e-06  2e-10  7e-12  3e-10  7e-09  0.8391  2e-01   2  1  1 |  0  0
20  -1.166e-05  -1.167e-05  +3e-07  4e-11  2e-12  8e-11  2e-09  0.8035  5e-02   1  1  1 |  0  0
21  -1.166e-05  -1.167e-05  +1e-07  1e-11  6e-13  2e-11  5e-10  0.8447  2e-01   1  1  1 |  0  0
22  -1.166e-05  -1.166e-05  +2e-08  3e-12  4e-13  5e-12  1e-10  0.8228  7e-02   2  1  1 |  0  0
23  -1.166e-05  -1.166e-05  +6e-09  8e-13  1e-13  1e-12  3e-11  0.8651  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=7.6e-13, reltol=5.1e-04, abstol=5.9e-09).
Runtime: 0.010823 seconds.


(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.053e-07
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.010e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.108e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.989e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.586e-08
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.989e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.079e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.019e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.246e-09
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.019e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.094e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.039e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 4.068e-10
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.039e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.090e-02 seconds
Reranking users:   0%|          | 3/2064 [00:01<16:28,  2.09it/s](CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.035e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 8.703e+00
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.035e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 7.308e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.026e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.267e-01
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.026e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.941e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.109e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.552e-02
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.109e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 9.627e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.087e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.857e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.729e+00  -1.129e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.967e+00  -3.710e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3759  3e-01   1  1  1 |  0  0
 2  +1.237e+00  -4.591e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8059  1e-01   1  1  1 |  0  0
 3  +1.650e-01  -1.097e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8497  1e-01   1  2  2 |  0  0
 4  +7.268e-02  -7.950e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6274  5e-01   2  2  2 |  0  0
 5  +2.118e-02  -2.311e-01  +6e+00  9e-04  3e-05  6e-03  3e-02  0.7835  1e-01   1  2  2 |  0  0
 6  +1.222e-02  -1.465e-01  +4e+00  6e-04  2e-05  3e-03  2e-02  0.4777  2e-01   1  2  2 |  0  0
 7  +1.282e-02  -1.323e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2650  7e-01   1  2  2 |  0  0
 8  +4.163e-03  -4.992e-02  +1e+00  2e-04  7e-06  7e-04  7e-03  0.7727  2e-01   1  2  2 |  0  0
 9  +2.002e-03  -1.432e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8704  2e-01   1  2  2 |  0  0
10  +5.290e-04  -4.441e-03  +1e-01  2e-05  6e-07  4e-05  6e-04  0.7806  1e-01   1  2  2 |  0  0
11  +3.127e-04  -1.847e-03  +5e-02  7e-06  3e-07  1e-05  3e-04  0.8235  3e-01   1  2  2 |  0  0
12  +6.083e-05  -4.170e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8244  6e-02   1  1  2 |  0  0
13  +2.530e-05  -1.442e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.7992  2e-01   1  1  1 |  0  0
14  +4.742e-06  -3.173e-05  +9e-04  1e-07  5e-09  2e-07  5e-06  0.8036  2e-02   2  1  1 |  0  0
15  +1.469e-06  -9.443e-06  +3e-04  4e-08  1e-09  7e-08  1e-06  0.8500  2e-01   2  1  1 |  0  0
16  +1.524e-07  -2.365e-06  +6e-05  8e-09  3e-10  2e-08  3e-07  0.7899  3e-02   2  1  1 |  0  0
17  -8.896e-08  -8.310e-07  +2e-05  2e-09  1e-10  4e-09  9e-08  0.8509  2e-01   2  1  1 |  0  0
18  -1.807e-07  -3.474e-07  +4e-06  5e-10  2e-11  1e-09  2e-08  0.8003  3e-02   2  1  1 |  0  0
19  -1.976e-07  -2.463e-07  +1e-06  2e-10  6e-12  3e-10  6e-09  0.8414  2e-01   2  1  1 |  0  0
20  -2.036e-07  -2.150e-07  +3e-07  4e-11  2e-12  7e-11  1e-09  0.8166  6e-02   1  1  1 |  0  0
21  -2.048e-07  -2.080e-07  +8e-08  1e-11  6e-13  2e-11  4e-10  0.8559  2e-01   2  1  1 |  0  0
22  -2.052e-07  -2.059e-07  +2e-08  2e-12  3e-13  4e-12  9e-11  0.8381  8e-02   2  1  1 |  0  0
23  -2.053e-07  -2.055e-07  +5e-09  6e-13  1e-13  1e-12  2e-11  0.8773  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=5.9e-13, reltol=2.2e-02, abstol=4.6e-09).
Runtime: 0.011051 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.729e+00  -1.129e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.969e+00  -3.708e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3760  3e-01   1  1  1 |  0  0
 2  +1.237e+00  -4.594e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8057  1e-01   1  1  1 |  0  0
 3  +1.653e-01  -1.097e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8495  1e-01   1  2  2 |  0  0
 4  +7.255e-02  -7.939e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6281  5e-01   2  2  2 |  0  0
 5  +2.111e-02  -2.303e-01  +6e+00  9e-04  3e-05  6e-03  3e-02  0.7837  1e-01   1  2  2 |  0  0
 6  +1.222e-02  -1.463e-01  +4e+00  6e-04  2e-05  3e-03  2e-02  0.4778  2e-01   1  2  2 |  0  0
 7  +1.281e-02  -1.320e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2660  7e-01   1  2  2 |  0  0
 8  +4.153e-03  -4.977e-02  +1e+00  2e-04  7e-06  7e-04  7e-03  0.7726  2e-01   1  2  2 |  0  0
 9  +2.005e-03  -1.435e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8696  2e-01   1  2  2 |  0  0
10  +5.289e-04  -4.443e-03  +1e-01  2e-05  6e-07  4e-05  6e-04  0.7806  1e-01   1  2  2 |  0  0
11  +3.124e-04  -1.847e-03  +5e-02  7e-06  3e-07  1e-05  3e-04  0.8228  3e-01   1  2  2 |  0  0
12  +6.105e-05  -4.176e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8230  5e-02   1  1  2 |  0  0
13  +2.566e-05  -1.452e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.7978  2e-01   1  1  1 |  0  0
14  +4.999e-06  -3.208e-05  +9e-04  1e-07  5e-09  2e-07  5e-06  0.8023  2e-02   1  1  1 |  0  0
15  +1.677e-06  -9.426e-06  +3e-04  4e-08  1e-09  7e-08  1e-06  0.8499  2e-01   2  1  1 |  0  0
16  +3.389e-07  -2.229e-06  +7e-05  8e-09  3e-10  2e-08  3e-07  0.7895  3e-02   1  1  1 |  0  0
17  +9.248e-08  -6.629e-07  +2e-05  2e-09  1e-10  5e-09  9e-08  0.8511  2e-01   2  1  1 |  0  0
18  -9.042e-10  -1.705e-07  +4e-06  6e-10  2e-11  1e-09  2e-08  0.8008  3e-02   2  1  1 |  0  0
19  -1.807e-08  -6.744e-08  +1e-06  2e-10  7e-12  3e-10  6e-09  0.8419  2e-01   2  1  1 |  0  0
20  -2.418e-08  -3.571e-08  +3e-07  4e-11  2e-12  7e-11  1e-09  0.8175  6e-02   2  1  1 |  0  0
21  -2.541e-08  -2.858e-08  +8e-08  1e-11  6e-13  2e-11  4e-10  0.8567  2e-01   2  1  1 |  0  0
22  -2.581e-08  -2.653e-08  +2e-08  3e-12  3e-13  4e-12  9e-11  0.8393  8e-02   1  1  1 |  0  0
23  -2.589e-08  -2.607e-08  +5e-09  7e-13  1e-13  1e-12  2e-11  0.8781  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=6.9e-13, reltol=1.8e-01, abstol=4.6e-09).
Runtime: 0.010754 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.729e+00  -1.129e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.970e+00  -3.708e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3760  3e-01   1  1  1 |  0  0
 2  +1.237e+00  -4.595e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8057  1e-01   1  1  1 |  0  0
 3  +1.653e-01  -1.097e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8495  1e-01   1  2  2 |  0  0
 4  +7.251e-02  -7.936e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6284  5e-01   2  2  2 |  0  0
 5  +2.108e-02  -2.301e-01  +6e+00  9e-04  3e-05  6e-03  3e-02  0.7838  1e-01   1  2  2 |  0  0
 6  +1.223e-02  -1.463e-01  +4e+00  6e-04  2e-05  3e-03  2e-02  0.4778  2e-01   1  2  2 |  0  0
 7  +1.281e-02  -1.320e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2664  7e-01   1  2  2 |  0  0
 8  +4.149e-03  -4.972e-02  +1e+00  2e-04  7e-06  7e-04  7e-03  0.7726  2e-01   1  2  2 |  0  0
 9  +2.006e-03  -1.436e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8694  2e-01   1  2  2 |  0  0
10  +5.289e-04  -4.444e-03  +1e-01  2e-05  6e-07  4e-05  6e-04  0.7806  1e-01   1  2  2 |  0  0
11  +3.123e-04  -1.847e-03  +5e-02  7e-06  3e-07  1e-05  3e-04  0.8225  3e-01   1  2  2 |  0  0
12  +6.110e-05  -4.180e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8224  5e-02   1  1  2 |  0  0
13  +2.576e-05  -1.457e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.7973  2e-01   2  1  1 |  0  0
14  +5.052e-06  -3.226e-05  +9e-04  1e-07  5e-09  2e-07  5e-06  0.8018  2e-02   2  1  1 |  0  0
15  +1.711e-06  -9.468e-06  +3e-04  4e-08  1e-09  7e-08  1e-06  0.8498  2e-01   1  1  1 |  0  0
16  +3.643e-07  -2.224e-06  +7e-05  8e-09  3e-10  2e-08  3e-07  0.7894  3e-02   1  1  1 |  0  0
17  +1.159e-07  -6.449e-07  +2e-05  2e-09  1e-10  5e-09  9e-08  0.8512  2e-01   3  1  1 |  0  0
18  +2.188e-08  -1.489e-07  +4e-06  6e-10  2e-11  1e-09  2e-08  0.8009  3e-02   2  1  1 |  0  0
19  +4.587e-09  -4.506e-08  +1e-06  2e-10  7e-12  3e-10  6e-09  0.8420  2e-01   1  1  1 |  0  0
20  -1.556e-09  -1.314e-08  +3e-07  4e-11  2e-12  7e-11  1e-09  0.8178  6e-02   2  1  1 |  0  0
21  -2.793e-09  -5.980e-09  +8e-08  1e-11  6e-13  2e-11  4e-10  0.8570  2e-01   2  1  1 |  0  0
22  -3.191e-09  -3.914e-09  +2e-08  2e-12  3e-13  4e-12  9e-11  0.8397  8e-02   2  1  1 |  0  0
23  -3.274e-09  -3.453e-09  +5e-09  6e-13  1e-13  1e-12  2e-11  0.8785  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=5.9e-13, reltol=1.4e+00, abstol=4.6e-09).
Runtime: 0.010905 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.729e+00  -1.129e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.970e+00  -3.708e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3760  3e-01   1  1  1 |  0  0
 2  +1.237e+00  -4.596e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.8056  1e-01   1  1  1 |  0  0
 3  +1.654e-01  -1.097e+00  +3e+01  5e-03  2e-04  6e-02  2e-01  0.8494  1e-01   1  2  2 |  0  0
 4  +7.249e-02  -7.934e-01  +2e+01  3e-03  1e-04  3e-02  1e-01  0.6285  5e-01   2  2  2 |  0  0
 5  +2.107e-02  -2.300e-01  +6e+00  9e-04  3e-05  6e-03  3e-02  0.7838  1e-01   1  2  2 |  0  0
 6  +1.223e-02  -1.463e-01  +4e+00  6e-04  2e-05  3e-03  2e-02  0.4778  2e-01   1  2  2 |  0  0
 7  +1.281e-02  -1.319e-01  +4e+00  5e-04  2e-05  3e-03  2e-02  0.2665  7e-01   1  2  2 |  0  0
 8  +4.148e-03  -4.970e-02  +1e+00  2e-04  7e-06  7e-04  7e-03  0.7725  2e-01   1  2  2 |  0  0
 9  +2.007e-03  -1.436e-02  +4e-01  5e-05  2e-06  2e-04  2e-03  0.8693  2e-01   1  2  2 |  0  0
10  +5.289e-04  -4.445e-03  +1e-01  2e-05  6e-07  4e-05  6e-04  0.7806  1e-01   1  2  2 |  0  0
11  +3.122e-04  -1.847e-03  +5e-02  7e-06  3e-07  1e-05  3e-04  0.8224  3e-01   1  2  2 |  0  0
12  +6.112e-05  -4.181e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8222  5e-02   1  1  2 |  0  0
13  +2.579e-05  -1.459e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.7971  2e-01   1  1  1 |  0  0
14  +5.066e-06  -3.233e-05  +1e-03  1e-07  5e-09  2e-07  5e-06  0.8016  2e-02   2  1  1 |  0  0
15  +1.718e-06  -9.489e-06  +3e-04  4e-08  1e-09  7e-08  1e-06  0.8497  2e-01   2  1  1 |  0  0
16  +3.682e-07  -2.227e-06  +7e-05  8e-09  3e-10  2e-08  3e-07  0.7893  3e-02   2  1  1 |  0  0
17  +1.191e-07  -6.437e-07  +2e-05  2e-09  1e-10  5e-09  1e-07  0.8512  2e-01   2  1  1 |  0  0
18  +2.478e-08  -1.464e-07  +4e-06  6e-10  2e-11  1e-09  2e-08  0.8010  3e-02   2  1  1 |  0  0
19  +7.443e-09  -4.230e-08  +1e-06  2e-10  7e-12  3e-10  6e-09  0.8421  2e-01   2  1  1 |  0  0
20  +1.288e-09  -1.032e-08  +3e-07  4e-11  2e-12  7e-11  1e-09  0.8179  6e-02   2  1  1 |  0  0
21  +5.122e-11  -3.140e-09  +8e-08  1e-11  6e-13  2e-11  4e-10  0.8571  2e-01   2  1  1 |  0  0
22  -3.471e-10  -1.071e-09  +2e-08  2e-12  3e-13  4e-12  9e-11  0.8398  8e-02   1  1  1 |  0  0
23  -4.334e-10  -6.129e-10  +5e-09  6e-13  1e-13  1e-12  2e-11  0.8785  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=5.9e-13, reltol=1.1e+01, abstol=4.6e-09).
Runtime: 0.010870 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.443e+01  -1.548e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +9.046e-01  -8.022e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2503  4e-01   1  2  2 |  0  0
 2  -4.049e+00  -1.956e+01  +3e+02  6e-02  2e-03  5e-01  1e+00  0.7097  1e-01   1  1  1 |  0  0
 3  -7.759e+00  -1.151e+01  +7e+01  1e-02  4e-04  1e-01  4e-01  0.7622  6e-02   2  2  2 |  0  0
 4  -8.390e+00  -9.780e+00  +3e+01  4e-03  1e-04  4e-02  1e-01  0.6533  7e-02   1  2  2 |  0  0
 5  -8.613e+00  -9.266e+00  +1e+01  2e-03  5e-05  1e-02  7e-02  0.7441  3e-01   1  2  1 |  0  0
 6  -8.676e+00  -8.843e+00  +3e+00  5e-04  1e-05  3e-03  2e-02  0.7924  7e-02   1  1  1 |  0  0
 7  -8.697e+00  -8.738e+00  +9e-01  1e-04  3e-06  6e-04  4e-03  0.8182  8e-02   1  1  1 |  0  0
 8  -8.698e+00  -8.729e+00  +7e-01  9e-05  2e-06  4e-04  3e-03  0.4479  5e-01   1  1  1 |  0  0
 9  -8.703e+00  -8.705e+00  +6e-02  7e-06  2e-07  3e-05  3e-04  0.9279  2e-02   1  1  1 |  0  0
10  -8.703e+00  -8.703e+00  +8e-03  1e-06  3e-08  5e-06  4e-05  0.8744  3e-02   1  1  1 |  0  0
11  -8.703e+00  -8.703e+00  +7e-04  9e-08  2e-09  3e-07  3e-06  0.9392  2e-02   1  1  1 |  0  0
12  -8.703e+00  -8.703e+00  +5e-05  7e-09  2e-10  2e-08  3e-07  0.9718  5e-02   2  1  1 |  0  0
13  -8.703e+00  -8.703e+00  +3e-06  4e-10  1e-11  1e-09  1e-08  0.9499  8e-04   1  1  1 |  0  0
14  -8.703e+00  -8.703e+00  +6e-07  8e-11  2e-12  2e-10  3e-09  0.8474  8e-02   2  1  1 |  0  0
15  -8.703e+00  -8.703e+00  +4e-08  5e-12  1e-13  1e-11  2e-10  0.9593  2e-02   1  1  1 |  0  0

OPTIMAL (within feastol=4.9e-12, reltol=4.3e-09, abstol=3.7e-08).
Runtime: 0.007276 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.440e+00  -1.105e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.477e+00  -3.260e+01  +4e+02  2e-01  1e-02  1e+00  2e+00  0.4151  3e-01   1  1  1 |  0  0
 2  +5.609e-01  -3.039e+00  +8e+01  2e-02  9e-04  3e-01  4e-01  0.8805  8e-02   1  1  1 |  0  0
 3  -1.577e-01  -1.840e+00  +4e+01  7e-03  3e-04  1e-01  2e-01  0.7038  3e-01   2  2  2 |  0  0
 4  -2.937e-01  -7.694e-01  +1e+01  2e-03  8e-05  2e-02  6e-02  0.7731  9e-02   1  2  2 |  0  0
 5  -3.180e-01  -5.159e-01  +5e+00  7e-04  3e-05  8e-03  2e-02  0.6722  1e-01   1  1  1 |  0  0
 6  -3.187e-01  -4.446e-01  +3e+00  4e-04  2e-05  3e-03  2e-02  0.6807  5e-01   1  1  1 |  0  0
 7  -3.242e-01  -3.531e-01  +7e-01  1e-04  4e-06  6e-04  4e-03  0.8125  5e-02   1  1  1 |  0  0
 8  -3.254e-01  -3.395e-01  +3e-01  5e-05  2e-06  9e-05  2e-03  0.9890  5e-01   1  1  1 |  0  0
 9  -3.264e-01  -3.290e-01  +6e-02  8e-06  4e-07  2e-05  3e-04  0.8573  5e-02   1  1  1 |  0  0
10  -3.266e-01  -3.273e-01  +2e-02  2e-06  1e-07  4e-06  9e-05  0.8274  1e-01   2  1  1 |  0  0
11  -3.266e-01  -3.271e-01  +1e-02  1e-06  6e-08  3e-06  5e-05  0.6607  4e-01   1  1  1 |  0  0
12  -3.267e-01  -3.267e-01  +2e-03  2e-07  1e-08  4e-07  8e-06  0.8971  6e-02   1  1  1 |  0  0
13  -3.267e-01  -3.267e-01  +5e-04  6e-08  3e-09  1e-07  2e-06  0.8142  1e-01   2  1  1 |  0  0
14  -3.267e-01  -3.267e-01  +8e-05  1e-08  5e-10  2e-08  4e-07  0.9097  9e-02   1  1  1 |  0  0
15  -3.267e-01  -3.267e-01  +2e-05  2e-09  1e-10  4e-09  9e-08  0.8946  1e-01   2  1  1 |  0  0
16  -3.267e-01  -3.267e-01  +2e-06  3e-10  1e-11  5e-10  1e-08  0.9194  5e-02   2  1  1 |  0  0
17  -3.267e-01  -3.267e-01  +4e-07  5e-11  2e-12  9e-11  2e-09  0.8722  4e-02   2  1  1 |  0  0
18  -3.267e-01  -3.267e-01  +7e-08  9e-12  4e-13  2e-11  4e-10  0.9061  1e-01   2  1  1 |  0  0
19  -3.267e-01  -3.267e-01  +5e-09  7e-13  4e-14  1e-12  3e-11  0.9319  2e-03   2  1  1 |  0  0

OPTIMAL (within feastol=6.9e-13, reltol=1.6e-08, abstol=5.2e-09).
Runtime: 0.008887 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.572e+00  -1.111e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.694e+00  -2.878e+01  +4e+02  2e-01  8e-03  1e+00  2e+00  0.4579  3e-01   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.087e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.653e-05
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.087e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.513e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.938e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 6.323e-07
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.938e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.861e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.015e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.128e-08
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.015e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 9.031e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.940e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.104e-10
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.940e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.789e-03 seconds
Reranking users:   0%|          | 4/2064 [00:01<12:41,  2.71it/s](CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.079e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 7.515e+00
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.079e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.421e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.023e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.309e-01
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.023e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 9.748e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.056e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 4.871e-02
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 9.132e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 3.066e-03
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.026e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.826e+00  -1.147e+02  +6e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.485e+00  -2.727e+01  +4e+02  2e-01  5e-03  7e-01  2e+00  0.5139  2e-01   2  2  1 |  0  0
 2  +1.474e-01  -4.882e+00  +1e+02  2e-02  6e-04  1e-01  5e-01  0.7812  5e-02   2  2  2 |  0  0
 3  -1.648e-01  -1.165e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8693  1e-01   2  2  2 |  0  0
 4  -7.691e-02  -5.259e-01  +1e+01  2e-03  3e-05  7e-03  5e-02  0.6825  2e-01   2  2  2 |  0  0
 5  -4.746e-02  -2.736e-01  +5e+00  9e-04  2e-05  3e-03  3e-02  0.6117  2e-01   2  2  2 |  0  0
 6  -2.604e-02  -1.523e-01  +3e+00  5e-04  9e-06  1e-03  1e-02  0.8569  5e-01   1  2  2 |  0  0
 7  -8.196e-03  -4.884e-02  +9e-01  1e-04  3e-06  4e-04  5e-03  0.7257  7e-02   1  1  1 |  0  0
 8  -2.747e-03  -1.717e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.7115  9e-02   1  1  1 |  0  0
 9  -1.109e-03  -6.171e-03  +1e-01  2e-05  4e-07  4e-05  6e-04  0.7358  1e-01   1  1  1 |  0  0
10  -1.835e-04  -8.989e-04  +2e-02  3e-06  5e-08  5e-06  8e-05  0.9425  9e-02   1  1  1 |  0  0
11  -6.970e-05  -2.283e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.9714  2e-01   1  1  1 |  0  0
12  -4.662e-05  -9.494e-05  +1e-03  2e-07  3e-09  3e-07  5e-06  0.8154  1e-01   2  1  1 |  0  0
13  -3.983e-05  -5.617e-05  +4e-04  6e-08  1e-09  1e-07  2e-06  0.8474  2e-01   2  1  1 |  0  0
14  -3.692e-05  -3.873e-05  +4e-05  7e-09  1e-10  1e-08  2e-07  0.9030  2e-02   2  1  1 |  0  0
15  -3.655e-05  -3.664e-05  +2e-06  3e-10  6e-12  6e-10  1e-08  0.9810  3e-02   1  1  1 |  0  0
16  -3.653e-05  -3.653e-05  +5e-08  8e-12  2e-13  2e-11  3e-10  0.9766  4e-04   2  1  1 |  0  0
17  -3.653e-05  -3.653e-05  +5e-09  8e-13  3e-14  1e-12  2e-11  0.9108  9e-03   2  1  1 |  0  0

OPTIMAL (within feastol=7.8e-13, reltol=1.4e-04, abstol=5.0e-09).
Runtime: 0.008476 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.831e+00  -1.148e+02  +6e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.450e+00  -2.721e+01  +4e+02  2e-01  5e-03  7e-01  2e+00  0.5155  2e-01   2  2  1 |  0  0
 2  +1.407e-01  -4.919e+00  +1e+02  2e-02  6e-04  1e-01  5e-01  0.7794  5e-02   2  2  2 |  0  0
 3  -1.657e-01  -1.169e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8680  1e-01   2  2  2 |  0  0
 4  -7.540e-02  -5.168e-01  +1e+01  2e-03  3e-05  7e-03  5e-02  0.6873  2e-01   2  2  2 |  0  0
 5  -4.831e-02  -2.794e-01  +5e+00  9e-04  2e-05  3e-03  3e-02  0.5930  2e-01   2  2  2 |  0  0
 6  -2.720e-02  -1.575e-01  +3e+00  5e-04  9e-06  1e-03  1e-02  0.8485  5e-01   1  2  2 |  0  0
 7  -8.451e-03  -5.000e-02  +1e+00  2e-04  3e-06  4e-04  5e-03  0.7290  7e-02   1  1  1 |  0  0
 8  -2.808e-03  -1.763e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.7133  1e-01   1  1  1 |  0  0
 9  -1.126e-03  -6.391e-03  +1e-01  2e-05  4e-07  4e-05  6e-04  0.7361  1e-01   1  1  1 |  0  0
10  -1.558e-04  -9.026e-04  +2e-02  3e-06  5e-08  5e-06  8e-05  0.9441  9e-02   1  1  1 |  0  0
11  -3.512e-05  -1.963e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.9810  2e-01   1  1  1 |  0  0
12  -1.331e-05  -7.388e-05  +1e-03  2e-07  4e-09  4e-07  7e-06  0.7778  2e-01   2  1  1 |  0  0
13  -2.211e-06  -9.615e-06  +2e-04  3e-08  5e-10  5e-08  8e-07  0.9291  6e-02   2  1  1 |  0  0
14  -7.402e-07  -1.264e-06  +1e-05  2e-09  4e-11  4e-09  6e-08  0.9344  6e-03   1  1  1 |  0  0
15  -6.440e-07  -7.012e-07  +1e-06  2e-10  4e-12  4e-10  6e-09  0.9128  2e-02   2  1  1 |  0  0
16  -6.347e-07  -6.468e-07  +3e-07  4e-11  8e-13  8e-11  1e-09  0.8109  3e-02   2  1  1 |  0  0
17  -6.324e-07  -6.329e-07  +1e-08  2e-12  5e-14  3e-12  6e-11  0.9878  3e-02   1  1  1 |  0  0
18  -6.323e-07  -6.323e-07  +6e-10  2e-13  4e-15  2e-13  3e-12  0.9514  5e-03   2  1  1 |  0  0

OPTIMAL (within feastol=2.2e-13, reltol=9.9e-04, abstol=6.3e-10).
Runtime: 0.008825 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.831e+00  -1.148e+02  +6e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.446e+00  -2.721e+01  +4e+02  2e-01  5e-03  7e-01  2e+00  0.5157  2e-01   2  2  1 |  0  0
 2  +1.400e-01  -4.924e+00  +1e+02  2e-02  6e-04  1e-01  5e-01  0.7792  5e-02   2  2  2 |  0  0
 3  -1.658e-01  -1.169e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8678  1e-01   2  2  2 |  0  0
 4  -7.531e-02  -5.161e-01  +1e+01  2e-03  3e-05  7e-03  5e-02  0.6877  2e-01   2  2  2 |  0  0
 5  -4.841e-02  -2.800e-01  +5e+00  9e-04  2e-05  3e-03  3e-02  0.5914  2e-01   2  2  2 |  0  0
 6  -2.731e-02  -1.580e-01  +3e+00  5e-04  9e-06  1e-03  1e-02  0.8478  5e-01   1  2  2 |  0  0
 7  -8.503e-03  -5.024e-02  +1e+00  2e-04  3e-06  4e-04  5e-03  0.7285  7e-02   1  1  1 |  0  0
 8  -2.824e-03  -1.772e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.7133  1e-01   1  1  1 |  0  0
 9  -1.133e-03  -6.430e-03  +1e-01  2e-05  4e-07  4e-05  6e-04  0.7368  1e-01   1  1  1 |  0  0
10  -1.561e-04  -9.065e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.9448  9e-02   1  1  1 |  0  0
11  -3.418e-05  -1.936e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.9867  2e-01   1  1  1 |  0  0
12  -1.252e-05  -7.208e-05  +1e-03  2e-07  4e-09  4e-07  7e-06  0.7782  2e-01   1  1  1 |  0  0
13  -1.577e-06  -8.950e-06  +2e-04  3e-08  5e-10  5e-08  8e-07  0.9344  6e-02   2  1  1 |  0  0
14  -1.369e-07  -7.458e-07  +1e-05  2e-09  4e-11  4e-09  7e-08  0.9234  7e-03   2  1  1 |  0  0
15  -2.512e-08  -9.193e-08  +2e-06  2e-10  5e-12  5e-10  8e-09  0.9381  5e-02   2  1  1 |  0  0
16  -1.308e-08  -2.179e-08  +2e-07  3e-11  6e-13  6e-11  1e-09  0.8808  1e-02   2  1  1 |  0  0
17  -1.137e-08  -1.183e-08  +1e-08  2e-12  4e-14  3e-12  5e-11  0.9890  4e-02   2  1  1 |  0  0
18  -1.128e-08  -1.131e-08  +6e-10  1e-13  4e-15  2e-13  3e-12  0.9465  2e-04   1  1  1 |  0  0

OPTIMAL (within feastol=1.0e-13, reltol=5.0e-02, abstol=5.6e-10).
Runtime: 0.008997 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.831e+00  -1.148e+02  +6e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.445e+00  -2.721e+01  +4e+02  2e-01  5e-03  7e-01  2e+00  0.5157  2e-01   2  2  1 |  0  0
 2  +1.399e-01  -4.924e+00  +1e+02  2e-02  6e-04  1e-01  5e-01  0.7792  5e-02   2  2  2 |  0  0
 3  -1.658e-01  -1.169e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8678  1e-01   2  2  2 |  0  0
 4  -7.528e-02  -5.160e-01  +1e+01  2e-03  3e-05  7e-03  5e-02  0.6877  2e-01   2  2  2 |  0  0
 5  -4.842e-02  -2.801e-01  +5e+00  9e-04  2e-05  3e-03  3e-02  0.5911  2e-01   2  2  2 |  0  0
 6  -2.733e-02  -1.580e-01  +3e+00  5e-04  9e-06  1e-03  1e-02  0.8476  5e-01   1  2  2 |  0  0
 7  -8.508e-03  -5.026e-02  +1e+00  2e-04  3e-06  4e-04  5e-03  0.7286  7e-02   1  1  1 |  0  0
 8  -2.825e-03  -1.773e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.7134  1e-01   1  1  1 |  0  0
 9  -1.134e-03  -6.434e-03  +1e-01  2e-05  4e-07  4e-05  6e-04  0.7368  1e-01   1  1  1 |  0  0
10  -1.562e-04  -9.071e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.9449  9e-02   1  1  1 |  0  0
11  -3.419e-05  -1.936e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.9870  2e-01   1  1  1 |  0  0
12  -1.251e-05  -7.202e-05  +1e-03  2e-07  4e-09  4e-07  7e-06  0.7783  2e-01   1  1  1 |  0  0
13  -1.563e-06  -8.917e-06  +2e-04  3e-08  5e-10  5e-08  8e-07  0.9345  6e-02   2  1  1 |  0  0
14  -1.283e-07  -7.490e-07  +1e-05  2e-09  4e-11  4e-09  7e-08  0.9219  7e-03   2  1  1 |  0  0
15  -1.421e-08  -8.168e-08  +2e-06  2e-10  5e-12  5e-10  8e-09  0.9440  6e-02   1  1  1 |  0  0
16  -1.953e-09  -1.037e-08  +2e-07  3e-11  6e-13  6e-11  1e-09  0.8849  1e-02   2  1  1 |  0  0
17  -3.192e-10  -8.142e-10  +1e-08  2e-12  4e-14  3e-12  6e-11  0.9890  5e-02   1  1  1 |  0  0
18  -2.189e-10  -2.428e-10  +6e-10  1e-13  4e-15  2e-13  3e-12  0.9519  2e-04   2  1  1 |  0  0

OPTIMAL (within feastol=1.0e-13, reltol=2.5e+00, abstol=5.5e-10).
Runtime: 0.008754 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.326e+01  -1.540e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +1.738e+00  -8.036e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2433  5e-01   1  2  2 |  0  0
 2  -3.243e+00  -1.836e+01  +2e+02  5e-02  2e-03  6e-01  1e+00  0.7228  1e-01   1  1  1 |  0  0
 3  -6.582e+00  -1.011e+01  +7e+01  1e-02  4e-04  1e-01  3e-01  0.7659  6e-02   2  1  2 |  0  0
 4  -7.425e+00  -8.281e+00  +2e+01  3e-03  8e-05  3e-02  9e-02  0.8111  8e-02   1  2  2 |  0  0
 5  -7.463e+00  -7.837e+00  +8e+00  1e-03  3e-05  8e-03  4e-02  0.7498  3e-01   1  2  2 |  0  0
 6  -7.502e+00  -7.596e+00  +2e+00  3e-04  8e-06  2e-03  1e-02  0.8005  7e-02   1  1  1 |  0  0
 7  -7.511e+00  -7.539e+00  +6e-01  8e-05  2e-06  4e-04  3e-03  0.8003  1e-01   1  1  1 |  0  0
 8  -7.512e+00  -7.532e+00  +4e-01  6e-05  2e-06  2e-04  2e-03  0.5325  5e-01   1  2  2 |  0  0
 9  -7.514e+00  -7.517e+00  +5e-02  6e-06  2e-07  2e-05  2e-04  0.9323  5e-02   1  1  1 |  0  0
10  -7.515e+00  -7.515e+00  +1e-02  1e-06  4e-08  4e-06  5e-05  0.8401  6e-02   1  1  1 |  0  0
11  -7.515e+00  -7.515e+00  +5e-03  7e-07  2e-08  2e-06  2e-05  0.6887  3e-01   2  1  1 |  0  0
12  -7.515e+00  -7.515e+00  +5e-04  6e-08  2e-09  2e-07  2e-06  0.9232  2e-02   2  1  1 |  0  0
13  -7.515e+00  -7.515e+00  +1e-04  1e-08  4e-10  4e-08  5e-07  0.8115  5e-02   2  1  1 |  0  0
14  -7.515e+00  -7.515e+00  +7e-05  9e-09  3e-10  3e-08  3e-07  0.5669  3e-01   1  1  1 |  0  0
15  -7.515e+00  -7.515e+00  +6e-06  8e-10  2e-11  2e-09  3e-08  0.9890  8e-02   1  1  1 |  0  0
16  -7.515e+00  -7.515e+00  +3e-07  4e-11  1e-12  1e-10  1e-09  0.9500  4e-03   1  1  1 |  0  0
17  -7.515e+00  -7.515e+00  +8e-09  1e-12  4e-14  3e-12  4e-11  0.9744  1e-03   2  1  1 |  0  0

OPTIMAL (within feastol=1.1e-12, reltol=1.1e-09, abstol=8.2e-09).
Runtime: 0.008367 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.575e+00  -1.071e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.266e+00  -4.083e+01  +4e+02  2e-01  2e-02  2e+00  2e+00  0.3628  4e-01   1  1  1 |  0  0
 2  +3.108e-01  -2.317e+00  +6e+01  1e-02  1e-03  1e+00  4e-01  0.9635  1e-01   1  1  1 |  0  0
 3  -2.309e-02  -1.956e+00  +5e+01  1e-02  1e-03  6e-01  3e-01  0.3776  3e-01   1  1  1 |  0  0
 4  -2.002e-01  -1.165e+00  +2e+01  5e-03  4e-04  3e-01  1e-01  0.5474  1e-01   1  1  1 |  0  0
 5  -2.508e-01  -9.494e-01  +2e+01  3e-03  3e-04  1e-01  1e-01  0.6394  5e-01   1  1  1 |  0  0
 6  -2.895e-01  -5.105e-01  +6e+00  9e-04  8e-05  3e-02  3e-02  0.7126  5e-02   1  1  1 |  0  0
 7  -3.123e-01  -4.279e-01  +3e+00  4e-04  4e-05  1e-02  2e-02  0.6282  2e-01   1  1  1 |  0  0
 8  -3.216e-01  -3.671e-01  +1e+00  2e-04  1e-05  3e-03  6e-03  0.7331  2e-01   1  1  1 |  0  0
 9  -3.260e-01  -3.491e-01  +6e-01  8e-05  7e-06  1e-03  3e-03  0.6542  2e-01   1  1  1 |  0  0
10  -3.275e-01  -3.401e-01  +3e-01  4e-05  4e-06  2e-04  2e-03  0.8692  5e-01   1  1  1 |  0  0
11  -3.298e-01  -3.339e-01  +1e-01  1e-05  1e-06  5e-05  5e-04  0.8033  2e-01   1  1  1 |  0  0
12  -3.307e-01  -3.313e-01  +1e-02  2e-06  2e-07  4e-06  7e-05  0.9487  9e-02   1  1  1 |  0  0
13  -3.309e-01  -3.310e-01  +3e-03  4e-07  4e-08  9e-07  2e-05  0.8412  9e-02   1  1  1 |  0  0
14  -3.309e-01  -3.309e-01  +1e-03  2e-07  1e-08  3e-07  6e-06  0.7997  2e-01   1  1  1 |  0  0
15  -3.309e-01  -3.309e-01  +2e-04  2e-08  2e-09  4e-08  8e-07  0.9260  6e-02   1  1  1 |  0  0
16  -3.309e-01  -3.309e-01  +5e-05  6e-09  6e-10  1e-08  3e-07  0.7352  9e-02   2  1  1 |  0  0
17  -3.309e-01  -3.309e-01  +3e-05  4e-09  4e-10  7e-09  1e-07  0.6293  3e-01   2  1  1 |  0  0
18  -3.309e-01  -3.309e-01  +4e-06  5e-10  5e-11  9e-10  2e-08  0.9497  9e-02   2  1  1 |  0  0
19  -3.309e-01  -3.309e-01  +5e-07  7e-11  6e-12  1e-10  3e-09  0.8776  1e-02   2  1  1 |  0  0
20  -3.309e-01  -3.309e-01  +2e-07  2e-11  2e-12  4e-11  9e-10  0.7679  1e-01   1  1  1 |  0  0
21  -3.309e-01  -3.309e-01  +3e-08  4e-12  5e-13  7e-12  2e-10  0.8901  1e-01   2  1  1 |  0  0
22  -3.309e-01  -3.309e-01  +6e-09  8e-13  1e-13  1e-12  3e-11  0.9890  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=7.8e-13, reltol=1.9e-08, abstol=6.3e-09).
Runtime: 0.009714 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.711e+00  -1.068e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.073e+00  -3.303e+01  +4e+02  2e-01  1e-02  1e+00  2e+00  0.4064  3e-01   1  1  1 |  0  0
 2  +6.406e-01  -2.632e+00  +7e+01  2e-02  1e-03  4e-01  4e-01  0.8988  1e-01   1  1  1 |  0  0
 3  +1.039e-01  -1.297e+00  +3e+01  6e-03  4e-04  2e-01  2e-01  0.6258  1e-01   1  2  2 |  0  0
 4  -1.968e-02  -7.659e-01  +2e+01  3e-03  2e-04  5e-02  9e-02  0.7242  3e-01   1  2  1 |  0  0
 5  -3.938e-02  -5.418e-01  +1e+01  2e-03  1e-04  2e-02  6e-02  0.6994  5e-01   1  1  2 |  0  0
 6  -4.411e-02  -1.824e-01  +3e+00  5e-04  3e-05  3e-03  2e-02  0.8481  1e-01   1  2  2 |  0  0
 7  -4.691e-02  -8.756e-02  +1e+00  1e-04  7e-06  6e-04  5e-03  0.8308  2e-01   1  2  2 |  0  0
 8  -4.697e-02  -6.984e-02  +6e-01  8e-05  4e-06  2e-04  3e-03  0.7513  4e-01   1  2  2 |  0  0
 9  -4.819e-02  -5.721e-02  +2e-01  3e-05  2e-06  8e-05  1e-03  0.7316  2e-01   1  1  2 |  0  0
10  -4.833e-02  -5.270e-02  +1e-01  1e-05  8e-07  3e-05  5e-04  0.7670  3e-01   1  1  1 |  0  0
11  -4.856e-02  -5.017e-02  +4e-02  5e-06  3e-07  9e-06  2e-04  0.9890  4e-01   1  1  1 |  0  0
12  -4.868e-02  -4.893e-02  +6e-03  8e-07  4e-08  1e-06  3e-05  0.8833  4e-02   1  1  1 |  0  0
13  -4.870e-02  -4.877e-02  +2e-03  2e-07  1e-08  4e-07  8e-06  0.9890  3e-01   2  1  1 |  0  0
14  -4.871e-02  -4.872e-02  +2e-04  3e-08  1e-09  5e-08  1e-06  0.8992  2e-02   2  1  1 |  0  0
15  -4.871e-02  -4.871e-02  +4e-05  6e-09  3e-10  1e-08  2e-07  0.9515  2e-01   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.089e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.167e-04
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.089e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.011e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.027e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 4.325e-06
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.027e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.016e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.067e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 1.955e-07
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.067e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.030e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.020e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 9.988e-09
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.020e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.012e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 9.994e-03 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 5.390e-10
(CVXPY) Jun 21 07:40:14 PM: Compilation took 9.994e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.014e-02 seconds
Reranking users:   0%|          | 5/2064 [00:01<11:03,  3.10it/s](CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.056e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 8.273e+00
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.056e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 8.802e-03 seconds
(CVXPY) Jun 21 07:40:14 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:14 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:14 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:14 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:14 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:14 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:14 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:14 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:14 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:14 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:14 PM: Finished problem compilation (took 1.049e-02 seconds).
(CVXPY) Jun 21 07:40:14 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:14 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:14 PM: Optimal value: 2.093e-01
(CVXPY) Jun 21 07:40:14 PM: Compilation took 1.049e-02 seconds
(CVXPY) Jun 21 07:40:14 PM: Solver (including time spent in interface) took 1.025e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.022e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.055e-02
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.022e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.003e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.932e+00  -1.096e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.458e+00  -2.945e+01  +4e+02  2e-01  8e-03  9e-01  2e+00  0.4477  3e-01   1  1  1 |  0  0
 2  +3.588e-01  -2.948e+00  +7e+01  2e-02  6e-04  2e-01  3e-01  0.8780  6e-02   1  1  1 |  0  0
 3  +5.618e-03  -1.050e+00  +2e+01  4e-03  1e-04  4e-02  1e-01  0.7686  2e-01   2  2  2 |  0  0
 4  -3.357e-03  -6.022e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.5148  2e-01   2  2  2 |  0  0
 5  -1.125e-02  -5.534e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.3060  7e-01   2  2  1 |  0  0
 6  -1.403e-02  -1.867e-01  +4e+00  7e-04  2e-05  2e-03  2e-02  0.8906  2e-01   1  2  1 |  0  0
 7  -1.818e-03  -5.947e-02  +1e+00  2e-04  6e-06  5e-04  7e-03  0.9083  3e-01   1  2  2 |  0  0
 8  -8.166e-04  -1.703e-02  +4e-01  6e-05  2e-06  1e-04  2e-03  0.7953  1e-01   1  2  2 |  0  0
 9  -7.164e-04  -8.942e-03  +2e-01  3e-05  9e-07  6e-05  1e-03  0.7495  3e-01   1  2  1 |  0  0
10  -2.551e-04  -5.203e-03  +1e-01  2e-05  5e-07  3e-05  6e-04  0.7683  5e-01   1  2  2 |  0  0
11  -1.910e-04  -1.586e-03  +3e-02  5e-06  1e-07  9e-06  2e-04  0.8393  1e-01   1  1  2 |  0  0
12  -1.343e-04  -4.945e-04  +9e-03  1e-06  4e-08  2e-06  4e-05  0.8657  1e-01   1  1  1 |  0  0
13  -1.202e-04  -2.070e-04  +2e-03  3e-07  9e-09  5e-07  1e-05  0.9890  2e-01   1  1  1 |  0  0
14  -1.170e-04  -1.254e-04  +2e-04  3e-08  9e-10  5e-08  1e-06  0.9224  2e-02   1  1  1 |  0  0
15  -1.167e-04  -1.182e-04  +4e-05  5e-09  2e-10  9e-09  2e-07  0.8815  7e-02   1  1  1 |  0  0
16  -1.167e-04  -1.171e-04  +1e-05  2e-09  5e-11  3e-09  5e-08  0.8003  1e-01   2  1  1 |  0  0
17  -1.167e-04  -1.168e-04  +3e-06  5e-10  1e-11  9e-10  2e-08  0.8545  2e-01   1  1  1 |  0  0
18  -1.167e-04  -1.167e-04  +7e-07  1e-10  3e-12  2e-10  3e-09  0.9444  2e-01   2  1  1 |  0  0
19  -1.167e-04  -1.167e-04  +1e-07  2e-11  6e-13  3e-11  5e-10  0.8844  5e-02   1  1  1 |  0  0
20  -1.167e-04  -1.167e-04  +3e-08  4e-12  2e-13  8e-12  1e-10  0.8441  2e-01   2  1  1 |  0  0
21  -1.167e-04  -1.167e-04  +7e-09  1e-12  7e-14  2e-12  3e-11  0.9100  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=9.8e-13, reltol=5.7e-05, abstol=6.7e-09).
Runtime: 0.010060 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.945e+00  -1.098e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.422e+00  -2.937e+01  +4e+02  2e-01  8e-03  9e-01  2e+00  0.4500  3e-01   1  1  1 |  0  0
 2  +3.356e-01  -2.963e+00  +7e+01  2e-02  5e-04  2e-01  3e-01  0.8782  6e-02   1  1  2 |  0  0
 3  +4.451e-03  -1.009e+00  +2e+01  4e-03  1e-04  4e-02  1e-01  0.7809  2e-01   2  2  2 |  0  0
 4  -5.626e-03  -5.963e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.5009  2e-01   2  2  2 |  0  0
 5  -1.305e-02  -5.481e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.3052  7e-01   2  2  1 |  0  0
 6  -1.434e-02  -1.959e-01  +4e+00  7e-04  2e-05  3e-03  2e-02  0.8567  2e-01   1  2  2 |  0  0
 7  -2.153e-03  -5.435e-02  +1e+00  2e-04  5e-06  5e-04  6e-03  0.9042  2e-01   1  2  2 |  0  0
 8  -8.390e-04  -1.682e-02  +4e-01  6e-05  2e-06  1e-04  2e-03  0.7933  1e-01   1  2  2 |  0  0
 9  -6.148e-04  -8.330e-03  +2e-01  3e-05  8e-07  6e-05  9e-04  0.6750  2e-01   1  1  1 |  0  0
10  -5.326e-05  -3.909e-03  +9e-02  1e-05  4e-07  3e-05  5e-04  0.8722  4e-01   1  2  2 |  0  0
11  -5.565e-05  -8.168e-04  +2e-02  3e-06  8e-08  5e-06  9e-05  0.9501  2e-01   1  1  1 |  0  0
12  -1.145e-05  -1.590e-04  +4e-03  5e-07  1e-08  9e-07  2e-05  0.8593  6e-02   1  1  1 |  0  0
13  -6.879e-06  -6.997e-05  +2e-03  2e-07  6e-09  4e-07  7e-06  0.8118  3e-01   2  1  1 |  0  0
14  -5.280e-06  -2.348e-05  +4e-04  6e-08  2e-09  1e-07  2e-06  0.8507  2e-01   2  1  1 |  0  0
15  -4.499e-06  -8.875e-06  +1e-04  2e-08  4e-10  3e-08  5e-07  0.9047  2e-01   1  1  1 |  0  0
16  -4.342e-06  -4.668e-06  +8e-06  1e-09  3e-11  2e-09  4e-08  0.9353  1e-02   2  1  1 |  0  0
17  -4.330e-06  -4.425e-06  +2e-06  3e-10  1e-11  6e-10  1e-08  0.7883  1e-01   2  1  1 |  0  0
18  -4.327e-06  -4.371e-06  +1e-06  2e-10  5e-12  3e-10  5e-09  0.6967  2e-01   2  1  1 |  0  0
19  -4.326e-06  -4.343e-06  +4e-07  6e-11  2e-12  1e-10  2e-09  0.8559  3e-01   1  1  1 |  0  0
20  -4.325e-06  -4.328e-06  +6e-08  9e-12  4e-13  2e-11  3e-10  0.9890  1e-01   2  1  1 |  0  0
21  -4.325e-06  -4.325e-06  +8e-09  1e-12  9e-14  2e-12  4e-11  0.8858  1e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.2e-12, reltol=1.8e-03, abstol=8.0e-09).
Runtime: 0.010121 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.947e+00  -1.098e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.418e+00  -2.934e+01  +4e+02  2e-01  8e-03  9e-01  2e+00  0.4506  3e-01   1  1  1 |  0  0
 2  +3.317e-01  -2.964e+00  +7e+01  2e-02  5e-04  2e-01  3e-01  0.8782  6e-02   1  1  2 |  0  0
 3  +4.873e-03  -1.005e+00  +2e+01  4e-03  1e-04  4e-02  1e-01  0.7818  2e-01   2  2  2 |  0  0
 4  -5.661e-03  -5.955e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.4997  2e-01   2  2  2 |  0  0
 5  -1.312e-02  -5.473e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.3056  7e-01   2  2  1 |  0  0
 6  -1.437e-02  -1.973e-01  +4e+00  7e-04  2e-05  3e-03  2e-02  0.8514  2e-01   1  2  2 |  0  0
 7  -2.205e-03  -5.352e-02  +1e+00  2e-04  5e-06  5e-04  6e-03  0.9038  2e-01   1  2  2 |  0  0
 8  -8.515e-04  -1.707e-02  +4e-01  6e-05  2e-06  1e-04  2e-03  0.7878  1e-01   1  2  2 |  0  0
 9  -5.956e-04  -8.426e-03  +2e-01  3e-05  8e-07  6e-05  9e-04  0.6827  2e-01   1  1  1 |  0  0
10  -4.253e-05  -3.888e-03  +9e-02  1e-05  4e-07  3e-05  5e-04  0.8800  4e-01   1  2  2 |  0  0
11  -5.061e-05  -7.865e-04  +2e-02  3e-06  7e-08  5e-06  9e-05  0.9562  2e-01   1  1  1 |  0  0
12  -8.248e-06  -1.646e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.8348  6e-02   1  1  1 |  0  0
13  -3.115e-06  -7.242e-05  +2e-03  2e-07  7e-09  4e-07  8e-06  0.8351  3e-01   1  1  1 |  0  0
14  -1.223e-06  -2.043e-05  +5e-04  7e-08  2e-09  1e-07  2e-06  0.8615  2e-01   2  1  1 |  0  0
15  -3.698e-07  -4.707e-06  +1e-04  2e-08  4e-10  3e-08  5e-07  0.9032  1e-01   1  1  1 |  0  0
16  -2.132e-07  -5.441e-07  +8e-06  1e-09  3e-11  2e-09  4e-08  0.9325  9e-03   2  1  1 |  0  0
17  -2.005e-07  -2.986e-07  +2e-06  3e-10  1e-11  6e-10  1e-08  0.7925  1e-01   1  1  1 |  0  0
18  -1.981e-07  -2.436e-07  +1e-06  2e-10  5e-12  3e-10  5e-09  0.6914  2e-01   1  1  1 |  0  0
19  -1.964e-07  -2.145e-07  +4e-07  6e-11  2e-12  1e-10  2e-09  0.8531  3e-01   2  1  1 |  0  0
20  -1.957e-07  -1.986e-07  +7e-08  1e-11  4e-13  2e-11  3e-10  0.9890  1e-01   2  1  1 |  0  0
21  -1.956e-07  -1.960e-07  +9e-09  1e-12  9e-14  2e-12  4e-11  0.8857  1e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=4.4e-02, abstol=8.5e-09).
Runtime: 0.010258 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.947e+00  -1.098e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.416e+00  -2.934e+01  +4e+02  2e-01  8e-03  9e-01  2e+00  0.4506  3e-01   1  1  1 |  0  0
 2  +3.309e-01  -2.965e+00  +7e+01  2e-02  5e-04  2e-01  3e-01  0.8782  6e-02   1  1  2 |  0  0
 3  +4.820e-03  -1.004e+00  +2e+01  4e-03  1e-04  4e-02  1e-01  0.7822  2e-01   2  2  2 |  0  0
 4  -5.751e-03  -5.953e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.4992  2e-01   2  2  2 |  0  0
 5  -1.319e-02  -5.471e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.3057  7e-01   2  2  1 |  0  0
 6  -1.438e-02  -1.976e-01  +4e+00  7e-04  2e-05  3e-03  2e-02  0.8503  2e-01   1  2  2 |  0  0
 7  -2.220e-03  -5.337e-02  +1e+00  2e-04  5e-06  5e-04  6e-03  0.9037  2e-01   1  2  2 |  0  0
 8  -8.553e-04  -1.713e-02  +4e-01  6e-05  2e-06  1e-04  2e-03  0.7863  1e-01   1  2  2 |  0  0
 9  -5.919e-04  -8.461e-03  +2e-01  3e-05  8e-07  6e-05  9e-04  0.6873  2e-01   1  1  1 |  0  0
10  -4.163e-05  -3.884e-03  +9e-02  1e-05  4e-07  3e-05  5e-04  0.8813  4e-01   1  2  2 |  0  0
11  -5.043e-05  -7.838e-04  +2e-02  3e-06  7e-08  5e-06  9e-05  0.9565  2e-01   1  1  1 |  0  0
12  -8.203e-06  -1.661e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.8339  6e-02   1  1  1 |  0  0
13  -3.004e-06  -7.373e-05  +2e-03  3e-07  7e-09  4e-07  8e-06  0.8321  3e-01   1  1  1 |  0  0
14  -1.063e-06  -2.064e-05  +5e-04  7e-08  2e-09  1e-07  2e-06  0.8635  2e-01   1  1  1 |  0  0
15  -1.880e-07  -4.601e-06  +1e-04  2e-08  4e-10  3e-08  5e-07  0.9018  1e-01   1  1  1 |  0  0
16  -2.802e-08  -3.631e-07  +8e-06  1e-09  3e-11  2e-09  4e-08  0.9328  9e-03   1  1  1 |  0  0
17  -1.504e-08  -1.140e-07  +2e-06  4e-10  1e-11  6e-10  1e-08  0.7936  1e-01   2  1  1 |  0  0
18  -1.258e-08  -5.860e-08  +1e-06  2e-10  5e-12  3e-10  5e-09  0.6902  2e-01   1  1  1 |  0  0
19  -1.085e-08  -2.927e-08  +4e-07  7e-11  2e-12  1e-10  2e-09  0.8515  3e-01   1  1  1 |  0  0
20  -1.021e-08  -1.311e-08  +7e-08  1e-11  4e-13  2e-11  3e-10  0.9890  1e-01   1  1  1 |  0  0
21  -1.008e-08  -1.044e-08  +9e-09  1e-12  9e-14  2e-12  4e-11  0.8865  1e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=8.6e-01, abstol=8.7e-09).
Runtime: 0.010089 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.947e+00  -1.098e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.416e+00  -2.934e+01  +4e+02  2e-01  8e-03  9e-01  2e+00  0.4506  3e-01   1  1  1 |  0  0
 2  +3.308e-01  -2.965e+00  +7e+01  2e-02  5e-04  2e-01  3e-01  0.8782  6e-02   1  1  2 |  0  0
 3  +4.837e-03  -1.004e+00  +2e+01  4e-03  1e-04  4e-02  1e-01  0.7823  2e-01   2  2  2 |  0  0
 4  -5.750e-03  -5.952e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.4992  2e-01   2  2  2 |  0  0
 5  -1.320e-02  -5.471e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.3057  7e-01   2  2  1 |  0  0
 6  -1.439e-02  -1.976e-01  +4e+00  7e-04  2e-05  3e-03  2e-02  0.8501  2e-01   1  2  2 |  0  0
 7  -2.222e-03  -5.334e-02  +1e+00  2e-04  5e-06  5e-04  6e-03  0.9037  2e-01   1  2  2 |  0  0
 8  -8.558e-04  -1.714e-02  +4e-01  6e-05  2e-06  1e-04  2e-03  0.7861  1e-01   1  2  2 |  0  0
 9  -5.912e-04  -8.469e-03  +2e-01  3e-05  8e-07  6e-05  9e-04  0.6881  3e-01   1  1  1 |  0  0
10  -4.144e-05  -3.884e-03  +9e-02  1e-05  4e-07  3e-05  5e-04  0.8816  4e-01   1  2  2 |  0  0
11  -5.042e-05  -7.833e-04  +2e-02  3e-06  7e-08  5e-06  9e-05  0.9566  2e-01   1  1  1 |  0  0
12  -8.212e-06  -1.664e-04  +4e-03  6e-07  2e-08  1e-06  2e-05  0.8340  6e-02   1  1  1 |  0  0
13  -3.002e-06  -7.385e-05  +2e-03  3e-07  7e-09  4e-07  8e-06  0.8330  3e-01   2  1  1 |  0  0
14  -1.054e-06  -2.063e-05  +5e-04  7e-08  2e-09  1e-07  2e-06  0.8638  2e-01   2  1  1 |  0  0
15  -1.782e-07  -4.582e-06  +1e-04  2e-08  4e-10  3e-08  5e-07  0.9016  1e-01   1  1  1 |  0  0
16  -1.855e-08  -3.534e-07  +8e-06  1e-09  3e-11  2e-09  4e-08  0.9327  9e-03   2  1  1 |  0  0
17  -5.590e-09  -1.046e-07  +2e-06  4e-10  1e-11  6e-10  1e-08  0.7935  1e-01   2  1  1 |  0  0
18  -3.130e-09  -4.912e-08  +1e-06  2e-10  5e-12  3e-10  5e-09  0.6905  2e-01   1  1  1 |  0  0
19  -1.396e-09  -1.980e-08  +4e-07  7e-11  2e-12  1e-10  2e-09  0.8518  3e-01   1  1  1 |  0  0
20  -7.589e-10  -3.648e-09  +7e-08  1e-11  4e-13  2e-11  3e-10  0.9890  1e-01   2  1  1 |  0  0
21  -6.299e-10  -9.911e-10  +9e-09  1e-12  9e-14  2e-12  4e-11  0.8862  1e-02   1  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=1.4e+01, abstol=8.7e-09).
Runtime: 0.010105 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.150e+01  -1.619e+02  +9e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +3.261e+00  -8.266e+01  +7e+02  3e-01  1e-02  1e+00  4e+00  0.2550  4e-01   1  2  2 |  0  0
 2  -3.151e+00  -1.923e+01  +3e+02  5e-02  2e-03  6e-01  1e+00  0.7219  1e-01   1  1  1 |  0  0
 3  -7.607e+00  -1.176e+01  +8e+01  1e-02  4e-04  1e-01  4e-01  0.7502  7e-02   2  2  2 |  0  0
 4  -8.124e+00  -9.261e+00  +2e+01  3e-03  9e-05  2e-02  1e-01  0.9221  2e-01   1  2  2 |  0  0
 5  -8.209e+00  -8.546e+00  +7e+00  9e-04  3e-05  4e-03  4e-02  0.8417  2e-01   1  1  1 |  0  0
 6  -8.265e+00  -8.316e+00  +1e+00  1e-04  4e-06  5e-04  5e-03  0.9327  9e-02   1  1  1 |  0  0
 7  -8.270e+00  -8.283e+00  +3e-01  3e-05  1e-06  1e-04  1e-03  0.9056  2e-01   1  1  1 |  0  0
 8  -8.273e+00  -8.274e+00  +2e-02  3e-06  8e-08  8e-06  1e-04  0.9219  5e-03   2  1  1 |  0  0
 9  -8.273e+00  -8.273e+00  +6e-03  6e-07  2e-08  2e-06  3e-05  0.8984  2e-01   1  1  1 |  0  0
10  -8.273e+00  -8.273e+00  +3e-03  3e-07  9e-09  9e-07  1e-05  0.7167  2e-01   2  1  1 |  0  0
11  -8.273e+00  -8.273e+00  +7e-04  8e-08  3e-09  2e-07  3e-06  0.7403  3e-02   2  1  1 |  0  0
12  -8.273e+00  -8.273e+00  +3e-04  3e-08  9e-10  9e-08  1e-06  0.7527  2e-01   2  1  1 |  0  0
13  -8.273e+00  -8.273e+00  +8e-05  9e-09  3e-10  3e-08  4e-07  0.7393  6e-02   2  1  1 |  0  0
14  -8.273e+00  -8.273e+00  +2e-05  2e-09  7e-11  7e-09  1e-07  0.8629  1e-01   2  1  1 |  0  0
15  -8.273e+00  -8.273e+00  +5e-06  6e-10  2e-11  2e-09  2e-08  0.7888  4e-02   1  1  1 |  0  0
16  -8.273e+00  -8.273e+00  +9e-07  1e-10  3e-12  3e-10  5e-09  0.9040  1e-01   1  1  1 |  0  0
17  -8.273e+00  -8.273e+00  +2e-07  2e-11  7e-13  6e-11  9e-10  0.8232  2e-02   2  1  1 |  0  0
18  -8.273e+00  -8.273e+00  +3e-08  3e-12  9e-14  9e-12  1e-10  0.9372  9e-02   1  1  1 |  0  0

OPTIMAL (within feastol=3.0e-12, reltol=3.1e-09, abstol=2.6e-08).
Runtime: 0.008768 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.430e+00  -1.137e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.606e+00  -3.425e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.4048  3e-01   1  1  1 |  0  0
 2  +9.138e-01  -5.154e+00  +1e+02  3e-02  1e-03  4e-01  6e-01  0.7776  9e-02   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.063e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.386e-03
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.063e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.006e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.010e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.116e-04
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.010e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.090e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.018e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.534e-05
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.018e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.010e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.058e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.553e-06
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.058e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.039e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.035e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.398e-07
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.035e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.092e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 9.782e-03 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.274e-08
(CVXPY) Jun 21 07:40:15 PM: Compilation took 9.782e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.082e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.022e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.183e-09
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.022e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.097e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.014e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.783e+00  -1.202e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.099e+00  -2.670e+01  +4e+02  1e-01  5e-03  7e-01  2e+00  0.5292  2e-01   1  2  1 |  0  0
 2  +5.158e-01  -6.455e+00  +1e+02  3e-02  8e-04  2e-01  7e-01  0.6947  5e-02   2  1  2 |  0  0
 3  -4.806e-02  -1.786e+00  +4e+01  7e-03  2e-04  4e-02  2e-01  0.7360  4e-02   2  2  2 |  0  0
 4  -1.032e-01  -1.507e+00  +3e+01  6e-03  1e-04  3e-02  2e-01  0.4599  6e-01   2  2  2 |  0  0
 5  -1.821e-02  -3.238e-01  +7e+00  1e-03  2e-05  5e-03  4e-02  0.8312  7e-02   2  2  2 |  0  0
 6  -1.993e-02  -1.533e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.7100  2e-01   1  2  2 |  0  0
 7  -1.000e-02  -5.472e-02  +1e+00  2e-04  3e-06  5e-04  5e-03  0.8063  2e-01   1  2  2 |  0  0
 8  -6.139e-03  -2.289e-02  +4e-01  6e-05  1e-06  2e-04  2e-03  0.7331  1e-01   1  2  2 |  0  0
 9  -4.136e-03  -1.055e-02  +2e-01  2e-05  5e-07  5e-05  8e-04  0.9563  4e-01   1  2  2 |  0  0
10  -3.557e-03  -4.691e-03  +3e-02  4e-06  8e-08  8e-06  1e-04  0.8888  7e-02   1  2  2 |  0  0
11  -3.446e-03  -3.904e-03  +1e-02  2e-06  3e-08  3e-06  5e-05  0.7613  2e-01   1  1  1 |  0  0
12  -3.413e-03  -3.601e-03  +5e-03  6e-07  1e-08  1e-06  2e-05  0.7845  2e-01   1  1  1 |  0  0
13  -3.393e-03  -3.447e-03  +1e-03  2e-07  4e-09  4e-07  6e-06  0.8855  2e-01   2  1  1 |  0  0
14  -3.387e-03  -3.395e-03  +2e-04  3e-08  5e-10  5e-08  9e-07  0.8790  2e-02   2  1  1 |  0  0
15  -3.386e-03  -3.389e-03  +5e-05  7e-09  2e-10  1e-08  3e-07  0.9237  2e-01   2  1  1 |  0  0
16  -3.386e-03  -3.387e-03  +2e-05  3e-09  6e-11  6e-09  1e-07  0.7584  2e-01   1  1  1 |  0  0
17  -3.386e-03  -3.386e-03  +6e-06  8e-10  2e-11  2e-09  3e-08  0.9175  2e-01   1  1  1 |  0  0
18  -3.386e-03  -3.386e-03  +7e-07  1e-10  2e-12  2e-10  3e-09  0.9890  1e-01   2  1  1 |  0  0
19  -3.386e-03  -3.386e-03  +4e-08  5e-12  1e-13  1e-11  2e-10  0.9554  1e-02   2  1  1 |  0  0
20  -3.386e-03  -3.386e-03  +9e-09  1e-12  3e-14  3e-12  4e-11  0.7805  2e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=2.7e-06, abstol=9.1e-09).
Runtime: 0.010027 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.812e+00  -1.217e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.564e+00  -2.625e+01  +4e+02  1e-01  4e-03  7e-01  2e+00  0.5503  2e-01   1  2  1 |  0  0
 2  +3.218e-01  -6.494e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.6960  5e-02   2  2  2 |  0  0
 3  -8.541e-02  -1.793e+00  +4e+01  7e-03  1e-04  4e-02  2e-01  0.7368  4e-02   2  2  2 |  0  0
 4  -1.317e-01  -1.505e+00  +3e+01  5e-03  1e-04  3e-02  2e-01  0.4469  6e-01   2  2  2 |  0  0
 5  -2.045e-02  -2.959e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.8538  7e-02   2  2  2 |  0  0
 6  -2.057e-02  -1.311e-01  +3e+00  4e-04  7e-06  1e-03  1e-02  0.7971  3e-01   1  2  2 |  0  0
 7  -1.728e-02  -1.118e-01  +2e+00  3e-04  6e-06  1e-03  1e-02  0.3160  5e-01   1  2  2 |  0  0
 8  -1.167e-02  -7.116e-02  +1e+00  2e-04  4e-06  6e-04  7e-03  0.5697  4e-01   1  2  1 |  0  0
 9  -2.288e-03  -1.213e-02  +2e-01  3e-05  6e-07  8e-05  1e-03  0.9438  1e-01   1  2  2 |  0  0
10  -1.161e-03  -4.098e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.9832  3e-01   1  2  2 |  0  0
11  -8.275e-04  -2.225e-03  +3e-02  5e-06  9e-08  1e-05  2e-04  0.7494  3e-01   2  2  2 |  0  0
12  -6.724e-04  -9.955e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.9019  1e-01   1  1  1 |  0  0
13  -6.231e-04  -6.945e-04  +2e-03  2e-07  5e-09  5e-07  8e-06  0.9358  2e-01   1  1  2 |  0  0
14  -6.140e-04  -6.275e-04  +3e-04  5e-08  9e-10  9e-08  2e-06  0.8663  6e-02   2  1  1 |  0  0
15  -6.123e-04  -6.161e-04  +9e-05  1e-08  2e-10  3e-08  4e-07  0.8586  2e-01   2  1  1 |  0  0
16  -6.118e-04  -6.129e-04  +3e-05  4e-09  7e-11  8e-09  1e-07  0.8381  2e-01   2  1  1 |  0  0
17  -6.116e-04  -6.117e-04  +3e-06  4e-10  7e-12  8e-10  1e-08  0.9169  2e-02   2  1  1 |  0  0
18  -6.116e-04  -6.116e-04  +4e-07  6e-11  1e-12  1e-10  2e-09  0.8861  3e-02   1  1  1 |  0  0
19  -6.116e-04  -6.116e-04  +1e-07  2e-11  4e-13  4e-11  7e-10  0.8252  2e-01   1  1  1 |  0  0
20  -6.116e-04  -6.116e-04  +6e-08  8e-12  2e-13  2e-11  3e-10  0.7552  2e-01   1  1  1 |  0  0
21  -6.116e-04  -6.116e-04  +2e-08  3e-12  6e-14  6e-12  1e-10  0.8752  3e-01   2  1  1 |  0  0
22  -6.116e-04  -6.116e-04  +2e-09  3e-13  1e-14  6e-13  1e-11  0.9762  8e-02   1  1  1 |  0  0

OPTIMAL (within feastol=2.9e-13, reltol=3.3e-06, abstol=2.0e-09).
Runtime: 0.010870 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.836e+00  -1.224e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.324e+00  -2.630e+01  +4e+02  1e-01  4e-03  7e-01  2e+00  0.5562  2e-01   1  2  1 |  0  0
 2  +2.371e-01  -6.505e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.6987  5e-02   2  2  2 |  0  0
 3  -9.900e-02  -1.799e+00  +4e+01  7e-03  1e-04  4e-02  2e-01  0.7358  4e-02   2  2  2 |  0  0
 4  -1.428e-01  -1.507e+00  +3e+01  5e-03  1e-04  3e-02  2e-01  0.4441  6e-01   2  2  2 |  0  0
 5  -2.150e-02  -2.819e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.8673  8e-02   2  2  2 |  0  0
 6  -1.992e-02  -1.279e-01  +3e+00  4e-04  7e-06  1e-03  1e-02  0.7901  3e-01   1  2  2 |  0  0
 7  -8.578e-03  -4.834e-02  +9e-01  1e-04  2e-06  4e-04  5e-03  0.7264  1e-01   1  2  2 |  0  0
 8  -2.471e-03  -1.711e-02  +3e-01  5e-05  9e-07  1e-04  2e-03  0.9205  3e-01   1  2  2 |  0  0
 9  -6.041e-04  -3.388e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8740  7e-02   1  2  2 |  0  0
10  -2.024e-04  -9.733e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.9146  2e-01   1  2  2 |  0  0
11  -1.293e-04  -4.491e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.7157  2e-01   1  1  1 |  0  0
12  -9.031e-05  -2.384e-04  +4e-03  5e-07  9e-09  1e-06  2e-05  0.8942  4e-01   1  2  2 |  0  0
13  -6.948e-05  -9.089e-05  +5e-04  7e-08  1e-09  1e-07  2e-06  0.9232  7e-02   2  1  1 |  0  0
14  -6.617e-05  -7.045e-05  +1e-04  1e-08  3e-10  3e-08  5e-07  0.9890  2e-01   2  1  1 |  0  0
15  -6.544e-05  -6.592e-05  +1e-05  2e-09  3e-11  3e-09  6e-08  0.9128  3e-02   2  1  1 |  0  0
16  -6.536e-05  -6.542e-05  +2e-06  2e-10  4e-12  5e-10  8e-09  0.8876  3e-02   1  1  1 |  0  0
17  -6.535e-05  -6.537e-05  +6e-07  8e-11  2e-12  2e-10  3e-09  0.7405  1e-01   1  1  1 |  0  0
18  -6.535e-05  -6.535e-05  +2e-07  3e-11  6e-13  6e-11  1e-09  0.8122  2e-01   1  1  1 |  0  0
19  -6.534e-05  -6.535e-05  +5e-08  7e-12  1e-13  1e-11  2e-10  0.9580  2e-01   1  1  1 |  0  0
20  -6.534e-05  -6.534e-05  +3e-09  4e-13  8e-15  8e-13  1e-11  0.9890  5e-02   2  1  1 |  0  0

OPTIMAL (within feastol=4.2e-13, reltol=4.4e-05, abstol=2.8e-09).
Runtime: 0.010071 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.843e+00  -1.226e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.250e+00  -2.631e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5582  2e-01   1  2  1 |  0  0
 2  +2.106e-01  -6.503e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.6997  5e-02   2  2  2 |  0  0
 3  -1.029e-01  -1.799e+00  +4e+01  7e-03  1e-04  4e-02  2e-01  0.7356  4e-02   2  2  2 |  0  0
 4  -1.459e-01  -1.506e+00  +3e+01  5e-03  1e-04  2e-02  1e-01  0.4432  6e-01   2  2  2 |  0  0
 5  -2.239e-02  -2.827e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.8676  8e-02   2  2  2 |  0  0
 6  -2.001e-02  -1.283e-01  +3e+00  4e-04  7e-06  1e-03  1e-02  0.7825  3e-01   1  2  2 |  0  0
 7  -8.748e-03  -4.904e-02  +1e+00  1e-04  3e-06  4e-04  5e-03  0.7120  1e-01   1  2  2 |  0  0
 8  -2.506e-03  -1.737e-02  +4e-01  5e-05  9e-07  1e-04  2e-03  0.9247  3e-01   1  2  2 |  0  0
 9  -5.790e-04  -3.494e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8657  7e-02   1  2  2 |  0  0
10  -1.456e-04  -9.004e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.8863  2e-01   1  2  2 |  0  0
11  -7.488e-05  -4.141e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.7060  2e-01   1  1  1 |  0  0
12  -3.639e-05  -2.070e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.8406  4e-01   2  2  2 |  0  0
13  -1.174e-05  -3.694e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9436  1e-01   1  1  1 |  0  0
14  -7.605e-06  -1.278e-05  +1e-04  2e-08  3e-10  4e-08  6e-07  0.8655  8e-02   2  1  1 |  0  0
15  -6.799e-06  -8.056e-06  +3e-05  4e-09  8e-11  9e-09  1e-07  0.8553  1e-01   1  1  1 |  0  0
16  -6.630e-06  -7.016e-06  +9e-06  1e-09  2e-11  3e-09  4e-08  0.8324  2e-01   2  1  1 |  0  0
17  -6.565e-06  -6.625e-06  +1e-06  2e-10  4e-12  4e-10  7e-09  0.8533  1e-02   2  1  1 |  0  0
18  -6.555e-06  -6.562e-06  +2e-07  3e-11  5e-13  5e-11  9e-10  0.9102  4e-02   2  1  1 |  0  0
19  -6.554e-06  -6.556e-06  +6e-08  9e-12  2e-13  2e-11  3e-10  0.7864  2e-01   2  1  1 |  0  0
20  -6.553e-06  -6.554e-06  +2e-08  3e-12  6e-14  7e-12  1e-10  0.7907  2e-01   1  1  1 |  0  0
21  -6.553e-06  -6.553e-06  +7e-09  1e-12  2e-14  2e-12  3e-11  0.9264  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.0e-12, reltol=1.0e-03, abstol=6.9e-09).
Runtime: 0.010355 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.845e+00  -1.226e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.228e+00  -2.631e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5587  2e-01   2  2  1 |  0  0
 2  +2.026e-01  -6.503e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.7000  5e-02   2  2  2 |  0  0
 3  -1.040e-01  -1.799e+00  +4e+01  7e-03  1e-04  4e-02  2e-01  0.7356  4e-02   2  2  2 |  0  0
 4  -1.468e-01  -1.506e+00  +3e+01  5e-03  1e-04  2e-02  1e-01  0.4429  6e-01   2  2  2 |  0  0
 5  -2.271e-02  -2.834e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.8674  8e-02   2  2  2 |  0  0
 6  -2.008e-02  -1.285e-01  +3e+00  4e-04  7e-06  1e-03  1e-02  0.7797  3e-01   1  2  2 |  0  0
 7  -8.827e-03  -4.933e-02  +1e+00  1e-04  3e-06  4e-04  5e-03  0.7096  1e-01   1  2  2 |  0  0
 8  -2.522e-03  -1.743e-02  +4e-01  5e-05  9e-07  1e-04  2e-03  0.9267  3e-01   1  2  2 |  0  0
 9  -5.793e-04  -3.513e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8648  7e-02   1  2  2 |  0  0
10  -1.405e-04  -8.949e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.8838  2e-01   1  2  2 |  0  0
11  -6.943e-05  -4.098e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.7080  2e-01   2  1  1 |  0  0
12  -3.092e-05  -2.028e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.8357  4e-01   2  2  2 |  0  0
13  -6.072e-06  -3.238e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9394  1e-01   1  1  1 |  0  0
14  -1.602e-06  -6.292e-06  +1e-04  2e-08  3e-10  3e-08  5e-07  0.8646  5e-02   2  1  1 |  0  0
15  -8.724e-07  -2.053e-06  +3e-05  4e-09  7e-11  8e-09  1e-07  0.8460  1e-01   1  1  1 |  0  0
16  -7.335e-07  -1.202e-06  +1e-05  2e-09  3e-11  3e-09  5e-08  0.7642  2e-01   2  1  1 |  0  0
17  -6.528e-07  -7.194e-07  +2e-06  2e-10  4e-12  5e-10  8e-09  0.8663  1e-02   2  1  1 |  0  0
18  -6.413e-07  -6.486e-07  +2e-07  3e-11  5e-13  5e-11  9e-10  0.9178  3e-02   2  1  1 |  0  0
19  -6.403e-07  -6.426e-07  +5e-08  8e-12  1e-13  2e-11  3e-10  0.8451  2e-01   2  1  1 |  0  0
20  -6.400e-07  -6.410e-07  +2e-08  3e-12  6e-14  6e-12  1e-10  0.7343  2e-01   2  1  1 |  0  0
21  -6.399e-07  -6.403e-07  +8e-09  1e-12  2e-14  2e-12  4e-11  0.8730  3e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.2e-12, reltol=1.3e-02, abstol=8.4e-09).
Runtime: 0.010887 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.845e+00  -1.227e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.221e+00  -2.631e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5589  2e-01   2  2  1 |  0  0
 2  +2.002e-01  -6.502e+00  +1e+02  3e-02  7e-04  2e-01  6e-01  0.7001  5e-02   2  2  2 |  0  0
 3  -1.044e-01  -1.799e+00  +4e+01  7e-03  1e-04  4e-02  2e-01  0.7355  4e-02   2  2  2 |  0  0
 4  -1.471e-01  -1.506e+00  +3e+01  5e-03  1e-04  2e-02  1e-01  0.4428  6e-01   2  2  2 |  0  0
 5  -2.281e-02  -2.836e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.8673  8e-02   2  2  2 |  0  0
 6  -2.010e-02  -1.286e-01  +3e+00  4e-04  7e-06  1e-03  1e-02  0.7789  3e-01   1  2  2 |  0  0
 7  -8.851e-03  -4.942e-02  +1e+00  1e-04  3e-06  4e-04  5e-03  0.7088  1e-01   1  2  2 |  0  0
 8  -2.528e-03  -1.744e-02  +4e-01  5e-05  9e-07  1e-04  2e-03  0.9272  3e-01   1  2  2 |  0  0
 9  -5.807e-04  -3.521e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8644  7e-02   1  2  2 |  0  0
10  -1.401e-04  -8.941e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.8830  2e-01   1  2  2 |  0  0
11  -6.896e-05  -4.095e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.7089  2e-01   1  1  1 |  0  0
12  -3.047e-05  -2.027e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.8340  4e-01   2  2  2 |  0  0
13  -5.580e-06  -3.228e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9379  1e-01   2  1  1 |  0  0
14  -1.000e-06  -5.562e-06  +1e-04  2e-08  3e-10  3e-08  5e-07  0.8662  4e-02   2  1  1 |  0  0
15  -2.925e-07  -1.456e-06  +3e-05  4e-09  7e-11  8e-09  1e-07  0.8441  1e-01   2  1  1 |  0  0
16  -1.602e-07  -6.459e-07  +1e-05  2e-09  3e-11  3e-09  6e-08  0.7461  2e-01   2  1  1 |  0  0
17  -7.517e-08  -1.388e-07  +2e-06  2e-10  4e-12  4e-10  7e-09  0.8764  9e-03   1  1  1 |  0  0
18  -6.422e-08  -7.144e-08  +2e-07  2e-11  5e-13  5e-11  8e-10  0.9132  3e-02   1  1  1 |  0  0
19  -6.327e-08  -6.564e-08  +6e-08  8e-12  2e-13  2e-11  3e-10  0.8318  2e-01   1  1  1 |  0  0
20  -6.299e-08  -6.393e-08  +2e-08  3e-12  6e-14  7e-12  1e-10  0.7408  2e-01   2  1  1 |  0  0
21  -6.287e-08  -6.323e-08  +9e-09  1e-12  2e-14  3e-12  4e-11  0.8763  3e-01   1  1  1 |  0  0

OPTIMAL (within feastol=1.2e-12, reltol=1.4e-01, abstol=8.5e-09).
Runtime: 0.010669 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS


(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.114e-10
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.014e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.156e-02 seconds
Reranking users:   0%|          | 6/2064 [00:02<10:43,  3.20it/s](CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.072e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 7.568e+00
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.072e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.178e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.066e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.327e-01
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.066e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.476e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.059e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 4.567e-02
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.059e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.091e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.068e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 9.575e-03
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.068e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.355e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.040e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 1.811e-03
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.040e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.749e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.023e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.931e-04
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.023e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.604e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.033e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 7.761e-05
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.033e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.891e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS

 7  -8.860e-03  -4.945e-02  +1e+00  1e-04  3e-06  4e-04  5e-03  0.7085  1e-01   1  2  2 |  0  0
 8  -2.530e-03  -1.745e-02  +4e-01  5e-05  9e-07  1e-04  2e-03  0.9274  3e-01   1  2  2 |  0  0
 9  -5.814e-04  -3.524e-03  +7e-02  1e-05  2e-07  2e-05  3e-04  0.8643  7e-02   1  2  2 |  0  0
10  -1.401e-04  -8.939e-04  +2e-02  3e-06  5e-08  5e-06  9e-05  0.8828  2e-01   1  2  2 |  0  0
11  -6.894e-05  -4.095e-04  +8e-03  1e-06  2e-08  2e-06  4e-05  0.7093  2e-01   1  1  1 |  0  0
12  -3.045e-05  -2.028e-04  +4e-03  6e-07  1e-08  1e-06  2e-05  0.8333  4e-01   2  2  2 |  0  0
13  -5.550e-06  -3.239e-05  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9373  1e-01   2  1  1 |  0  0
14  -9.292e-07  -5.445e-06  +1e-04  2e-08  3e-10  3e-08  5e-07  0.8670  4e-02   2  1  1 |  0  0
15  -2.296e-07  -1.388e-06  +3e-05  4e-09  7e-11  8e-09  1e-07  0.8433  1e-01   1  1  1 |  0  0
16  -9.953e-08  -5.922e-07  +1e-05  2e-09  3e-11  3e-09  6e-08  0.7394  2e-01   2  1  1 |  0  0
17  -1.269e-08  -7.452e-08  +1e-06  2e-10  4e-12  4e-10  7e-09  0.8814  8e-03   2  1  1 |  0  0
18  -2.089e-09  -9.286e-09  +2e-07  2e-11  5e-13  5e-11  8e-10  0.9101  3e-02   2  1  1 |  0  0
19  -1.149e-09  -3.595e-09  +6e-08  8e-12  2e-13  2e-11  3e-10  0.8200  2e-01   2  1  1 |  0  0
20  -8.688e-10  -1.823e-09  +2e-08  3e-12  6e-14  7e-12  1e-10  0.7474  2e-01   2  1  1 |  0  0
21  -7.451e-10  -1.103e-09  +8e-09  1e-12  2e-14  2e-12  4e-11  0.8818  3e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.2e-12, reltol=1.1e+01, abstol=8.5e-09).
Runtime: 0.011521 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.346e+01  -1.519e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +1.630e+00  -7.445e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2546  4e-01   1  2  2 |  0  0
 2  -3.325e+00  -1.546e+01  +2e+02  5e-02  1e-03  5e-01  1e+00  0.7619  1e-01   1  1  1 |  0  0
 3  -6.343e+00  -1.083e+01  +1e+02  2e-02  5e-04  2e-01  5e-01  0.6767  1e-01   2  2  2 |  0  0
 4  -7.279e+00  -8.495e+00  +3e+01  4e-03  1e-04  4e-02  1e-01  0.7427  4e-02   1  2  2 |  0  0
 5  -7.502e+00  -7.855e+00  +8e+00  1e-03  3e-05  1e-02  4e-02  0.7416  5e-02   1  2  2 |  0  0
 6  -7.529e+00  -7.750e+00  +5e+00  7e-04  2e-05  5e-03  3e-02  0.5823  4e-01   1  1  1 |  0  0
 7  -7.559e+00  -7.612e+00  +1e+00  2e-04  4e-06  1e-03  6e-03  0.7856  3e-02   1  1  1 |  0  0
 8  -7.564e+00  -7.589e+00  +6e-01  8e-05  2e-06  4e-04  3e-03  0.6358  2e-01   1  1  1 |  0  0
 9  -7.567e+00  -7.574e+00  +2e-01  2e-05  6e-07  1e-04  8e-04  0.7730  8e-02   1  1  1 |  0  0
10  -7.568e+00  -7.570e+00  +4e-02  5e-06  1e-07  2e-05  2e-04  0.8630  1e-01   1  1  1 |  0  0
11  -7.568e+00  -7.569e+00  +9e-03  1e-06  3e-08  5e-06  5e-05  0.8074  4e-02   1  1  1 |  0  0
12  -7.568e+00  -7.568e+00  +1e-03  1e-07  3e-09  4e-07  5e-06  0.9527  6e-02   2  1  1 |  0  0
13  -7.568e+00  -7.568e+00  +1e-04  2e-08  5e-10  5e-08  7e-07  0.8717  1e-02   2  1  1 |  0  0
14  -7.568e+00  -7.568e+00  +2e-05  3e-09  7e-11  8e-09  1e-07  0.8883  5e-02   2  1  1 |  0  0
15  -7.568e+00  -7.568e+00  +4e-06  5e-10  1e-11  1e-09  2e-08  0.9890  2e-01   1  1  1 |  0  0
16  -7.568e+00  -7.568e+00  +5e-08  6e-12  2e-13  2e-11  2e-10  0.9875  1e-04   2  1  1 |  0  0

OPTIMAL (within feastol=6.0e-12, reltol=6.4e-09, abstol=4.8e-08).
Runtime: 0.008135 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.658e+00  -1.068e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.143e+00  -3.753e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3715  4e-01   1  1  1 |  0  0
 2  +6.555e-01  -3.853e+00  +1e+02  2e-02  2e-03  1e+00  6e-01  0.8499  1e-01   1  1  1 |  0  0
 3  +6.624e-02  -1.638e+00  +5e+01  8e-03  7e-04  3e-01  3e-01  0.6636  1e-01   1  1  1 |  0  0
 4  -1.447e-01  -8.307e-01  +2e+01  3e-03  3e-04  1e-01  1e-01  0.6818  1e-01   1  2  2 |  0  0
 5  -1.898e-01  -4.484e-01  +8e+00  1e-03  8e-05  3e-02  4e-02  0.6975  1e-01   1  2  2 |  0  0
 6  -2.178e-01  -3.551e-01  +4e+00  5e-04  4e-05  1e-03  2e-02  0.9890  5e-01   1  1  1 |  0  0
 7  -2.249e-01  -2.680e-01  +1e+00  1e-04  1e-05  4e-04  6e-03  0.7373  7e-02   1  1  1 |  0  0
 8  -2.286e-01  -2.499e-01  +6e-01  7e-05  6e-06  1e-04  3e-03  0.9890  5e-01   1  1  1 |  0  0
 9  -2.310e-01  -2.374e-01  +2e-01  2e-05  2e-06  4e-05  9e-04  0.8696  2e-01   1  1  1 |  0  0
10  -2.324e-01  -2.336e-01  +3e-02  4e-06  3e-07  6e-06  2e-04  0.8769  6e-02   1  1  1 |  0  0
11  -2.326e-01  -2.329e-01  +8e-03  8e-07  7e-08  1e-06  4e-05  0.9092  2e-01   2  1  1 |  0  0
12  -2.327e-01  -2.328e-01  +1e-03  1e-07  1e-08  3e-07  7e-06  0.9890  2e-01   2  1  1 |  0  0
13  -2.327e-01  -2.327e-01  +4e-05  5e-09  4e-10  8e-09  2e-07  0.9713  4e-03   2  1  1 |  0  0
14  -2.327e-01  -2.327e-01  +2e-06  2e-10  2e-11  3e-10  9e-09  0.9592  9e-04   2  1  1 |  0  0
15  -2.327e-01  -2.327e-01  +2e-07  2e-11  2e-12  4e-11  1e-09  0.8838  5e-03   1  1  1 |  0  0
16  -2.327e-01  -2.327e-01  +1e-08  1e-12  1e-13  2e-12  5e-11  0.9642  1e-02   2  1  1 |  0  0
17  -2.327e-01  -2.327e-01  +3e-10  2e-13  2e-14  6e-14  2e-12  0.9696  2e-04   2  1  1 |  0  0

OPTIMAL (within feastol=1.7e-13, reltol=1.4e-09, abstol=3.3e-10).
Runtime: 0.008430 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.708e+00  -1.066e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.950e+00  -3.591e+01  +5e+02  2e-01  1e-02  2e+00  2e+00  0.3600  4e-01   1  1  1 |  0  0
 2  +8.451e-01  -2.532e+00  +9e+01  2e-02  1e-03  6e-01  5e-01  0.9078  1e-01   1  1  1 |  0  0
 3  +2.000e-01  -9.070e-01  +3e+01  5e-03  3e-04  2e-01  2e-01  0.6763  6e-02   1  2  2 |  0  0
 4  +1.383e-02  -4.933e-01  +1e+01  2e-03  1e-04  6e-02  8e-02  0.6768  2e-01   1  2  2 |  0  0
 5  -2.875e-02  -4.028e-01  +1e+01  2e-03  8e-05  2e-02  5e-02  0.6259  5e-01   1  2  1 |  0  0
 6  -3.803e-02  -2.676e-01  +7e+00  9e-04  5e-05  4e-03  3e-02  0.8572  5e-01   1  1  2 |  0  0
 7  -4.214e-02  -1.067e-01  +2e+00  2e-04  1e-05  9e-04  9e-03  0.8311  1e-01   1  1  1 |  0  0
 8  -4.328e-02  -6.439e-02  +6e-01  8e-05  4e-06  2e-04  3e-03  0.7689  1e-01   1  1  1 |  0  0
 9  -4.470e-02  -5.335e-02  +3e-01  3e-05  2e-06  5e-05  1e-03  0.9890  4e-01   1  1  1 |  0  0
10  -4.535e-02  -4.768e-02  +7e-02  8e-06  4e-07  1e-05  3e-04  0.8256  1e-01   1  1  1 |  0  0
11  -4.559e-02  -4.617e-02  +2e-02  2e-06  1e-07  3e-06  8e-05  0.8196  9e-02   1  1  1 |  0  0
12  -4.562e-02  -4.588e-02  +7e-03  9e-07  5e-08  1e-06  4e-05  0.8576  3e-01   1  1  1 |  0  0
13  -4.566e-02  -4.569e-02  +8e-04  9e-08  5e-09  1e-07  4e-06  0.9293  3e-02   1  1  1 |  0  0
14  -4.567e-02  -4.567e-02  +7e-05  8e-09  5e-10  1e-08  3e-07  0.9445  4e-02   2  1  1 |  0  0
15  -4.567e-02  -4.567e-02  +3e-06  3e-10  2e-11  5e-10  1e-08  0.9647  2e-03   1  1  1 |  0  0
16  -4.567e-02  -4.567e-02  +1e-07  2e-11  9e-13  3e-11  6e-10  0.9511  2e-03   2  1  1 |  0  0
17  -4.567e-02  -4.567e-02  +2e-08  3e-12  2e-13  4e-12  1e-10  0.8527  3e-02   2  1  1 |  0  0
18  -4.567e-02  -4.567e-02  +3e-09  6e-13  6e-14  6e-13  2e-11  0.9052  5e-02   2  1  1 |  0  0

OPTIMAL (within feastol=6.0e-13, reltol=7.1e-08, abstol=3.3e-09).
Runtime: 0.010857 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.864e+00  -1.086e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.576e+00  -3.243e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.3949  3e-01   1  1  1 |  0  0
 2  +6.934e-01  -2.837e+00  +9e+01  2e-02  9e-04  3e-01  4e-01  0.8835  9e-02   1  1  1 |  0  0
 3  +1.360e-01  -1.418e+00  +4e+01  7e-03  3e-04  1e-01  2e-01  0.6224  2e-01   1  2  2 |  0  0
 4  +4.128e-02  -5.304e-01  +2e+01  2e-03  1e-04  4e-02  8e-02  0.6593  7e-02   1  2  2 |  0  0
 5  +1.405e-03  -4.457e-01  +1e+01  2e-03  8e-05  2e-02  6e-02  0.4790  5e-01   1  2  1 |  0  0
 6  -1.367e-02  -2.905e-01  +8e+00  1e-03  4e-05  5e-03  4e-02  0.8419  5e-01   1  2  2 |  0  0
 7  -1.077e-02  -8.280e-02  +2e+00  3e-04  1e-05  9e-04  1e-02  0.8789  2e-01   1  1  1 |  0  0
 8  -8.802e-03  -3.299e-02  +7e-01  9e-05  4e-06  2e-04  3e-03  0.8011  2e-01   1  1  1 |  0  0
 9  -9.603e-03  -2.115e-02  +3e-01  4e-05  2e-06  7e-05  2e-03  0.9890  5e-01   1  1  1 |  0  0
10  -9.401e-03  -1.170e-02  +7e-02  8e-06  3e-07  1e-05  3e-04  0.8909  1e-01   1  1  1 |  0  0
11  -9.557e-03  -1.018e-02  +2e-02  2e-06  9e-08  4e-06  9e-05  0.8373  1e-01   1  1  1 |  0  0
12  -9.563e-03  -9.756e-03  +6e-03  7e-07  3e-08  1e-06  3e-05  0.8893  2e-01   1  1  1 |  0  0
13  -9.575e-03  -9.595e-03  +6e-04  7e-08  3e-09  1e-07  3e-06  0.9169  2e-02   2  1  1 |  0  0
14  -9.575e-03  -9.580e-03  +1e-04  2e-08  7e-10  3e-08  6e-07  0.8339  7e-02   1  1  1 |  0  0
15  -9.575e-03  -9.577e-03  +4e-05  5e-09  2e-10  9e-09  2e-07  0.8000  1e-01   1  1  1 |  0  0
16  -9.575e-03  -9.576e-03  +1e-05  1e-09  6e-11  2e-09  5e-08  0.8750  2e-01   2  1  1 |  0  0
17  -9.575e-03  -9.575e-03  +1e-06  1e-10  6e-12  2e-10  6e-09  0.9382  5e-02   2  1  1 |  0  0
18  -9.575e-03  -9.575e-03  +5e-08  6e-12  3e-13  9e-12  2e-10  0.9643  3e-03   2  1  1 |  0  0
19  -9.575e-03  -9.575e-03  +3e-09  4e-13  2e-14  7e-13  2e-11  0.9364  7e-03   2  1  1 |  0  0

OPTIMAL (within feastol=4.0e-13, reltol=3.3e-07, abstol=3.2e-09).
Runtime: 0.009310 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.918e+00  -1.096e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.676e+00  -3.173e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.4045  3e-01   1  1  1 |  0  0
 2  +6.262e-01  -2.913e+00  +9e+01  2e-02  8e-04  3e-01  4e-01  0.8792  8e-02   1  1  1 |  0  0
 3  +1.371e-01  -1.665e+00  +5e+01  8e-03  3e-04  1e-01  2e-01  0.5692  2e-01   1  2  2 |  0  0
 4  +5.695e-02  -5.735e-01  +2e+01  3e-03  1e-04  4e-02  9e-02  0.6583  5e-02   1  2  2 |  0  0
 5  +7.440e-03  -5.050e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.4565  6e-01   1  2  1 |  0  0
 6  -1.316e-02  -3.295e-01  +9e+00  1e-03  4e-05  5e-03  4e-02  0.8655  5e-01   1  2  2 |  0  0
 7  -4.722e-03  -8.286e-02  +2e+00  3e-04  1e-05  9e-04  1e-02  0.8616  1e-01   1  1  1 |  0  0
 8  -1.876e-03  -3.202e-02  +8e-01  1e-04  4e-06  3e-04  4e-03  0.8084  2e-01   1  1  1 |  0  0
 9  -2.180e-03  -1.889e-02  +5e-01  6e-05  2e-06  1e-04  2e-03  0.6401  3e-01   1  1  1 |  0  0
10  -1.570e-03  -1.088e-02  +3e-01  3e-05  1e-06  6e-05  1e-03  0.8624  5e-01   1  1  1 |  0  0
11  -1.823e-03  -5.093e-03  +9e-02  1e-05  4e-07  2e-05  5e-04  0.8451  2e-01   1  1  1 |  0  0
12  -1.801e-03  -2.504e-03  +2e-02  2e-06  9e-08  4e-06  1e-04  0.8873  1e-01   1  1  1 |  0  0
13  -1.808e-03  -2.013e-03  +6e-03  7e-07  3e-08  1e-06  3e-05  0.9890  3e-01   2  1  1 |  0  0
14  -1.811e-03  -1.836e-03  +7e-04  9e-08  3e-09  2e-07  3e-06  0.9000  3e-02   1  1  1 |  0  0
15  -1.811e-03  -1.815e-03  +1e-04  2e-08  6e-10  3e-08  6e-07  0.8746  6e-02   2  1  1 |  0  0
16  -1.811e-03  -1.811e-03  +1e-05  2e-09  6e-11  3e-09  6e-08  0.9619  6e-02   2  1  1 |  0  0
17  -1.811e-03  -1.811e-03  +1e-06  2e-10  7e-12  3e-10  7e-09  0.8888  3e-03   1  1  1 |  0  0
18  -1.811e-03  -1.811e-03  +2e-07  3e-11  1e-12  5e-11  1e-09  0.9470  1e-01   2  1  1 |  0  0
19  -1.811e-03  -1.811e-03  +2e-08  3e-12  1e-13  5e-12  1e-10  0.8913  3e-03   2  1  1 |  0  0
20  -1.811e-03  -1.811e-03  +3e-09  4e-13  2e-14  7e-13  2e-11  0.9526  9e-02   2  1  1 |  0  0

OPTIMAL (within feastol=4.2e-13, reltol=1.8e-06, abstol=3.3e-09).
Runtime: 0.009707 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.941e+00  -1.103e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.728e+00  -3.102e+01  +5e+02  2e-01  1e-02  1e+00  2e+00  0.4142  3e-01   1  1  1 |  0  0
 2  +5.656e-01  -2.960e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8758  8e-02   1  1  1 |  0  0
 3  +7.439e-02  -1.599e+00  +4e+01  7e-03  3e-04  9e-02  2e-01  0.6273  2e-01   2  2  2 |  0  0
 4  +4.214e-02  -5.888e-01  +2e+01  3e-03  9e-05  3e-02  9e-02  0.6368  5e-02   1  2  2 |  0  0
 5  -2.647e-03  -5.051e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.4759  6e-01   1  2  1 |  0  0
 6  -1.560e-02  -3.225e-01  +8e+00  1e-03  4e-05  4e-03  4e-02  0.8592  5e-01   1  1  2 |  0  0
 7  -4.422e-03  -8.030e-02  +2e+00  3e-04  1e-05  8e-04  1e-02  0.8665  1e-01   1  1  1 |  0  0
 8  -9.440e-04  -3.477e-02  +9e-01  1e-04  4e-06  3e-04  5e-03  0.7471  3e-01   1  1  1 |  0  0
 9  -1.068e-03  -1.969e-02  +5e-01  7e-05  2e-06  1e-04  3e-03  0.6288  3e-01   1  1  1 |  0  0
10  -2.111e-04  -8.502e-03  +2e-01  3e-05  1e-06  5e-05  1e-03  0.9890  4e-01   1  1  1 |  0  0
11  -3.966e-04  -2.055e-03  +5e-02  6e-06  2e-07  1e-05  2e-04  0.9105  1e-01   1  1  1 |  0  0
12  -3.920e-04  -8.568e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.9890  3e-01   1  1  1 |  0  0
13  -3.918e-04  -4.737e-04  +2e-03  3e-07  1e-08  5e-07  1e-05  0.8701  5e-02   2  1  1 |  0  0
14  -3.930e-04  -4.105e-04  +5e-04  6e-08  2e-09  1e-07  2e-06  0.8592  9e-02   2  1  1 |  0  0
15  -3.930e-04  -3.973e-04  +1e-04  2e-08  5e-10  3e-08  6e-07  0.8715  1e-01   2  1  1 |  0  0
16  -3.931e-04  -3.932e-04  +5e-06  6e-10  2e-11  1e-09  2e-08  0.9666  5e-03   1  1  1 |  0  0
17  -3.931e-04  -3.931e-04  +1e-07  2e-11  6e-13  3e-11  7e-10  0.9802  1e-02   2  1  1 |  0  0
18  -3.931e-04  -3.931e-04  +1e-08  2e-12  6e-14  3e-12  6e-11  0.9121  5e-04   1  1  1 |  0  0
19  -3.931e-04  -3.931e-04  +3e-09  4e-13  2e-14  8e-13  2e-11  0.7326  3e-02   2  1  1 |  0  0

OPTIMAL (within feastol=4.5e-13, reltol=8.9e-06, abstol=3.5e-09).
Runtime: 0.009560 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------

(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.071e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 1.481e-05
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.071e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.753e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.015e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.794e-06
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.015e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.212e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.153e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 5.237e-07
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.153e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.211e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.045e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 9.787e-08
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.045e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.567e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.084e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 1.830e-08
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.084e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.421e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.032e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.431e-09
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.032e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.838e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.007e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.330e-10
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.007e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.126e-03 seconds
Reranking users:   0%|          | 7/2064 [00:02<11:15,  3.05it/s](CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.062e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 7.611e+00
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.062e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 7.292e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.956e+00  -1.107e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.753e+00  -3.053e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4212  3e-01   1  1  1 |  0  0
 2  +5.235e-01  -2.984e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8740  7e-02   1  1  1 |  0  0
 3  +2.494e-03  -1.394e+00  +4e+01  6e-03  2e-04  7e-02  2e-01  0.7336  2e-01   2  2  2 |  0  0
 4  +1.109e-02  -5.678e-01  +2e+01  2e-03  8e-05  2e-02  8e-02  0.6192  8e-02   1  2  2 |  0  0
 5  -2.212e-02  -4.538e-01  +1e+01  2e-03  6e-05  1e-02  6e-02  0.5883  6e-01   1  2  1 |  0  0
 6  -1.447e-02  -2.452e-01  +6e+00  9e-04  3e-05  3e-03  3e-02  0.8922  5e-01   1  1  2 |  0  0
 7  -3.796e-03  -6.190e-02  +2e+00  2e-04  7e-06  5e-04  8e-03  0.8786  2e-01   1  1  1 |  0  0
 8  -1.998e-04  -2.417e-02  +7e-01  9e-05  3e-06  2e-04  3e-03  0.9233  4e-01   1  1  1 |  0  0
 9  -4.611e-04  -1.323e-02  +4e-01  5e-05  2e-06  8e-05  2e-03  0.6255  3e-01   1  1  1 |  0  0
10  +4.949e-05  -6.121e-03  +2e-01  2e-05  7e-07  4e-05  8e-04  0.9084  4e-01   1  1  1 |  0  0
11  -5.388e-05  -2.005e-03  +5e-02  7e-06  2e-07  1e-05  3e-04  0.8310  2e-01   1  1  1 |  0  0
12  -1.885e-05  -4.924e-04  +1e-02  2e-06  6e-08  3e-06  6e-05  0.8143  7e-02   1  1  1 |  0  0
13  -1.458e-05  -8.478e-05  +2e-03  2e-07  8e-09  4e-07  1e-05  0.9775  1e-01   2  1  1 |  0  0
14  -1.471e-05  -3.328e-05  +5e-04  7e-08  2e-09  1e-07  3e-06  0.9890  3e-01   1  1  1 |  0  0
15  -1.479e-05  -1.703e-05  +6e-05  8e-09  3e-10  1e-08  3e-07  0.8985  2e-02   2  1  1 |  0  0
16  -1.481e-05  -1.527e-05  +1e-05  2e-09  6e-11  3e-09  6e-08  0.9548  2e-01   2  1  1 |  0  0
17  -1.481e-05  -1.482e-05  +3e-07  4e-11  1e-12  7e-11  1e-09  0.9805  3e-03   2  1  1 |  0  0
18  -1.481e-05  -1.481e-05  +7e-09  9e-13  3e-14  2e-12  3e-11  0.9776  5e-04   2  1  1 |  0  0

OPTIMAL (within feastol=8.7e-13, reltol=4.6e-04, abstol=6.8e-09).
Runtime: 0.008715 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.957e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.756e+00  -3.046e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4221  3e-01   1  1  1 |  0  0
 2  +5.183e-01  -2.987e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8738  7e-02   1  1  1 |  0  0
 3  -8.705e-03  -1.355e+00  +4e+01  6e-03  2e-04  6e-02  2e-01  0.7531  2e-01   2  2  2 |  0  0
 4  +5.210e-03  -5.571e-01  +2e+01  2e-03  7e-05  2e-02  8e-02  0.6223  9e-02   1  2  2 |  0  0
 5  -2.863e-02  -4.316e-01  +1e+01  2e-03  5e-05  9e-03  5e-02  0.6852  6e-01   1  2  1 |  0  0
 6  -1.197e-02  -2.015e-01  +5e+00  7e-04  2e-05  2e-03  3e-02  0.9171  4e-01   1  1  1 |  0  0
 7  -3.209e-03  -5.188e-02  +1e+00  2e-04  6e-06  4e-04  7e-03  0.8784  2e-01   1  1  1 |  0  0
 8  -2.003e-04  -1.833e-02  +5e-01  7e-05  2e-06  1e-04  2e-03  0.9890  4e-01   1  1  1 |  0  0
 9  -1.176e-04  -4.357e-03  +1e-01  2e-05  5e-07  3e-05  6e-04  0.8641  1e-01   1  1  1 |  0  0
10  +1.716e-05  -1.465e-03  +4e-02  5e-06  2e-07  9e-06  2e-04  0.9453  3e-01   1  1  1 |  0  0
11  -9.335e-06  -6.275e-04  +2e-02  2e-06  7e-08  4e-06  8e-05  0.7562  2e-01   1  1  1 |  0  0
12  -1.657e-06  -1.034e-04  +3e-03  4e-07  1e-08  6e-07  1e-05  0.9151  9e-02   2  1  1 |  0  0
13  -2.743e-06  -2.429e-05  +6e-04  8e-08  3e-09  1e-07  3e-06  0.8479  7e-02   2  1  1 |  0  0
14  -2.843e-06  -1.162e-05  +2e-04  3e-08  1e-09  5e-08  1e-06  0.7139  2e-01   1  1  1 |  0  0
15  -2.767e-06  -6.243e-06  +1e-04  1e-08  4e-10  2e-08  5e-07  0.8017  2e-01   2  1  1 |  0  0
16  -2.794e-06  -3.023e-06  +6e-06  8e-10  3e-11  1e-09  3e-08  0.9713  4e-02   2  1  1 |  0  0
17  -2.794e-06  -2.804e-06  +3e-07  4e-11  1e-12  7e-11  1e-09  0.9539  9e-04   2  1  1 |  0  0
18  -2.794e-06  -2.794e-06  +2e-08  3e-12  9e-14  5e-12  1e-10  0.9321  3e-03   2  1  1 |  0  0
19  -2.794e-06  -2.794e-06  +3e-09  3e-13  2e-14  6e-13  1e-11  0.9568  8e-02   1  1  1 |  0  0

OPTIMAL (within feastol=3.4e-13, reltol=9.2e-04, abstol=2.6e-09).
Runtime: 0.009179 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.958e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.758e+00  -3.044e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4225  3e-01   1  1  1 |  0  0
 2  +5.162e-01  -2.988e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8737  7e-02   1  1  1 |  0  0
 3  -1.364e-02  -1.337e+00  +3e+01  6e-03  2e-04  6e-02  2e-01  0.7618  2e-01   2  2  2 |  0  0
 4  +2.604e-03  -5.514e-01  +2e+01  2e-03  7e-05  2e-02  8e-02  0.6246  9e-02   1  2  2 |  0  0
 5  -3.317e-02  -4.166e-01  +1e+01  2e-03  5e-05  7e-03  5e-02  0.7717  6e-01   1  2  1 |  0  0
 6  -1.010e-02  -1.735e-01  +5e+00  6e-04  2e-05  1e-03  2e-02  0.9211  4e-01   1  1  1 |  0  0
 7  -2.888e-03  -4.702e-02  +1e+00  2e-04  5e-06  3e-04  6e-03  0.8692  2e-01   1  1  1 |  0  0
 8  -2.438e-04  -1.424e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.9359  3e-01   1  1  1 |  0  0
 9  -2.114e-05  -7.926e-03  +2e-01  3e-05  9e-07  5e-05  1e-03  0.7552  4e-01   1  1  1 |  0  0
10  -8.813e-05  -3.500e-03  +1e-01  1e-05  4e-07  2e-05  5e-04  0.7536  2e-01   1  1  1 |  0  0
11  +1.930e-06  -8.341e-04  +2e-02  3e-06  1e-07  5e-06  1e-04  0.8827  1e-01   1  1  1 |  0  0
12  -1.815e-07  -1.807e-04  +5e-03  6e-07  2e-08  1e-06  2e-05  0.8664  9e-02   1  1  1 |  0  0
13  -5.907e-07  -2.890e-05  +8e-04  1e-07  3e-09  2e-07  4e-06  0.8770  4e-02   2  1  1 |  0  0
14  -4.815e-07  -7.755e-06  +2e-04  3e-08  9e-10  4e-08  1e-06  0.9890  2e-01   2  1  1 |  0  0
15  -5.190e-07  -1.911e-06  +4e-05  5e-09  2e-10  9e-09  2e-07  0.8485  5e-02   2  1  1 |  0  0
16  -5.182e-07  -1.143e-06  +2e-05  2e-09  7e-11  4e-09  9e-08  0.7174  2e-01   1  1  1 |  0  0
17  -5.237e-07  -5.449e-07  +6e-07  8e-11  3e-12  1e-10  3e-09  0.9745  9e-03   1  1  1 |  0  0
18  -5.237e-07  -5.245e-07  +2e-08  3e-12  1e-13  5e-12  1e-10  0.9890  3e-02   2  1  1 |  0  0
19  -5.238e-07  -5.238e-07  +1e-09  2e-13  9e-15  3e-13  7e-12  0.9313  7e-04   2  1  1 |  0  0

OPTIMAL (within feastol=2.1e-13, reltol=2.8e-03, abstol=1.5e-09).
Runtime: 0.009173 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.958e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.758e+00  -3.043e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4227  3e-01   1  1  1 |  0  0
 2  +5.153e-01  -2.988e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8736  7e-02   1  1  1 |  0  0
 3  -1.578e-02  -1.329e+00  +3e+01  6e-03  2e-04  6e-02  2e-01  0.7657  2e-01   2  2  2 |  0  0
 4  +1.473e-03  -5.487e-01  +1e+01  2e-03  7e-05  2e-02  8e-02  0.6258  1e-01   1  2  2 |  0  0
 5  -3.583e-02  -4.081e-01  +1e+01  1e-03  5e-05  6e-03  5e-02  0.8277  6e-01   1  2  1 |  0  0
 6  -9.160e-03  -1.593e-01  +4e+00  6e-04  2e-05  1e-03  2e-02  0.9172  4e-01   1  1  1 |  0  0
 7  -2.696e-03  -4.427e-02  +1e+00  2e-04  5e-06  3e-04  6e-03  0.8655  2e-01   1  1  1 |  0  0
 8  -3.444e-04  -1.393e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.8870  2e-01   1  1  1 |  0  0
 9  -1.707e-05  -6.980e-03  +2e-01  3e-05  8e-07  4e-05  1e-03  0.8103  4e-01   1  1  1 |  0  0
10  -7.255e-05  -3.023e-03  +8e-02  1e-05  3e-07  2e-05  4e-04  0.7695  3e-01   1  1  1 |  0  0
11  +2.783e-06  -6.383e-04  +2e-02  2e-06  8e-08  4e-06  9e-05  0.8909  1e-01   1  1  1 |  0  0
12  +2.145e-07  -1.222e-04  +3e-03  4e-07  1e-08  8e-07  2e-05  0.8857  9e-02   1  1  1 |  0  0
13  -9.828e-08  -2.242e-05  +6e-04  8e-08  3e-09  1e-07  3e-06  0.8874  8e-02   1  1  1 |  0  0
14  -7.467e-08  -7.363e-06  +2e-04  3e-08  9e-10  5e-08  1e-06  0.9890  3e-01   2  1  1 |  0  0
15  -9.058e-08  -9.562e-07  +2e-05  3e-09  1e-10  5e-09  1e-07  0.8964  2e-02   1  1  1 |  0  0
16  -9.724e-08  -2.083e-07  +3e-06  4e-10  1e-11  7e-10  2e-08  0.9245  6e-02   2  1  1 |  0  0
17  -9.770e-08  -1.242e-07  +7e-07  9e-11  3e-12  2e-10  4e-09  0.8645  1e-01   2  1  1 |  0  0
18  -9.790e-08  -1.022e-07  +1e-07  2e-11  5e-13  3e-11  6e-10  0.8458  9e-03   2  1  1 |  0  0
19  -9.791e-08  -9.892e-08  +3e-08  4e-12  1e-13  6e-12  1e-10  0.8642  1e-01   1  1  1 |  0  0
20  -9.792e-08  -9.814e-08  +6e-09  8e-13  3e-14  1e-12  3e-11  0.8006  2e-02   1  1  1 |  0  0

OPTIMAL (within feastol=7.8e-13, reltol=6.2e-02, abstol=6.1e-09).
Runtime: 0.009532 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.959e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.759e+00  -3.042e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4228  3e-01   1  1  1 |  0  0
 2  +5.149e-01  -2.988e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8736  7e-02   1  1  1 |  0  0
 3  -1.671e-02  -1.326e+00  +3e+01  6e-03  2e-04  6e-02  2e-01  0.7674  2e-01   2  2  2 |  0  0
 4  +9.842e-04  -5.475e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.6263  1e-01   1  2  2 |  0  0
 5  -3.718e-02  -4.040e-01  +1e+01  1e-03  5e-05  5e-03  5e-02  0.8573  6e-01   1  2  1 |  0  0
 6  -8.749e-03  -1.528e-01  +4e+00  5e-04  2e-05  1e-03  2e-02  0.9137  3e-01   1  1  1 |  0  0
 7  -2.597e-03  -4.288e-02  +1e+00  1e-04  5e-06  3e-04  6e-03  0.8645  2e-01   1  1  1 |  0  0
 8  -3.646e-04  -1.359e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.8751  2e-01   1  1  1 |  0  0
 9  -1.429e-05  -6.676e-03  +2e-01  2e-05  8e-07  4e-05  9e-04  0.8138  4e-01   1  1  1 |  0  0
10  -6.774e-05  -2.857e-03  +8e-02  1e-05  3e-07  2e-05  4e-04  0.7794  3e-01   1  1  1 |  0  0
11  +3.400e-06  -5.684e-04  +2e-02  2e-06  7e-08  4e-06  8e-05  0.8993  1e-01   1  1  1 |  0  0
12  +3.522e-07  -1.080e-04  +3e-03  4e-07  1e-08  7e-07  1e-05  0.8826  8e-02   1  1  1 |  0  0
13  -1.159e-10  -2.083e-05  +6e-04  7e-08  2e-09  1e-07  3e-06  0.9033  1e-01   1  1  1 |  0  0
14  -1.679e-08  -6.154e-06  +2e-04  2e-08  7e-10  4e-08  8e-07  0.9890  3e-01   1  1  1 |  0  0
15  -3.223e-09  -1.632e-06  +5e-05  6e-09  2e-10  1e-08  2e-07  0.8126  1e-01   2  1  1 |  0  0
16  -1.813e-08  -8.780e-08  +2e-06  2e-10  8e-12  4e-10  1e-08  0.9890  3e-02   1  1  1 |  0  0
17  -1.833e-08  -2.013e-08  +5e-08  6e-12  2e-13  1e-11  2e-10  0.9741  1e-04   1  1  1 |  0  0
18  -1.833e-08  -1.847e-08  +4e-09  5e-13  2e-14  9e-13  2e-11  0.9244  1e-03   1  1  1 |  0  0

OPTIMAL (within feastol=5.0e-13, reltol=2.1e-01, abstol=3.9e-09).
Runtime: 0.008386 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.959e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.759e+00  -3.042e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4228  3e-01   1  1  1 |  0  0
 2  +5.147e-01  -2.988e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8736  7e-02   1  1  1 |  0  0
 3  -1.711e-02  -1.324e+00  +3e+01  6e-03  2e-04  6e-02  2e-01  0.7681  2e-01   2  2  2 |  0  0
 4  +7.735e-04  -5.470e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.6266  1e-01   1  2  2 |  0  0
 5  -3.781e-02  -4.020e-01  +1e+01  1e-03  4e-05  5e-03  5e-02  0.8713  6e-01   1  2  1 |  0  0
 6  -8.573e-03  -1.499e-01  +4e+00  5e-04  2e-05  1e-03  2e-02  0.9118  3e-01   1  1  1 |  0  0
 7  -2.551e-03  -4.222e-02  +1e+00  1e-04  5e-06  3e-04  5e-03  0.8643  2e-01   1  1  1 |  0  0
 8  -3.685e-04  -1.340e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.8720  2e-01   1  1  1 |  0  0
 9  -1.333e-05  -6.556e-03  +2e-01  2e-05  8e-07  4e-05  9e-04  0.8123  4e-01   1  1  1 |  0  0
10  -6.595e-05  -2.790e-03  +8e-02  1e-05  3e-07  2e-05  4e-04  0.7837  3e-01   1  1  1 |  0  0
11  +3.593e-06  -5.425e-04  +2e-02  2e-06  6e-08  3e-06  7e-05  0.9028  1e-01   1  1  1 |  0  0
12  +3.926e-07  -1.035e-04  +3e-03  4e-07  1e-08  6e-07  1e-05  0.8799  8e-02   2  1  1 |  0  0
13  +2.011e-08  -2.028e-05  +6e-04  7e-08  2e-09  1e-07  3e-06  0.9114  1e-01   1  1  1 |  0  0
14  -7.966e-09  -6.405e-06  +2e-04  2e-08  8e-10  4e-08  9e-07  0.9386  3e-01   2  1  1 |  0  0
15  +1.982e-08  -2.688e-06  +8e-05  1e-08  3e-10  2e-08  4e-07  0.7328  2e-01   2  1  1 |  0  0
16  -3.212e-09  -2.356e-07  +6e-06  8e-10  3e-11  1e-09  3e-08  0.9791  7e-02   2  1  1 |  0  0
17  -3.449e-09  -9.630e-09  +2e-07  2e-11  7e-13  4e-11  8e-10  0.9735  1e-04   1  1  1 |  0  0
18  -3.446e-09  -3.841e-09  +1e-08  1e-12  5e-14  2e-12  5e-11  0.9363  2e-04   1  1  1 |  0  0
19  -3.445e-09  -3.507e-09  +2e-09  2e-13  9e-15  4e-13  9e-12  0.8461  5e-03   1  1  1 |  0  0

OPTIMAL (within feastol=2.5e-13, reltol=5.1e-01, abstol=1.7e-09).
Runtime: 0.008804 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.959e+00  -1.108e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.759e+00  -3.042e+01  +5e+02  2e-01  9e-03  1e+00  2e+00  0.4228  3e-01   1  1  1 |  0  0
 2  +5.146e-01  -2.988e+00  +8e+01  2e-02  7e-04  2e-01  4e-01  0.8736  7e-02   1  1  1 |  0  0
 3  -1.729e-02  -1.323e+00  +3e+01  6e-03  2e-04  6e-02  2e-01  0.7684  2e-01   2  2  2 |  0  0
 4  +6.824e-04  -5.467e-01  +1e+01  2e-03  7e-05  2e-02  7e-02  0.6267  1e-01   1  2  2 |  0  0
 5  -3.809e-02  -4.012e-01  +1e+01  1e-03  4e-05  5e-03  5e-02  0.8776  6e-01   1  2  1 |  0  0
 6  -8.497e-03  -1.487e-01  +4e+00  5e-04  2e-05  1e-03  2e-02  0.9108  3e-01   1  1  1 |  0  0
 7  -2.531e-03  -4.193e-02  +1e+00  1e-04  5e-06  3e-04  5e-03  0.8643  2e-01   1  1  1 |  0  0
 8  -3.690e-04  -1.330e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.8712  2e-01   1  1  1 |  0  0
 9  -1.294e-05  -6.504e-03  +2e-01  2e-05  8e-07  4e-05  9e-04  0.8111  4e-01   1  1  1 |  0  0
10  -6.520e-05  -2.761e-03  +8e-02  1e-05  3e-07  2e-05  4e-04  0.7856  3e-01   1  1  1 |  0  0
11  +3.656e-06  -5.322e-04  +1e-02  2e-06  6e-08  3e-06  7e-05  0.9042  1e-01   1  1  1 |  0  0
12  +4.055e-07  -1.018e-04  +3e-03  4e-07  1e-08  6e-07  1e-05  0.8786  8e-02   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.074e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 4.228e-01
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.074e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.021e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.099e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.299e-02
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.099e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 1.027e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.018e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.126e-03
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.018e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.706e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.050e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.802e-04
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.050e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.842e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.019e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.272e-05
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.019e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.333e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.112e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.110e-06
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.112e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.507e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.119e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 2.699e-07
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.119e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.525e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.054e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.836e-08
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.054e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.094e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.587e+00  -1.079e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.756e+00  -3.465e+01  +4e+02  2e-01  2e-02  2e+00  2e+00  0.4156  4e-01   1  1  1 |  0  0
 2  +2.231e-01  -2.351e+00  +7e+01  1e-02  1e-03  9e-01  4e-01  0.9356  1e-01   1  1  1 |  0  0
 3  -1.653e-01  -1.815e+00  +4e+01  8e-03  8e-04  4e-01  3e-01  0.5695  3e-01   1  1  1 |  0  0
 4  -3.013e-01  -1.046e+00  +2e+01  3e-03  3e-04  2e-01  1e-01  0.5828  8e-02   1  1  2 |  0  0
 5  -3.600e-01  -6.782e-01  +9e+00  1e-03  1e-04  6e-02  5e-02  0.6303  9e-02   1  1  2 |  0  0
 6  -3.910e-01  -5.677e-01  +5e+00  7e-04  6e-05  2e-02  3e-02  0.6537  3e-01   1  1  1 |  0  0
 7  -4.124e-01  -4.598e-01  +1e+00  2e-04  2e-05  4e-03  7e-03  0.7994  8e-02   1  1  1 |  0  0
 8  -4.181e-01  -4.365e-01  +5e-01  6e-05  5e-06  4e-04  3e-03  0.9208  3e-01   1  1  1 |  0  0
 9  -4.201e-01  -4.299e-01  +3e-01  3e-05  3e-06  1e-04  1e-03  0.7527  4e-01   1  1  1 |  0  0
10  -4.223e-01  -4.241e-01  +5e-02  6e-06  5e-07  2e-05  2e-04  0.8457  3e-02   1  1  1 |  0  0
11  -4.227e-01  -4.230e-01  +7e-03  8e-07  7e-08  3e-06  3e-05  0.8889  2e-02   1  1  1 |  0  0
12  -4.228e-01  -4.229e-01  +2e-03  2e-07  2e-08  6e-07  1e-05  0.8531  2e-01   2  1  1 |  0  0
13  -4.228e-01  -4.228e-01  +9e-04  1e-07  9e-09  2e-07  4e-06  0.7284  2e-01   2  1  1 |  0  0
14  -4.228e-01  -4.228e-01  +3e-04  3e-08  3e-09  5e-08  1e-06  0.9341  2e-01   1  1  1 |  0  0
15  -4.228e-01  -4.228e-01  +4e-05  5e-09  5e-10  9e-09  2e-07  0.9200  1e-01   1  1  1 |  0  0
16  -4.228e-01  -4.228e-01  +8e-06  9e-10  8e-11  2e-09  4e-08  0.8417  2e-02   1  1  1 |  0  0
17  -4.228e-01  -4.228e-01  +2e-06  3e-10  2e-11  5e-10  1e-08  0.9890  3e-01   1  1  1 |  0  0
18  -4.228e-01  -4.228e-01  +3e-07  3e-11  3e-12  5e-11  1e-09  0.8916  9e-03   2  1  1 |  0  0
19  -4.228e-01  -4.228e-01  +1e-07  1e-11  2e-12  2e-11  6e-10  0.7704  3e-01   2  1  1 |  0  0
20  -4.228e-01  -4.228e-01  +2e-08  2e-12  5e-13  4e-12  1e-10  0.8678  4e-02   2  1  1 |  0  0
21  -4.228e-01  -4.228e-01  +5e-09  7e-13  2e-13  1e-12  3e-11  0.9890  3e-01   1  1  1 |  0  0

OPTIMAL (within feastol=6.7e-13, reltol=1.3e-08, abstol=5.3e-09).
Runtime: 0.010171 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.842e+00  -1.082e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.727e+00  -2.948e+01  +4e+02  2e-01  1e-02  1e+00  2e+00  0.4291  3e-01   1  1  1 |  0  0
 2  +5.751e-01  -2.861e+00  +8e+01  2e-02  8e-04  3e-01  4e-01  0.8725  7e-02   1  1  1 |  0  0
 3  +7.485e-02  -1.506e+00  +4e+01  7e-03  3e-04  1e-01  2e-01  0.6245  2e-01   2  2  2 |  0  0
 4  -8.125e-03  -6.089e-01  +2e+01  2e-03  9e-05  3e-02  8e-02  0.6556  8e-02   1  2  2 |  0  0
 5  -4.160e-02  -5.473e-01  +1e+01  2e-03  8e-05  2e-02  7e-02  0.4679  6e-01   1  2  1 |  0  0
 6  -6.632e-02  -3.219e-01  +7e+00  1e-03  4e-05  6e-03  3e-02  0.7147  3e-01   2  2  1 |  0  0
 7  -6.178e-02  -1.883e-01  +3e+00  5e-04  2e-05  9e-04  2e-02  0.9890  5e-01   1  1  1 |  0  0
 8  -6.203e-02  -9.217e-02  +8e-01  1e-04  4e-06  2e-04  4e-03  0.8524  1e-01   1  1  1 |  0  0
 9  -6.285e-02  -7.670e-02  +4e-01  5e-05  2e-06  9e-05  2e-03  0.8175  3e-01   1  1  1 |  0  0
10  -6.241e-02  -6.977e-02  +2e-01  3e-05  1e-06  5e-05  1e-03  0.7902  4e-01   1  1  1 |  0  0
11  -6.291e-02  -6.437e-02  +4e-02  5e-06  2e-07  9e-06  2e-04  0.8934  1e-01   1  1  1 |  0  0
12  -6.296e-02  -6.323e-02  +7e-03  1e-06  4e-08  2e-06  4e-05  0.8916  9e-02   1  1  1 |  0  0
13  -6.298e-02  -6.303e-02  +1e-03  1e-07  6e-09  3e-07  6e-06  0.8738  3e-02   2  1  1 |  0  0
14  -6.299e-02  -6.300e-02  +3e-04  3e-08  1e-09  6e-08  1e-06  0.8931  1e-01   2  1  1 |  0  0
15  -6.299e-02  -6.299e-02  +3e-05  4e-09  2e-10  8e-09  2e-07  0.8769  1e-02   2  1  1 |  0  0
16  -6.299e-02  -6.299e-02  +6e-06  8e-10  3e-11  1e-09  3e-08  0.9233  1e-01   2  1  1 |  0  0
17  -6.299e-02  -6.299e-02  +8e-07  1e-10  4e-12  2e-10  4e-09  0.8847  9e-03   1  1  1 |  0  0
18  -6.299e-02  -6.299e-02  +2e-07  2e-11  1e-12  4e-11  1e-09  0.8552  1e-01   2  1  1 |  0  0
19  -6.299e-02  -6.299e-02  +4e-08  5e-12  2e-13  9e-12  2e-10  0.8341  6e-02   2  1  1 |  0  0
20  -6.299e-02  -6.299e-02  +1e-08  2e-12  8e-14  3e-12  7e-11  0.8309  2e-01   1  1  1 |  0  0
21  -6.299e-02  -6.299e-02  +3e-09  4e-13  3e-14  6e-13  1e-11  0.8699  9e-02   2  1  1 |  0  0

OPTIMAL (within feastol=3.6e-13, reltol=4.5e-08, abstol=2.8e-09).
Runtime: 0.010238 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.884e+00  -1.100e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.442e+00  -2.681e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4750  3e-01   1  1  1 |  0  0
 2  +2.867e-01  -2.911e+00  +7e+01  1e-02  5e-04  1e-01  4e-01  0.8693  6e-02   1  1  1 |  0  0
 3  +5.378e-03  -1.004e+00  +3e+01  4e-03  1e-04  3e-02  1e-01  0.7933  2e-01   2  2  2 |  0  0
 4  -1.313e-02  -4.962e-01  +1e+01  2e-03  5e-05  1e-02  6e-02  0.6119  2e-01   1  2  2 |  0  0
 5  -2.252e-02  -3.715e-01  +9e+00  1e-03  4e-05  6e-03  4e-02  0.5832  5e-01   1  2  1 |  0  0
 6  -1.918e-02  -1.662e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.7760  3e-01   1  2  1 |  0  0
 7  -8.823e-03  -7.327e-02  +2e+00  2e-04  6e-06  4e-04  8e-03  0.9890  4e-01   1  1  1 |  0  0
 8  -6.500e-03  -2.155e-02  +4e-01  6e-05  1e-06  1e-04  2e-03  0.8239  7e-02   1  1  1 |  0  0
 9  -6.465e-03  -1.232e-02  +2e-01  2e-05  6e-07  4e-05  8e-04  0.8695  3e-01   1  1  1 |  0  0
10  -6.084e-03  -8.667e-03  +7e-02  9e-06  2e-07  2e-05  3e-04  0.8031  3e-01   1  1  1 |  0  0
11  -6.146e-03  -6.782e-03  +2e-02  2e-06  6e-08  4e-06  8e-05  0.8842  1e-01   1  1  1 |  0  0
12  -6.125e-03  -6.199e-03  +2e-03  3e-07  7e-09  5e-07  1e-05  0.9434  6e-02   1  1  1 |  0  0
13  -6.126e-03  -6.132e-03  +2e-04  2e-08  6e-10  4e-08  8e-07  0.9236  7e-03   1  1  1 |  0  0
14  -6.126e-03  -6.127e-03  +3e-05  4e-09  1e-10  7e-09  1e-07  0.8369  2e-02   2  1  1 |  0  0
15  -6.126e-03  -6.126e-03  +2e-06  2e-10  6e-12  4e-10  9e-09  0.9610  2e-02   1  1  1 |  0  0
16  -6.126e-03  -6.126e-03  +3e-07  4e-11  1e-12  7e-11  1e-09  0.8480  2e-02   2  1  1 |  0  0
17  -6.126e-03  -6.126e-03  +6e-08  9e-12  3e-13  2e-11  3e-10  0.8414  7e-02   2  1  1 |  0  0
18  -6.126e-03  -6.126e-03  +3e-08  4e-12  1e-13  6e-12  1e-10  0.7294  2e-01   2  1  1 |  0  0
19  -6.126e-03  -6.126e-03  +1e-08  2e-12  6e-14  3e-12  5e-11  0.7621  2e-01   2  1  1 |  0  0
20  -6.126e-03  -6.126e-03  +4e-09  5e-13  2e-14  9e-13  2e-11  0.8663  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=5.3e-13, reltol=6.2e-07, abstol=3.8e-09).
Runtime: 0.009670 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.959e+00  -1.112e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.981e+00  -2.681e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4882  2e-01   1  1  1 |  0  0
 2  +2.311e-01  -3.485e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8421  5e-02   2  1  2 |  0  0
 3  -2.736e-03  -1.116e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7780  1e-01   2  2  2 |  0  0
 4  -1.783e-02  -5.728e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5988  2e-01   1  2  2 |  0  0
 5  -4.247e-02  -3.617e-01  +8e+00  1e-03  3e-05  4e-03  4e-02  0.8321  5e-01   1  2  1 |  0  0
 6  -1.479e-02  -1.551e-01  +4e+00  5e-04  1e-05  1e-03  2e-02  0.8483  3e-01   1  2  1 |  0  0
 7  -3.774e-03  -3.938e-02  +9e-01  1e-04  3e-06  3e-04  5e-03  0.9625  2e-01   1  1  1 |  0  0
 8  -8.002e-04  -1.016e-02  +2e-01  3e-05  8e-07  6e-05  1e-03  0.8632  1e-01   1  1  1 |  0  0
 9  -7.195e-04  -4.738e-03  +1e-01  1e-05  3e-07  3e-05  5e-04  0.8542  3e-01   1  1  1 |  0  0
10  -4.160e-04  -2.229e-03  +5e-02  7e-06  2e-07  1e-05  2e-04  0.8116  3e-01   1  1  1 |  0  0
11  -3.984e-04  -7.287e-04  +9e-03  1e-06  3e-08  2e-06  4e-05  0.9075  1e-01   1  1  1 |  0  0
12  -3.805e-04  -4.119e-04  +8e-04  1e-07  3e-09  2e-07  4e-06  0.9449  4e-02   2  1  1 |  0  0
13  -3.804e-04  -3.830e-04  +7e-05  1e-08  2e-10  2e-08  3e-07  0.9223  6e-03   1  1  1 |  0  0
14  -3.802e-04  -3.806e-04  +9e-06  1e-09  3e-11  2e-09  5e-08  0.8880  3e-02   1  1  1 |  0  0
15  -3.802e-04  -3.803e-04  +2e-06  2e-10  5e-12  4e-10  8e-09  0.8232  4e-03   2  1  1 |  0  0
16  -3.802e-04  -3.802e-04  +2e-07  3e-11  8e-13  6e-11  1e-09  0.8914  4e-02   2  1  1 |  0  0
17  -3.802e-04  -3.802e-04  +5e-08  7e-12  2e-13  1e-11  2e-10  0.9012  1e-01   2  1  1 |  0  0
18  -3.802e-04  -3.802e-04  +9e-09  1e-12  4e-14  2e-12  5e-11  0.8702  7e-02   1  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=2.5e-05, abstol=9.4e-09).
Runtime: 0.008807 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.971e+00  -1.115e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.878e+00  -2.673e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4924  2e-01   1  1  1 |  0  0
 2  +2.200e-01  -3.634e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8344  5e-02   2  1  2 |  0  0
 3  -5.624e-03  -1.144e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7741  1e-01   2  2  2 |  0  0
 4  -2.055e-02  -5.904e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5990  2e-01   1  2  2 |  0  0
 5  -5.025e-02  -3.440e-01  +7e+00  1e-03  2e-05  2e-03  4e-02  0.9822  5e-01   1  2  1 |  0  0
 6  -1.335e-02  -1.308e-01  +3e+00  4e-04  1e-05  9e-04  1e-02  0.8347  3e-01   1  1  1 |  0  0
 7  -2.914e-03  -3.216e-02  +8e-01  1e-04  2e-06  2e-04  4e-03  0.9733  2e-01   1  1  1 |  0  0
 8  -6.063e-04  -9.661e-03  +2e-01  3e-05  7e-07  6e-05  1e-03  0.8268  2e-01   1  1  1 |  0  0
 9  -1.246e-04  -2.429e-03  +6e-02  8e-06  2e-07  2e-05  3e-04  0.8364  1e-01   1  1  1 |  0  0
10  -8.001e-05  -9.649e-04  +2e-02  3e-06  7e-08  6e-06  1e-04  0.7561  2e-01   1  1  1 |  0  0
11  -3.113e-05  -4.592e-04  +1e-02  2e-06  4e-08  3e-06  5e-05  0.8222  4e-01   1  1  1 |  0  0
12  -2.605e-05  -9.379e-05  +2e-03  2e-07  6e-09  5e-07  9e-06  0.9214  9e-02   2  1  1 |  0  0
13  -2.291e-05  -2.841e-05  +1e-04  2e-08  5e-10  4e-08  7e-07  0.9316  1e-02   1  1  1 |  0  0
14  -2.273e-05  -2.317e-05  +1e-05  2e-09  4e-11  3e-09  6e-08  0.9214  2e-03   1  1  1 |  0  0
15  -2.272e-05  -2.280e-05  +2e-06  3e-10  7e-12  6e-10  1e-08  0.8222  1e-02   1  1  1 |  0  0
16  -2.272e-05  -2.273e-05  +3e-07  5e-11  1e-12  9e-11  2e-09  0.9259  9e-02   2  1  1 |  0  0
17  -2.272e-05  -2.272e-05  +7e-08  1e-11  2e-13  2e-11  4e-10  0.8545  8e-02   1  1  1 |  0  0
18  -2.272e-05  -2.272e-05  +2e-08  3e-12  8e-14  6e-12  1e-10  0.8017  2e-01   2  1  1 |  0  0
19  -2.272e-05  -2.272e-05  +8e-09  1e-12  3e-14  2e-12  4e-11  0.8263  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.1e-12, reltol=3.3e-04, abstol=7.6e-09).
Runtime: 0.009298 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.971e+00  -1.115e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.864e+00  -2.671e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4930  2e-01   1  1  1 |  0  0
 2  +2.190e-01  -3.661e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8330  5e-02   2  1  2 |  0  0
 3  -6.112e-03  -1.147e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7741  1e-01   2  2  2 |  0  0
 4  -2.120e-02  -5.933e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5992  2e-01   1  2  2 |  0  0
 5  -5.086e-02  -3.445e-01  +7e+00  1e-03  2e-05  2e-03  4e-02  0.9890  5e-01   1  2  1 |  0  0
 6  -1.163e-02  -1.174e-01  +3e+00  4e-04  9e-06  8e-04  1e-02  0.8334  2e-01   1  1  1 |  0  0
 7  -2.587e-03  -2.833e-02  +7e-01  1e-04  2e-06  2e-04  3e-03  0.9322  2e-01   1  1  1 |  0  0
 8  -6.448e-04  -9.926e-03  +2e-01  3e-05  8e-07  6e-05  1e-03  0.8306  2e-01   1  1  1 |  0  0
 9  -1.001e-04  -2.457e-03  +6e-02  9e-06  2e-07  2e-05  3e-04  0.8324  1e-01   2  1  1 |  0  0
10  -5.553e-05  -8.651e-04  +2e-02  3e-06  7e-08  5e-06  1e-04  0.7799  2e-01   1  1  1 |  0  0
11  -8.257e-06  -3.502e-04  +9e-03  1e-06  3e-08  2e-06  4e-05  0.8648  3e-01   1  1  1 |  0  0
12  -4.308e-06  -4.898e-05  +1e-03  2e-07  4e-09  3e-07  6e-06  0.9330  7e-02   2  1  1 |  0  0
13  -2.223e-06  -5.455e-06  +8e-05  1e-08  3e-10  2e-08  4e-07  0.9395  1e-02   1  1  1 |  0  0
14  -2.119e-06  -2.397e-06  +7e-06  1e-09  2e-11  2e-09  4e-08  0.9158  2e-03   2  1  1 |  0  0
15  -2.112e-06  -2.167e-06  +1e-06  2e-10  5e-12  4e-10  7e-09  0.8102  1e-02   2  1  1 |  0  0
16  -2.110e-06  -2.120e-06  +3e-07  4e-11  8e-13  7e-11  1e-09  0.9158  1e-01   2  1  1 |  0  0
17  -2.110e-06  -2.112e-06  +6e-08  9e-12  2e-13  2e-11  3e-10  0.8481  9e-02   1  1  1 |  0  0
18  -2.110e-06  -2.110e-06  +2e-08  3e-12  7e-14  5e-12  9e-11  0.8116  2e-01   2  1  1 |  0  0
19  -2.110e-06  -2.110e-06  +6e-09  8e-13  2e-14  1e-12  3e-11  0.8469  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=8.2e-13, reltol=2.7e-03, abstol=5.8e-09).
Runtime: 0.009461 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.971e+00  -1.115e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.863e+00  -2.671e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4932  2e-01   1  1  1 |  0  0
 2  +2.193e-01  -3.667e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8326  5e-02   2  1  2 |  0  0
 3  -6.182e-03  -1.147e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7743  1e-01   2  2  2 |  0  0
 4  -2.136e-02  -5.938e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5994  2e-01   1  2  2 |  0  0
 5  -5.084e-02  -3.444e-01  +7e+00  1e-03  2e-05  2e-03  4e-02  0.9890  5e-01   1  2  1 |  0  0
 6  -1.168e-02  -1.177e-01  +3e+00  4e-04  9e-06  8e-04  1e-02  0.8335  2e-01   1  1  1 |  0  0
 7  -2.587e-03  -2.839e-02  +7e-01  1e-04  2e-06  2e-04  3e-03  0.9328  2e-01   1  1  1 |  0  0

(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.084e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 5.588e-09
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.084e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.492e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.050e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 8.184e-10
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.050e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.294e-03 seconds
Reranking users:   0%|          | 8/2064 [00:02<10:47,  3.18it/s](CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.094e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 7.512e+00
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.094e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 7.360e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.049e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.096e-01
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.049e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 7.767e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.006e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 3.570e-02
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.006e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 8.722e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.006e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:15 PM: Optimal value: 6.536e-03
(CVXPY) Jun 21 07:40:15 PM: Compilation took 1.006e-02 seconds
(CVXPY) Jun 21 07:40:15 PM: Solver (including time spent in interface) took 9.190e-03 seconds
(CVXPY) Jun 21 07:40:15 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:15 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:15 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:15 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:15 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:15 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:15 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:15 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:15 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:15 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:15 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:15 PM: Finished problem compilation (took 1.028e-02 seconds).
(CVXPY) Jun 21 07:40:15 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.063e-03
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.028e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.911e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.072e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.115e-04
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.072e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.693e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.971e+00  -1.115e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.863e+00  -2.671e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4932  2e-01   1  1  1 |  0  0
 2  +2.196e-01  -3.669e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8325  5e-02   2  1  2 |  0  0
 3  -6.189e-03  -1.147e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7745  1e-01   2  2  2 |  0  0
 4  -2.142e-02  -5.939e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5994  2e-01   1  2  2 |  0  0
 5  -5.077e-02  -3.439e-01  +7e+00  1e-03  2e-05  2e-03  4e-02  0.9890  5e-01   1  2  1 |  0  0
 6  -1.200e-02  -1.204e-01  +3e+00  4e-04  9e-06  8e-04  1e-02  0.8347  3e-01   1  1  1 |  0  0
 7  -2.610e-03  -2.886e-02  +7e-01  1e-04  2e-06  2e-04  3e-03  0.9427  2e-01   1  1  1 |  0  0
 8  -6.356e-04  -9.982e-03  +2e-01  3e-05  8e-07  6e-05  1e-03  0.8254  2e-01   1  1  1 |  0  0
 9  -9.927e-05  -2.416e-03  +6e-02  9e-06  2e-07  2e-05  3e-04  0.8347  1e-01   1  1  1 |  0  0
10  -5.461e-05  -8.850e-04  +2e-02  3e-06  7e-08  6e-06  1e-04  0.7703  2e-01   1  1  1 |  0  0
11  -7.052e-06  -3.776e-04  +1e-02  1e-06  3e-08  2e-06  5e-05  0.8472  3e-01   1  1  1 |  0  0
12  -2.649e-06  -5.605e-05  +1e-03  2e-07  4e-09  4e-07  7e-06  0.9265  8e-02   1  1  1 |  0  0
13  -1.370e-07  -3.975e-06  +1e-04  1e-08  3e-10  3e-08  5e-07  0.9403  1e-02   2  1  1 |  0  0
14  -1.675e-08  -3.541e-07  +9e-06  1e-09  3e-11  2e-09  4e-08  0.9141  2e-03   1  1  1 |  0  0
15  -8.295e-09  -7.252e-08  +2e-06  2e-10  5e-12  4e-10  8e-09  0.8195  1e-02   1  1  1 |  0  0
16  -6.221e-09  -1.741e-08  +3e-07  4e-11  9e-13  7e-11  1e-09  0.9193  1e-01   2  1  1 |  0  0
17  -5.726e-09  -8.146e-09  +6e-08  9e-12  2e-13  2e-11  3e-10  0.8553  8e-02   2  1  1 |  0  0
18  -5.688e-09  -6.445e-09  +2e-08  3e-12  7e-14  5e-12  1e-10  0.8111  2e-01   2  1  1 |  0  0
19  -5.662e-09  -5.895e-09  +6e-09  9e-13  2e-14  2e-12  3e-11  0.8359  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=8.6e-13, reltol=1.1e+00, abstol=6.0e-09).
Runtime: 0.009454 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.971e+00  -1.115e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.864e+00  -2.671e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4932  2e-01   1  1  1 |  0  0
 2  +2.196e-01  -3.669e+00  +8e+01  2e-02  5e-04  1e-01  4e-01  0.8325  5e-02   2  1  2 |  0  0
 3  -6.189e-03  -1.147e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.7745  1e-01   2  2  2 |  0  0
 4  -2.142e-02  -5.939e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5994  2e-01   1  2  2 |  0  0
 5  -5.076e-02  -3.438e-01  +7e+00  1e-03  2e-05  2e-03  4e-02  0.9890  5e-01   1  2  1 |  0  0
 6  -1.206e-02  -1.208e-01  +3e+00  4e-04  9e-06  8e-04  1e-02  0.8349  3e-01   1  1  1 |  0  0
 7  -2.616e-03  -2.895e-02  +7e-01  1e-04  2e-06  2e-04  3e-03  0.9442  2e-01   1  1  1 |  0  0
 8  -6.340e-04  -9.982e-03  +2e-01  3e-05  8e-07  6e-05  1e-03  0.8247  2e-01   1  1  1 |  0  0
 9  -9.945e-05  -2.411e-03  +6e-02  8e-06  2e-07  2e-05  3e-04  0.8350  1e-01   1  1  1 |  0  0
10  -5.476e-05  -8.878e-04  +2e-02  3e-06  7e-08  6e-06  1e-04  0.7690  2e-01   1  1  1 |  0  0
11  -7.177e-06  -3.817e-04  +1e-02  1e-06  3e-08  3e-06  5e-05  0.8447  3e-01   1  1  1 |  0  0
12  -2.707e-06  -5.734e-05  +1e-03  2e-07  4e-09  4e-07  7e-06  0.9256  8e-02   1  1  1 |  0  0
13  -1.357e-07  -4.078e-06  +1e-04  1e-08  3e-10  3e-08  5e-07  0.9401  1e-02   2  1  1 |  0  0
14  -1.227e-08  -3.576e-07  +9e-06  1e-09  3e-11  2e-09  4e-08  0.9144  2e-03   1  1  1 |  0  0
15  -3.583e-09  -6.902e-08  +2e-06  2e-10  5e-12  4e-10  8e-09  0.8203  1e-02   1  1  1 |  0  0
16  -1.461e-09  -1.278e-08  +3e-07  4e-11  9e-13  8e-11  1e-09  0.9197  1e-01   2  1  1 |  0  0
17  -9.574e-10  -3.391e-09  +6e-08  9e-12  2e-13  2e-11  3e-10  0.8557  8e-02   1  1  1 |  0  0
18  -9.189e-10  -1.681e-09  +2e-08  3e-12  7e-14  5e-12  1e-10  0.8108  2e-01   3  1  1 |  0  0
19  -8.928e-10  -1.128e-09  +6e-09  9e-13  2e-14  2e-12  3e-11  0.8348  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=8.6e-13, reltol=6.8e+00, abstol=6.1e-09).
Runtime: 0.009258 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.372e+01  -1.470e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +9.770e-01  -7.442e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2538  4e-01   1  2  2 |  0  0
 2  -3.583e+00  -1.733e+01  +2e+02  5e-02  2e-03  5e-01  1e+00  0.7228  1e-01   1  1  1 |  0  0
 3  -6.362e+00  -1.101e+01  +9e+01  2e-02  5e-04  2e-01  5e-01  0.6672  9e-02   2  2  2 |  0  0
 4  -7.321e+00  -8.519e+00  +3e+01  4e-03  1e-04  4e-02  1e-01  0.7611  5e-02   1  2  2 |  0  0
 5  -7.422e+00  -7.952e+00  +1e+01  2e-03  5e-05  1e-02  6e-02  0.6772  2e-01   1  2  2 |  0  0
 6  -7.437e+00  -7.885e+00  +1e+01  1e-03  4e-05  1e-02  5e-02  0.3413  5e-01   1  1  1 |  0  0
 7  -7.503e+00  -7.558e+00  +1e+00  2e-04  5e-06  1e-03  6e-03  0.8975  2e-02   1  1  1 |  0  0
 8  -7.511e+00  -7.518e+00  +1e-01  2e-05  6e-07  1e-04  7e-04  0.9030  3e-02   1  1  1 |  0  0
 9  -7.512e+00  -7.513e+00  +2e-02  3e-06  1e-07  2e-05  1e-04  0.8530  3e-02   1  1  1 |  0  0
10  -7.512e+00  -7.512e+00  +5e-03  7e-07  2e-08  3e-06  2e-05  0.8634  7e-02   1  1  1 |  0  0
11  -7.512e+00  -7.512e+00  +5e-04  7e-08  2e-09  2e-07  2e-06  0.9407  4e-02   1  1  1 |  0  0
12  -7.512e+00  -7.512e+00  +2e-05  3e-09  9e-11  1e-08  1e-07  0.9562  1e-03   2  1  1 |  0  0
13  -7.512e+00  -7.512e+00  +1e-06  1e-10  4e-12  5e-10  5e-09  0.9623  1e-02   2  1  1 |  0  0
14  -7.512e+00  -7.512e+00  +1e-07  1e-11  4e-13  5e-11  5e-10  0.9022  2e-03   1  1  1 |  0  0
15  -7.512e+00  -7.512e+00  +6e-09  8e-13  3e-14  3e-12  3e-11  0.9495  4e-03   2  1  1 |  0  0

OPTIMAL (within feastol=7.7e-13, reltol=7.5e-10, abstol=5.7e-09).
Runtime: 0.007324 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.569e+00  -1.116e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.690e+00  -2.891e+01  +4e+02  1e-01  1e-02  1e+00  2e+00  0.4602  3e-01   1  1  1 |  0  0
 2  +7.067e-01  -4.900e+00  +1e+02  2e-02  1e-03  4e-01  6e-01  0.7620  7e-02   1  1  1 |  0  0
 3  -1.502e-01  -1.810e+00  +4e+01  7e-03  4e-04  1e-01  2e-01  0.7385  1e-01   1  2  1 |  0  0
 4  -2.588e-01  -7.497e-01  +1e+01  2e-03  9e-05  3e-02  6e-02  0.7441  7e-02   1  2  2 |  0  0
 5  -2.928e-01  -5.646e-01  +7e+00  1e-03  5e-05  8e-03  4e-02  0.7286  4e-01   1  2  2 |  0  0
 6  -3.042e-01  -3.719e-01  +2e+00  2e-04  1e-05  1e-03  9e-03  0.8486  1e-01   1  1  1 |  0  0
 7  -3.073e-01  -3.317e-01  +6e-01  8e-05  4e-06  2e-04  3e-03  0.9261  3e-01   1  1  1 |  0  0
 8  -3.081e-01  -3.189e-01  +3e-01  4e-05  2e-06  8e-05  1e-03  0.8405  3e-01   1  1  1 |  0  0
 9  -3.092e-01  -3.125e-01  +9e-02  1e-05  5e-07  2e-05  4e-04  0.8224  1e-01   1  1  1 |  0  0
10  -3.094e-01  -3.106e-01  +3e-02  4e-06  2e-07  7e-06  2e-04  0.8624  3e-01   1  1  1 |  0  0
11  -3.095e-01  -3.097e-01  +4e-03  5e-07  2e-08  9e-07  2e-05  0.8947  2e-02   1  1  1 |  0  0
12  -3.096e-01  -3.096e-01  +7e-04  8e-08  4e-09  1e-07  3e-06  0.9890  2e-01   1  1  1 |  0  0
13  -3.096e-01  -3.096e-01  +3e-05  4e-09  2e-10  7e-09  1e-07  0.9561  3e-03   1  1  1 |  0  0
14  -3.096e-01  -3.096e-01  +7e-07  9e-11  5e-12  2e-10  4e-09  0.9778  2e-03   2  1  1 |  0  0
15  -3.096e-01  -3.096e-01  +4e-08  5e-12  3e-13  9e-12  2e-10  0.9479  3e-04   1  1  1 |  0  0
16  -3.096e-01  -3.096e-01  +3e-09  4e-13  4e-14  6e-13  1e-11  0.9347  3e-03   1  1  1 |  0  0

OPTIMAL (within feastol=3.9e-13, reltol=8.5e-09, abstol=2.6e-09).
Runtime: 0.007731 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.859e+00  -1.126e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.712e+00  -2.945e+01  +4e+02  2e-01  8e-03  1e+00  2e+00  0.4498  3e-01   1  1  1 |  0  0
 2  +6.164e-01  -4.904e+00  +1e+02  2e-02  9e-04  2e-01  6e-01  0.7722  6e-02   1  1  1 |  0  0
 3  -8.318e-02  -1.416e+00  +3e+01  5e-03  2e-04  4e-02  2e-01  0.8014  1e-01   2  2  2 |  0  0
 4  -5.568e-02  -4.562e-01  +1e+01  2e-03  4e-05  9e-03  5e-02  0.8295  2e-01   2  2  2 |  0  0
 5  -5.359e-02  -2.734e-01  +6e+00  8e-04  2e-05  4e-03  3e-02  0.5498  2e-01   1  2  1 |  0  0
 6  -4.891e-02  -1.500e-01  +3e+00  4e-04  1e-05  7e-04  1e-02  0.9890  5e-01   1  1  1 |  0  0
 7  -3.871e-02  -6.582e-02  +7e-01  1e-04  3e-06  2e-04  3e-03  0.8111  1e-01   1  1  1 |  0  0
 8  -3.774e-02  -5.267e-02  +4e-01  5e-05  2e-06  1e-04  2e-03  0.6745  3e-01   1  1  1 |  0  0
 9  -3.643e-02  -4.433e-02  +2e-01  3e-05  8e-07  5e-05  1e-03  0.8384  4e-01   1  1  1 |  0  0
10  -3.602e-02  -3.857e-02  +6e-02  9e-06  3e-07  2e-05  3e-04  0.8642  2e-01   1  1  1 |  0  0
11  -3.572e-02  -3.609e-02  +9e-03  1e-06  4e-08  2e-06  5e-05  0.9216  7e-02   1  1  1 |  0  0
12  -3.570e-02  -3.578e-02  +2e-03  3e-07  8e-09  5e-07  1e-05  0.8674  1e-01   1  1  1 |  0  0
13  -3.570e-02  -3.572e-02  +6e-04  9e-08  2e-09  2e-07  3e-06  0.9890  3e-01   1  1  1 |  0  0
14  -3.570e-02  -3.570e-02  +7e-05  9e-09  3e-10  2e-08  3e-07  0.9060  1e-02   1  1  1 |  0  0
15  -3.570e-02  -3.570e-02  +2e-05  3e-09  7e-11  5e-09  9e-08  0.8737  2e-01   1  1  1 |  0  0
16  -3.570e-02  -3.570e-02  +4e-06  5e-10  2e-11  9e-10  2e-08  0.8607  8e-02   2  1  1 |  0  0
17  -3.570e-02  -3.570e-02  +3e-07  5e-11  1e-12  8e-11  2e-09  0.9682  6e-02   1  1  1 |  0  0
18  -3.570e-02  -3.570e-02  +4e-09  6e-13  2e-14  1e-12  2e-11  0.9874  1e-04   2  1  1 |  0  0

OPTIMAL (within feastol=6.1e-13, reltol=1.2e-07, abstol=4.3e-09).
Runtime: 0.008685 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.069e+00  -1.169e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.541e+00  -2.787e+01  +4e+02  2e-01  5e-03  7e-01  2e+00  0.5083  2e-01   1  2  1 |  0  0
 2  +2.578e-01  -6.195e+00  +1e+02  3e-02  8e-04  2e-01  6e-01  0.7217  5e-02   2  1  2 |  0  0
 3  -1.468e-01  -1.378e+00  +3e+01  5e-03  1e-04  3e-02  1e-01  0.8136  5e-02   2  2  2 |  0  0
 4  -7.097e-02  -5.355e-01  +1e+01  2e-03  4e-05  8e-03  5e-02  0.7788  2e-01   2  2  2 |  0  0
 5  -4.954e-02  -3.133e-01  +6e+00  1e-03  2e-05  4e-03  3e-02  0.5236  2e-01   1  2  2 |  0  0
 6  -3.581e-02  -1.713e-01  +3e+00  5e-04  1e-05  1e-03  2e-02  0.9890  5e-01   1  2  2 |  0  0
 7  -1.665e-02  -6.073e-02  +1e+00  2e-04  3e-06  3e-04  5e-03  0.7338  8e-02   1  1  1 |  0  0
 8  -9.225e-03  -2.085e-02  +3e-01  4e-05  8e-07  8e-05  1e-03  0.8444  1e-01   1  1  1 |  0  0
 9  -7.475e-03  -1.216e-02  +1e-01  2e-05  3e-07  3e-05  6e-04  0.9890  4e-01   1  1  1 |  0  0
10  -6.692e-03  -7.393e-03  +2e-02  3e-06  5e-08  5e-06  8e-05  0.9061  6e-02   1  1  1 |  0  0
11  -6.566e-03  -6.713e-03  +4e-03  5e-07  1e-08  1e-06  2e-05  0.9364  2e-01   2  1  1 |  0  0
12  -6.551e-03  -6.625e-03  +2e-03  3e-07  5e-09  5e-07  9e-06  0.6910  3e-01   1  1  1 |  0  0
13  -6.539e-03  -6.550e-03  +3e-04  4e-08  8e-10  8e-08  1e-06  0.9627  1e-01   2  1  1 |  0  0
14  -6.536e-03  -6.538e-03  +4e-05  6e-09  1e-10  1e-08  2e-07  0.8741  2e-02   2  1  1 |  0  0
15  -6.536e-03  -6.536e-03  +3e-06  4e-10  7e-12  7e-10  1e-08  0.9578  2e-02   1  1  1 |  0  0
16  -6.536e-03  -6.536e-03  +8e-08  1e-11  2e-13  2e-11  4e-10  0.9693  1e-04   2  1  1 |  0  0
17  -6.536e-03  -6.536e-03  +1e-08  2e-12  4e-14  3e-12  6e-11  0.8546  4e-03   2  1  1 |  0  0
18  -6.536e-03  -6.536e-03  +2e-09  4e-13  8e-15  6e-13  1e-11  0.8333  2e-02   1  1  1 |  0  0

OPTIMAL (within feastol=3.6e-13, reltol=3.3e-07, abstol=2.1e-09).
Runtime: 0.009155 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.167e+00  -1.194e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.567e+00  -2.742e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5412  2e-01   2  2  1 |  0  0
 2  -4.727e-02  -6.478e+00  +1e+02  3e-02  7e-04  1e-01  6e-01  0.7168  5e-02   2  2  2 |  0  0
 3  -1.782e-01  -1.316e+00  +3e+01  5e-03  9e-05  2e-02  1e-01  0.8315  5e-02   2  2  2 |  0  0
 4  -9.495e-02  -5.996e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.7101  2e-01   2  2  2 |  0  0
 5  -6.227e-02  -3.519e-01  +7e+00  1e-03  2e-05  4e-03  3e-02  0.5295  2e-01   2  2  2 |  0  0
 6  -4.251e-02  -2.028e-01  +4e+00  6e-04  1e-05  1e-03  2e-02  0.9361  5e-01   1  2  2 |  0  0
 7  -1.488e-02  -6.546e-02  +1e+00  2e-04  3e-06  4e-04  6e-03  0.7481  9e-02   1  1  1 |  0  0
 8  -4.363e-03  -1.615e-02  +3e-01  4e-05  7e-07  9e-05  1e-03  0.8223  7e-02   1  1  1 |  0  0
 9  -2.345e-03  -6.969e-03  +1e-01  2e-05  3e-07  3e-05  5e-04  0.8583  3e-01   1  1  1 |  0  0
10  -1.505e-03  -3.256e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8668  3e-01   1  1  1 |  0  0
11  -1.153e-03  -1.479e-03  +8e-03  1e-06  2e-08  2e-06  4e-05  0.9412  1e-01   1  1  1 |  0  0
12  -1.086e-03  -1.178e-03  +2e-03  3e-07  6e-09  6e-07  1e-05  0.8234  1e-01   1  1  1 |  0  0
13  -1.068e-03  -1.088e-03  +5e-04  7e-08  1e-09  1e-07  2e-06  0.8584  1e-01   1  1  1 |  0  0
14  -1.065e-03  -1.075e-03  +2e-04  4e-08  6e-10  7e-08  1e-06  0.7248  3e-01   1  1  1 |  0  0
15  -1.063e-03  -1.064e-03  +2e-05  3e-09  5e-11  5e-09  9e-08  0.9365  9e-03   2  1  1 |  0  0
16  -1.063e-03  -1.063e-03  +5e-06  8e-10  1e-11  1e-09  2e-08  0.7561  5e-02   2  1  1 |  0  0
17  -1.063e-03  -1.063e-03  +2e-06  3e-10  5e-12  6e-10  1e-08  0.7802  2e-01   2  1  1 |  0  0
18  -1.063e-03  -1.063e-03  +3e-07  5e-11  8e-13  9e-11  2e-09  0.9395  1e-01   2  1  1 |  0  0
19  -1.063e-03  -1.063e-03  +1e-08  2e-12  4e-14  4e-12  7e-11  0.9753  2e-02   1  1  1 |  0  0
20  -1.063e-03  -1.063e-03  +1e-09  2e-13  3e-15  4e-13  6e-12  0.9202  3e-03   1  1  1 |  0  0


(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.088e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.065e-05
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.088e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.916e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.051e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.018e-06
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.051e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.072e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.020e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 9.713e-08
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.020e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.047e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.059e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 9.303e-09
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.059e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.334e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.040e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 8.805e-10
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.040e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.535e-03 seconds
Reranking users:   0%|          | 9/2064 [00:02<10:24,  3.29it/s](CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.018e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 7.785e+00
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.018e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.323e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.001e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.524e-01
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.001e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.012e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.016e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 7.537e-02
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.016e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.702e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.971e-03 seconds).

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.214e+00  -1.206e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.061e+00  -2.736e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5555  2e-01   2  2  1 |  0  0
 2  -2.068e-01  -6.521e+00  +1e+02  3e-02  6e-04  1e-01  6e-01  0.7196  5e-02   2  2  2 |  0  0
 3  -1.819e-01  -1.285e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8348  5e-02   2  2  2 |  0  0
 4  -1.041e-01  -6.243e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.6776  2e-01   2  2  2 |  0  0
 5  -6.999e-02  -3.754e-01  +7e+00  1e-03  2e-05  4e-03  4e-02  0.5256  2e-01   2  2  2 |  0  0
 6  -4.813e-02  -2.211e-01  +4e+00  7e-04  1e-05  2e-03  2e-02  0.8984  5e-01   1  2  2 |  0  0
 7  -1.684e-02  -7.403e-02  +1e+00  2e-04  3e-06  5e-04  7e-03  0.7536  1e-01   1  1  1 |  0  0
 8  -3.901e-03  -1.679e-02  +3e-01  5e-05  8e-07  1e-04  2e-03  0.8224  6e-02   1  1  1 |  0  0
 9  -1.566e-03  -6.550e-03  +1e-01  2e-05  3e-07  4e-05  6e-04  0.8048  2e-01   1  1  1 |  0  0
10  -4.892e-04  -2.208e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8937  3e-01   1  1  1 |  0  0
11  -1.009e-04  -3.990e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.9485  1e-01   1  1  1 |  0  0
12  -2.477e-05  -7.407e-05  +1e-03  2e-07  3e-09  4e-07  6e-06  0.9782  1e-01   1  1  1 |  0  0
13  -1.606e-05  -3.447e-05  +4e-04  7e-08  1e-09  1e-07  2e-06  0.9890  4e-01   2  1  1 |  0  0
14  -1.111e-05  -1.262e-05  +4e-05  6e-09  9e-11  1e-08  2e-07  0.9269  1e-02   1  1  1 |  0  0
15  -1.069e-05  -1.085e-05  +4e-06  6e-10  9e-12  1e-09  2e-08  0.9218  3e-02   2  1  1 |  0  0
16  -1.065e-05  -1.065e-05  +5e-08  7e-12  1e-13  1e-11  2e-10  0.9879  7e-04   2  1  1 |  0  0
17  -1.065e-05  -1.065e-05  +1e-09  2e-13  5e-15  4e-13  7e-12  0.9717  1e-04   2  1  1 |  0  0

OPTIMAL (within feastol=2.1e-13, reltol=1.3e-04, abstol=1.3e-09).
Runtime: 0.008879 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.218e+00  -1.207e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.025e+00  -2.736e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5564  2e-01   2  2  1 |  0  0
 2  -2.181e-01  -6.522e+00  +1e+02  3e-02  6e-04  1e-01  6e-01  0.7200  5e-02   2  2  2 |  0  0
 3  -1.819e-01  -1.282e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8351  5e-02   2  2  2 |  0  0
 4  -1.048e-01  -6.263e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.6750  2e-01   2  2  2 |  0  0
 5  -7.052e-02  -3.768e-01  +7e+00  1e-03  2e-05  4e-03  4e-02  0.5260  2e-01   2  2  2 |  0  0
 6  -4.855e-02  -2.222e-01  +4e+00  7e-04  1e-05  2e-03  2e-02  0.8961  5e-01   1  2  2 |  0  0
 7  -1.724e-02  -7.562e-02  +1e+00  2e-04  3e-06  5e-04  7e-03  0.7485  1e-01   1  1  1 |  0  0
 8  -3.929e-03  -1.687e-02  +3e-01  5e-05  8e-07  1e-04  2e-03  0.8240  6e-02   1  1  1 |  0  0
 9  -1.548e-03  -6.482e-03  +1e-01  2e-05  3e-07  4e-05  6e-04  0.8156  2e-01   1  1  1 |  0  0
10  -4.722e-04  -2.153e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8895  3e-01   1  1  1 |  0  0
11  -9.040e-05  -3.836e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.9492  1e-01   1  1  1 |  0  0
12  -1.532e-05  -6.463e-05  +1e-03  2e-07  3e-09  4e-07  6e-06  0.9697  1e-01   2  1  1 |  0  0
13  -5.884e-06  -2.246e-05  +4e-04  6e-08  1e-09  1e-07  2e-06  0.9643  3e-01   2  1  1 |  0  0
14  -2.152e-06  -5.895e-06  +9e-05  1e-08  2e-10  3e-08  4e-07  0.8458  8e-02   1  1  1 |  0  0
15  -1.121e-06  -1.468e-06  +8e-06  1e-09  2e-11  2e-09  4e-08  0.9272  2e-02   1  1  1 |  0  0
16  -1.024e-06  -1.042e-06  +4e-07  7e-11  1e-12  1e-10  2e-09  0.9485  3e-03   1  1  1 |  0  0
17  -1.019e-06  -1.020e-06  +4e-08  6e-12  1e-13  1e-11  2e-10  0.9144  3e-03   2  1  1 |  0  0
18  -1.018e-06  -1.018e-06  +2e-09  4e-13  8e-15  7e-13  1e-11  0.9834  5e-02   1  1  1 |  0  0

OPTIMAL (within feastol=3.9e-13, reltol=2.4e-03, abstol=2.5e-09).
Runtime: 0.009037 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.219e+00  -1.207e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.015e+00  -2.736e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5567  2e-01   2  2  1 |  0  0
 2  -2.214e-01  -6.522e+00  +1e+02  3e-02  6e-04  1e-01  6e-01  0.7201  5e-02   2  2  2 |  0  0
 3  -1.819e-01  -1.281e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8351  5e-02   2  2  2 |  0  0
 4  -1.050e-01  -6.269e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.6743  2e-01   2  2  2 |  0  0
 5  -7.068e-02  -3.772e-01  +7e+00  1e-03  2e-05  4e-03  4e-02  0.5261  2e-01   2  2  2 |  0  0
 6  -4.868e-02  -2.226e-01  +4e+00  7e-04  1e-05  2e-03  2e-02  0.8955  5e-01   1  2  2 |  0  0
 7  -1.736e-02  -7.608e-02  +1e+00  2e-04  3e-06  5e-04  7e-03  0.7471  1e-01   1  1  1 |  0  0
 8  -3.939e-03  -1.690e-02  +3e-01  5e-05  8e-07  1e-04  2e-03  0.8245  6e-02   1  1  1 |  0  0
 9  -1.544e-03  -6.461e-03  +1e-01  2e-05  3e-07  4e-05  6e-04  0.8190  2e-01   1  1  1 |  0  0
10  -4.688e-04  -2.137e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8882  3e-01   1  1  1 |  0  0
11  -8.918e-05  -3.808e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.9495  1e-01   1  1  1 |  0  0
12  -1.439e-05  -6.349e-05  +1e-03  2e-07  3e-09  4e-07  6e-06  0.9682  1e-01   1  1  1 |  0  0
13  -5.076e-06  -2.204e-05  +4e-04  6e-08  1e-09  1e-07  2e-06  0.9356  3e-01   2  1  1 |  0  0
14  -1.318e-06  -5.343e-06  +1e-04  1e-08  2e-10  3e-08  5e-07  0.8453  1e-01   2  1  1 |  0  0
15  -2.001e-07  -5.489e-07  +8e-06  1e-09  2e-11  3e-09  4e-08  0.9315  2e-02   2  1  1 |  0  0
16  -1.014e-07  -1.157e-07  +3e-07  5e-11  8e-13  1e-10  2e-09  0.9633  5e-03   2  1  1 |  0  0
17  -9.767e-08  -9.932e-08  +4e-08  6e-12  1e-13  1e-11  2e-10  0.8862  1e-03   2  1  1 |  0  0
18  -9.730e-08  -9.770e-08  +1e-08  1e-12  3e-14  3e-12  5e-11  0.8199  8e-02   1  1  1 |  0  0

OPTIMAL (within feastol=1.5e-12, reltol=9.8e-02, abstol=9.6e-09).
Runtime: 0.009013 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.219e+00  -1.207e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.012e+00  -2.736e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5568  2e-01   2  2  1 |  0  0
 2  -2.225e-01  -6.522e+00  +1e+02  3e-02  6e-04  1e-01  6e-01  0.7201  5e-02   2  2  2 |  0  0
 3  -1.819e-01  -1.281e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8352  5e-02   2  2  2 |  0  0
 4  -1.051e-01  -6.271e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.6740  2e-01   2  2  2 |  0  0
 5  -7.073e-02  -3.773e-01  +7e+00  1e-03  2e-05  4e-03  4e-02  0.5261  2e-01   2  2  2 |  0  0
 6  -4.871e-02  -2.227e-01  +4e+00  7e-04  1e-05  2e-03  2e-02  0.8953  5e-01   1  2  2 |  0  0
 7  -1.740e-02  -7.622e-02  +1e+00  2e-04  3e-06  5e-04  7e-03  0.7466  1e-01   1  1  1 |  0  0
 8  -3.942e-03  -1.691e-02  +3e-01  5e-05  8e-07  1e-04  2e-03  0.8246  6e-02   1  1  1 |  0  0
 9  -1.543e-03  -6.455e-03  +1e-01  2e-05  3e-07  4e-05  6e-04  0.8201  2e-01   1  1  1 |  0  0
10  -4.680e-04  -2.133e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8879  3e-01   1  1  1 |  0  0
11  -8.899e-05  -3.801e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.9496  1e-01   1  1  1 |  0  0
12  -1.428e-05  -6.330e-05  +1e-03  2e-07  3e-09  4e-07  6e-06  0.9678  1e-01   2  1  1 |  0  0
13  -5.008e-06  -2.203e-05  +4e-04  6e-08  1e-09  1e-07  2e-06  0.9288  3e-01   1  1  1 |  0  0
14  -1.249e-06  -5.332e-06  +1e-04  2e-08  2e-10  3e-08  5e-07  0.8453  1e-01   2  1  1 |  0  0
15  -1.117e-07  -4.592e-07  +8e-06  1e-09  2e-11  2e-09  4e-08  0.9329  2e-02   1  1  1 |  0  0
16  -1.327e-08  -2.673e-08  +3e-07  5e-11  8e-13  1e-10  2e-09  0.9664  5e-03   2  1  1 |  0  0
17  -9.787e-09  -1.141e-08  +4e-08  6e-12  1e-13  1e-11  2e-10  0.8807  1e-03   2  1  1 |  0  0
18  -9.438e-09  -9.880e-09  +1e-08  2e-12  3e-14  3e-12  5e-11  0.8031  9e-02   2  1  1 |  0  0
19  -9.315e-09  -9.344e-09  +7e-10  1e-13  2e-15  2e-13  3e-12  0.9357  1e-03   1  1  1 |  0  0

OPTIMAL (within feastol=1.1e-13, reltol=7.4e-02, abstol=6.9e-10).
Runtime: 0.009300 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.219e+00  -1.207e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.011e+00  -2.736e+01  +4e+02  1e-01  4e-03  6e-01  2e+00  0.5568  2e-01   2  2  1 |  0  0
 2  -2.228e-01  -6.522e+00  +1e+02  3e-02  6e-04  1e-01  6e-01  0.7201  5e-02   2  2  2 |  0  0
 3  -1.819e-01  -1.281e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8352  5e-02   2  2  2 |  0  0
 4  -1.051e-01  -6.271e-01  +1e+01  2e-03  3e-05  8e-03  6e-02  0.6739  2e-01   2  2  2 |  0  0
 5  -7.074e-02  -3.774e-01  +7e+00  1e-03  2e-05  4e-03  4e-02  0.5261  2e-01   2  2  2 |  0  0
 6  -4.873e-02  -2.227e-01  +4e+00  7e-04  1e-05  2e-03  2e-02  0.8952  5e-01   2  2  2 |  0  0
 7  -1.741e-02  -7.626e-02  +1e+00  2e-04  3e-06  5e-04  7e-03  0.7465  1e-01   1  1  1 |  0  0
 8  -3.943e-03  -1.691e-02  +3e-01  5e-05  8e-07  1e-04  2e-03  0.8246  6e-02   1  1  1 |  0  0
 9  -1.543e-03  -6.453e-03  +1e-01  2e-05  3e-07  4e-05  6e-04  0.8204  2e-01   1  1  1 |  0  0
10  -4.677e-04  -2.132e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8878  3e-01   1  1  1 |  0  0
11  -8.896e-05  -3.799e-04  +7e-03  1e-06  2e-08  2e-06  3e-05  0.9496  1e-01   1  1  1 |  0  0
12  -1.427e-05  -6.325e-05  +1e-03  2e-07  3e-09  4e-07  6e-06  0.9677  1e-01   2  1  1 |  0  0
13  -5.005e-06  -2.204e-05  +4e-04  6e-08  1e-09  1e-07  2e-06  0.9269  3e-01   1  1  1 |  0  0
14  -1.245e-06  -5.343e-06  +1e-04  2e-08  2e-10  3e-08  5e-07  0.8453  1e-01   2  1  1 |  0  0
15  -1.031e-07  -4.500e-07  +8e-06  1e-09  2e-11  2e-09  4e-08  0.9333  2e-02   2  1  1 |  0  0
16  -4.801e-09  -1.808e-08  +3e-07  5e-11  8e-13  1e-10  2e-09  0.9671  6e-03   2  1  1 |  0  0
17  -1.359e-09  -2.961e-09  +4e-08  6e-12  1e-13  1e-11  2e-10  0.8805  1e-03   2  1  1 |  0  0
18  -1.017e-09  -1.459e-09  +1e-08  2e-12  3e-14  3e-12  5e-11  0.8017  1e-01   2  1  1 |  0  0
19  -8.933e-10  -9.236e-10  +7e-10  1e-13  2e-15  2e-13  4e-12  0.9329  2e-03   2  1  1 |  0  0

OPTIMAL (within feastol=1.1e-13, reltol=8.1e-01, abstol=7.2e-10).
Runtime: 0.009491 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.590e+01  -1.554e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +4.637e-01  -7.921e+01  +7e+02  3e-01  1e-02  1e+00  4e+00  0.2458  5e-01   1  2  2 |  0  0
 2  -3.812e+00  -1.812e+01  +3e+02  5e-02  2e-03  5e-01  1e+00  0.7221  1e-01   1  1  1 |  0  0
 3  -6.427e+00  -1.121e+01  +1e+02  2e-02  5e-04  2e-01  5e-01  0.6666  9e-02   2  2  2 |  0  0
 4  -7.610e+00  -8.557e+00  +2e+01  3e-03  8e-05  3e-02  1e-01  0.8217  4e-02   2  2  2 |  0  0
 5  -7.743e+00  -8.049e+00  +7e+00  9e-04  2e-05  7e-03  4e-02  0.7718  1e-01   2  2  2 |  0  0
 6  -7.752e+00  -7.992e+00  +6e+00  7e-04  2e-05  5e-03  3e-02  0.3845  4e-01   1  1  1 |  0  0
 7  -7.779e+00  -7.821e+00  +1e+00  1e-04  3e-06  8e-04  5e-03  0.8343  1e-02   1  1  1 |  0  0
 8  -7.783e+00  -7.798e+00  +4e-01  5e-05  1e-06  2e-04  2e-03  0.7437  1e-01   1  1  1 |  0  0
 9  -7.785e+00  -7.787e+00  +4e-02  5e-06  1e-07  3e-05  2e-04  0.9008  7e-03   1  1  1 |  0  0
10  -7.785e+00  -7.786e+00  +8e-03  9e-07  2e-08  3e-06  4e-05  0.9264  1e-01   1  1  1 |  0  0
11  -7.785e+00  -7.785e+00  +2e-03  3e-07  8e-09  1e-06  1e-05  0.7955  1e-01   2  1  1 |  0  0
12  -7.785e+00  -7.785e+00  +5e-04  6e-08  1e-09  2e-07  2e-06  0.8667  7e-02   1  1  1 |  0  0
13  -7.785e+00  -7.785e+00  +1e-04  2e-08  4e-10  5e-08  7e-07  0.8545  2e-01   2  1  1 |  0  0
14  -7.785e+00  -7.785e+00  +1e-05  1e-09  4e-11  4e-09  6e-08  0.9116  2e-03   2  1  1 |  0  0
15  -7.785e+00  -7.785e+00  +1e-06  2e-10  4e-12  4e-10  6e-09  0.9569  6e-02   2  1  1 |  0  0
16  -7.785e+00  -7.785e+00  +4e-08  5e-12  1e-13  1e-11  2e-10  0.9693  1e-04   1  1  1 |  0  0

OPTIMAL (within feastol=4.6e-12, reltol=4.9e-09, abstol=3.8e-08).
Runtime: 0.008290 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.768e+00  -1.088e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.748e+00  -3.727e+01  +5e+02  2e-01  2e-02  2e+00  2e+00  0.3896  4e-01   1  1  1 |  0  0
 2  +3.022e-01  -3.796e+00  +1e+02  2e-02  2e-03  9e-01  6e-01  0.8691  1e-01   1  1  1 |  0  0
 3  -1.864e-01  -2.293e+00  +6e+01  1e-02  9e-04  4e-01  3e-01  0.5537  2e-01   1  1  1 |  0  0
 4  -4.269e-01  -1.153e+00  +2e+01  3e-03  3e-04  1e-01  1e-01  0.6951  8e-02   1  1  2 |  0  0
 5  -4.978e-01  -7.830e-01  +8e+00  1e-03  9e-05  4e-02  4e-02  0.7016  1e-01   1  1  2 |  0  0
 6  -5.175e-01  -6.992e-01  +5e+00  7e-04  5e-05  1e-02  3e-02  0.6609  4e-01   1  1  1 |  0  0
 7  -5.406e-01  -5.960e-01  +2e+00  2e-04  2e-05  3e-03  8e-03  0.7816  1e-01   1  1  1 |  0  0
 8  -5.491e-01  -5.618e-01  +4e-01  4e-05  4e-06  6e-04  2e-03  0.8109  5e-02   1  1  1 |  0  0
 9  -5.511e-01  -5.550e-01  +1e-01  1e-05  1e-06  3e-05  6e-04  0.9890  3e-01   1  1  1 |  0  0
10  -5.522e-01  -5.527e-01  +1e-02  2e-06  1e-07  3e-06  7e-05  0.8956  3e-02   1  1  1 |  0  0
11  -5.523e-01  -5.524e-01  +4e-03  5e-07  4e-08  9e-07  2e-05  0.9027  2e-01   1  1  1 |  0  0
12  -5.523e-01  -5.524e-01  +4e-04  5e-08  4e-09  9e-08  2e-06  0.9073  5e-03   1  1  1 |  0  0
13  -5.524e-01  -5.524e-01  +3e-05  3e-09  3e-10  6e-09  1e-07  0.9687  4e-02   2  1  1 |  0  0
14  -5.524e-01  -5.524e-01  +1e-06  1e-10  1e-11  2e-10  5e-09  0.9690  5e-03   1  1  1 |  0  0
15  -5.524e-01  -5.524e-01  +4e-08  4e-12  4e-13  7e-12  2e-10  0.9662  2e-04   2  1  1 |  0  0
16  -5.524e-01  -5.524e-01  +4e-09  5e-13  2e-13  8e-13  2e-11  0.9144  3e-02   2  1  1 |  0  0

OPTIMAL (within feastol=5.0e-13, reltol=7.7e-09, abstol=4.3e-09).
Runtime: 0.007822 seconds.

-------------------------------------------------------------------------------
                                    Summary

(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.012e-02
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.971e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.099e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.871e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 2.577e-03
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.871e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.094e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.940e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.959e-04
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.940e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.110e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.002e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.028e-04
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.002e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.080e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.003e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.697e-05
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.003e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.086e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.004e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 2.839e-06
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.004e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.108e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.755e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 4.576e-07
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.755e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.110e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.046e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 7.202e-08
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.046e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.127e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.416e+00  -1.119e+02  +7e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.493e+00  -2.898e+01  +4e+02  2e-01  6e-03  8e-01  2e+00  0.4784  2e-01   1  1  1 |  0  0
 2  +2.359e-01  -4.554e+00  +1e+02  2e-02  6e-04  1e-01  5e-01  0.7999  6e-02   2  1  2 |  0  0
 3  -1.022e-01  -1.035e+00  +2e+01  4e-03  9e-05  2e-02  1e-01  0.8560  1e-01   2  2  2 |  0  0
 4  -7.966e-02  -6.419e-01  +1e+01  2e-03  5e-05  1e-02  7e-02  0.5299  3e-01   2  2  2 |  0  0
 5  -3.612e-02  -2.442e-01  +5e+00  9e-04  2e-05  4e-03  3e-02  0.7070  1e-01   2  2  2 |  0  0
 6  -3.051e-02  -1.710e-01  +4e+00  6e-04  1e-05  2e-03  2e-02  0.6119  5e-01   1  2  2 |  0  0
 7  -2.112e-02  -7.951e-02  +2e+00  2e-04  5e-06  6e-04  7e-03  0.8026  3e-01   1  2  1 |  0  0
 8  -1.312e-02  -3.155e-02  +5e-01  7e-05  1e-06  1e-04  2e-03  0.9890  3e-01   1  1  1 |  0  0
 9  -1.082e-02  -1.471e-02  +1e-01  2e-05  3e-07  3e-05  5e-04  0.8370  6e-02   1  1  1 |  0  0
10  -1.036e-02  -1.197e-02  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8192  3e-01   1  1  1 |  0  0
11  -1.024e-02  -1.084e-02  +2e-02  2e-06  5e-08  4e-06  8e-05  0.8105  2e-01   1  1  1 |  0  0
12  -1.015e-02  -1.032e-02  +5e-03  7e-07  1e-08  1e-06  2e-05  0.9878  3e-01   2  1  1 |  0  0
13  -1.013e-02  -1.016e-02  +9e-04  1e-07  3e-09  2e-07  4e-06  0.8524  5e-02   2  1  1 |  0  0
14  -1.012e-02  -1.014e-02  +3e-04  5e-08  1e-09  8e-08  2e-06  0.7790  2e-01   2  1  1 |  0  0
15  -1.012e-02  -1.013e-02  +9e-05  1e-08  3e-10  2e-08  5e-07  0.8742  2e-01   2  1  1 |  0  0
16  -1.012e-02  -1.012e-02  +2e-05  3e-09  5e-11  5e-09  9e-08  0.9531  1e-01   1  1  1 |  0  0
17  -1.012e-02  -1.012e-02  +5e-06  8e-10  2e-11  1e-09  3e-08  0.8389  2e-01   2  1  1 |  0  0
18  -1.012e-02  -1.012e-02  +2e-06  3e-10  6e-12  5e-10  1e-08  0.7715  2e-01   2  1  1 |  0  0
19  -1.012e-02  -1.012e-02  +4e-07  6e-11  1e-12  1e-10  2e-09  0.9107  1e-01   2  1  1 |  0  0
20  -1.012e-02  -1.012e-02  +1e-07  2e-11  4e-13  3e-11  7e-10  0.7942  2e-01   2  1  1 |  0  0
21  -1.012e-02  -1.012e-02  +3e-08  4e-12  2e-13  7e-12  1e-10  0.9224  1e-01   2  1  1 |  0  0
22  -1.012e-02  -1.012e-02  +8e-09  1e-12  5e-14  2e-12  4e-11  0.8833  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=1.2e-12, reltol=7.9e-07, abstol=8.0e-09).
Runtime: 0.010954 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.494e+00  -1.140e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.070e+00  -2.851e+01  +4e+02  2e-01  5e-03  6e-01  2e+00  0.5168  2e-01   1  1  1 |  0  0
 2  -4.423e-02  -5.443e+00  +1e+02  3e-02  6e-04  1e-01  5e-01  0.7641  6e-02   2  2  2 |  0  0
 3  -1.122e-01  -1.116e+00  +2e+01  4e-03  8e-05  2e-02  1e-01  0.8265  5e-02   2  2  2 |  0  0
 4  -9.675e-02  -7.336e-01  +2e+01  3e-03  5e-05  1e-02  8e-02  0.4909  3e-01   2  2  2 |  0  0
 5  -3.603e-02  -2.503e-01  +5e+00  9e-04  1e-05  3e-03  3e-02  0.7528  1e-01   2  2  2 |  0  0
 6  -3.005e-02  -1.711e-01  +4e+00  6e-04  9e-06  2e-03  2e-02  0.5007  3e-01   1  2  1 |  0  0
 7  -2.085e-02  -1.063e-01  +2e+00  4e-04  6e-06  8e-04  1e-02  0.8553  5e-01   1  2  2 |  0  0
 8  -7.083e-03  -2.593e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8922  1e-01   1  1  1 |  0  0
 9  -4.135e-03  -1.143e-02  +2e-01  3e-05  5e-07  5e-05  9e-04  0.9131  3e-01   1  1  1 |  0  0
10  -3.116e-03  -5.213e-03  +5e-02  8e-06  1e-07  2e-05  3e-04  0.8090  1e-01   1  1  1 |  0  0
11  -2.775e-03  -3.805e-03  +3e-02  4e-06  7e-08  7e-06  1e-04  0.9099  4e-01   1  1  1 |  0  0
12  -2.618e-03  -2.813e-03  +5e-03  8e-07  1e-08  1e-06  2e-05  0.8777  8e-02   1  1  1 |  0  0
13  -2.592e-03  -2.658e-03  +2e-03  3e-07  4e-09  5e-07  8e-06  0.9890  3e-01   2  1  1 |  0  0
14  -2.579e-03  -2.586e-03  +2e-04  3e-08  5e-10  6e-08  1e-06  0.8972  2e-02   1  1  1 |  0  0
15  -2.577e-03  -2.580e-03  +6e-05  1e-08  2e-10  2e-08  3e-07  0.8142  2e-01   2  1  1 |  0  0
16  -2.577e-03  -2.578e-03  +3e-05  5e-09  9e-11  1e-08  2e-07  0.6778  3e-01   1  1  1 |  0  0
17  -2.577e-03  -2.577e-03  +9e-06  1e-09  2e-11  2e-09  4e-08  0.9596  2e-01   1  1  1 |  0  0
18  -2.577e-03  -2.577e-03  +2e-06  4e-10  6e-12  7e-10  1e-08  0.8989  2e-01   2  1  1 |  0  0
19  -2.577e-03  -2.577e-03  +5e-07  7e-11  1e-12  1e-10  2e-09  0.8538  6e-02   2  1  1 |  0  0
20  -2.577e-03  -2.577e-03  +1e-07  2e-11  4e-13  4e-11  7e-10  0.9490  3e-01   1  1  1 |  0  0
21  -2.577e-03  -2.577e-03  +5e-08  8e-12  2e-13  1e-11  2e-10  0.7978  2e-01   2  1  1 |  0  0
22  -2.577e-03  -2.577e-03  +8e-09  1e-12  4e-14  2e-12  4e-11  0.8816  5e-02   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=3.2e-06, abstol=8.3e-09).
Runtime: 0.010896 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.496e+00  -1.152e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +1.110e+00  -2.819e+01  +4e+02  2e-01  4e-03  6e-01  2e+00  0.5397  2e-01   2  2  1 |  0  0
 2  -2.416e-01  -5.804e+00  +1e+02  3e-02  5e-04  1e-01  6e-01  0.7498  6e-02   2  2  2 |  0  0
 3  -1.335e-01  -1.162e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8248  5e-02   2  2  2 |  0  0
 4  -1.132e-01  -7.634e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4933  3e-01   2  2  2 |  0  0
 5  -4.516e-02  -2.804e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7280  1e-01   2  2  2 |  0  0
 6  -3.525e-02  -1.851e-01  +4e+00  6e-04  9e-06  2e-03  2e-02  0.5254  3e-01   2  2  2 |  0  0
 7  -2.358e-02  -1.158e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8451  5e-01   1  2  2 |  0  0
 8  -6.101e-03  -2.680e-02  +5e-01  8e-05  1e-06  2e-04  3e-03  0.8433  8e-02   1  2  1 |  0  0
 9  -2.692e-03  -1.144e-02  +2e-01  4e-05  5e-07  7e-05  1e-03  0.8643  3e-01   1  1  1 |  0  0
10  -1.268e-03  -3.580e-03  +6e-02  9e-06  1e-07  2e-05  3e-04  0.8391  1e-01   1  1  1 |  0  0
11  -8.239e-04  -1.846e-03  +3e-02  4e-06  6e-08  8e-06  1e-04  0.9326  4e-01   1  1  1 |  0  0
12  -6.396e-04  -8.140e-04  +4e-03  7e-07  1e-08  1e-06  2e-05  0.8957  7e-02   1  1  1 |  0  0
13  -6.086e-04  -6.519e-04  +1e-03  2e-07  3e-09  3e-07  5e-06  0.9890  2e-01   1  1  1 |  0  0
14  -5.999e-04  -6.146e-04  +4e-04  6e-08  9e-10  1e-07  2e-06  0.8013  2e-01   2  1  1 |  0  0
15  -5.965e-04  -5.986e-04  +5e-05  8e-09  1e-10  2e-08  3e-07  0.9221  7e-02   2  1  1 |  0  0
16  -5.960e-04  -5.962e-04  +6e-06  1e-09  1e-11  2e-09  3e-08  0.9103  3e-02   1  1  1 |  0  0
17  -5.959e-04  -5.960e-04  +2e-06  3e-10  5e-12  6e-10  1e-08  0.8584  2e-01   1  1  1 |  0  0
18  -5.959e-04  -5.959e-04  +3e-07  4e-11  6e-13  7e-11  1e-09  0.8826  1e-02   2  1  1 |  0  0
19  -5.959e-04  -5.959e-04  +9e-08  1e-11  2e-13  3e-11  4e-10  0.7914  2e-01   2  1  1 |  0  0
20  -5.959e-04  -5.959e-04  +3e-08  5e-12  9e-14  1e-11  2e-10  0.7762  2e-01   1  1  1 |  0  0
21  -5.959e-04  -5.959e-04  +1e-08  2e-12  3e-14  3e-12  5e-11  0.9099  3e-01   2  1  1 |  0  0
22  -5.959e-04  -5.959e-04  +9e-10  2e-13  1e-14  3e-13  5e-12  0.9890  8e-02   1  1  1 |  0  0

OPTIMAL (within feastol=1.5e-13, reltol=1.6e-06, abstol=9.3e-10).
Runtime: 0.011059 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.502e+00  -1.156e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +6.574e-01  -2.812e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5498  2e-01   2  2  1 |  0  0
 2  -3.383e-01  -5.929e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7456  6e-02   2  2  2 |  0  0
 3  -1.437e-01  -1.175e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8252  5e-02   2  2  2 |  0  0
 4  -1.218e-01  -7.776e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4912  3e-01   2  2  2 |  0  0
 5  -4.921e-02  -2.901e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7183  1e-01   2  2  2 |  0  0
 6  -3.815e-02  -1.913e-01  +4e+00  6e-04  9e-06  2e-03  2e-02  0.5384  3e-01   2  2  2 |  0  0
 7  -2.462e-02  -1.161e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8676  5e-01   1  2  2 |  0  0
 8  -5.949e-03  -2.662e-02  +5e-01  8e-05  1e-06  2e-04  3e-03  0.8297  7e-02   1  2  1 |  0  0
 9  -2.229e-03  -1.055e-02  +2e-01  3e-05  5e-07  6e-05  1e-03  0.9119  3e-01   1  1  1 |  0  0
10  -7.328e-04  -2.752e-03  +5e-02  8e-06  1e-07  2e-05  2e-04  0.8465  1e-01   1  1  1 |  0  0
11  -3.033e-04  -1.134e-03  +2e-02  3e-06  5e-08  6e-06  1e-04  0.9526  4e-01   1  1  1 |  0  0
12  -1.454e-04  -3.063e-04  +4e-03  6e-07  9e-09  1e-06  2e-05  0.8824  9e-02   1  1  1 |  0  0
13  -1.191e-04  -1.744e-04  +1e-03  2e-07  3e-09  4e-07  7e-06  0.8335  2e-01   2  1  1 |  0  0
14  -1.100e-04  -1.353e-04  +6e-04  1e-07  1e-09  2e-07  3e-06  0.7945  3e-01   2  1  1 |  0  0
15  -1.039e-04  -1.073e-04  +8e-05  1e-08  2e-10  3e-08  4e-07  0.9223  6e-02   2  1  1 |  0  0
16  -1.030e-04  -1.038e-04  +2e-05  3e-09  4e-11  6e-09  1e-07  0.8145  5e-02   1  1  1 |  0  0
17  -1.028e-04  -1.030e-04  +5e-06  7e-10  1e-11  1e-09  2e-08  0.8720  1e-01   1  1  1 |  0  0
18  -1.028e-04  -1.029e-04  +2e-06  3e-10  4e-12  6e-10  1e-08  0.7609  3e-01   2  1  1 |  0  0
19  -1.028e-04  -1.028e-04  +3e-07  4e-11  6e-13  8e-11  1e-09  0.9275  6e-02   1  1  1 |  0  0
20  -1.028e-04  -1.028e-04  +6e-08  1e-11  1e-13  2e-11  3e-10  0.8624  1e-01   2  1  1 |  0  0
21  -1.028e-04  -1.028e-04  +2e-08  3e-12  5e-14  6e-12  9e-11  0.7992  1e-01   2  1  1 |  0  0
22  -1.028e-04  -1.028e-04  +6e-09  1e-12  2e-14  2e-12  3e-11  0.9080  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=9.7e-13, reltol=5.9e-05, abstol=6.0e-09).
Runtime: 0.010764 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.507e+00  -1.158e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.698e-01  -2.811e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5541  2e-01   2  2  1 |  0  0
 2  -3.796e-01  -5.975e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7444  6e-02   2  2  2 |  0  0
 3  -1.480e-01  -1.179e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8255  5e-02   2  2  2 |  0  0
 4  -1.258e-01  -7.843e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4891  3e-01   2  2  2 |  0  0
 5  -5.090e-02  -2.935e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7149  1e-01   2  2  2 |  0  0
 6  -3.949e-02  -1.937e-01  +4e+00  7e-04  9e-06  2e-03  2e-02  0.5457  3e-01   2  2  2 |  0  0
 7  -2.494e-02  -1.150e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8829  5e-01   1  2  2 |  0  0
 8  -5.946e-03  -2.632e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8261  7e-02   1  2  1 |  0  0
 9  -2.011e-03  -9.620e-03  +2e-01  3e-05  4e-07  6e-05  9e-04  0.9731  4e-01   1  1  1 |  0  0
10  -5.662e-04  -2.292e-03  +4e-02  7e-06  1e-07  1e-05  2e-04  0.8469  9e-02   1  1  1 |  0  0
11  -1.905e-04  -8.944e-04  +2e-02  3e-06  4e-08  5e-06  9e-05  0.9595  4e-01   1  1  1 |  0  0
12  -6.087e-05  -2.241e-04  +4e-03  7e-07  9e-09  1e-06  2e-05  0.8720  1e-01   2  1  1 |  0  0
13  -3.614e-05  -1.010e-04  +2e-03  3e-07  4e-09  5e-07  8e-06  0.7343  2e-01   2  1  1 |  0  0
14  -2.626e-05  -5.846e-05  +8e-04  1e-07  2e-09  2e-07  4e-06  0.8082  4e-01   1  1  1 |  0  0
15  -1.846e-05  -2.310e-05  +1e-04  2e-08  3e-10  3e-08  6e-07  0.9176  7e-02   1  1  1 |  0  0
16  -1.730e-05  -1.833e-05  +3e-05  4e-09  6e-11  8e-09  1e-07  0.8303  6e-02   1  1  1 |  0  0
17  -1.705e-05  -1.732e-05  +7e-06  1e-09  1e-11  2e-09  3e-08  0.8189  9e-02   2  1  1 |  0  0
18  -1.699e-05  -1.708e-05  +2e-06  3e-10  5e-12  6e-10  1e-08  0.8579  2e-01   1  1  1 |  0  0
19  -1.697e-05  -1.698e-05  +3e-07  4e-11  6e-13  8e-11  1e-09  0.8902  2e-02   2  1  1 |  0  0
20  -1.697e-05  -1.697e-05  +9e-08  1e-11  2e-13  3e-11  4e-10  0.7613  1e-01   2  1  1 |  0  0
21  -1.697e-05  -1.697e-05  +3e-08  5e-12  8e-14  1e-11  2e-10  0.8110  2e-01   2  1  1 |  0  0
22  -1.697e-05  -1.697e-05  +6e-09  1e-12  2e-14  2e-12  3e-11  0.9715  2e-01   1  1  1 |  0  0

OPTIMAL (within feastol=1.0e-12, reltol=3.7e-04, abstol=6.4e-09).
Runtime: 0.010691 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.509e+00  -1.159e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.933e-01  -2.811e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5558  2e-01   2  2  1 |  0  0
 2  -3.964e-01  -5.993e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7439  6e-02   2  2  2 |  0  0
 3  -1.497e-01  -1.181e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8256  5e-02   2  2  2 |  0  0
 4  -1.274e-01  -7.869e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4881  3e-01   2  2  2 |  0  0
 5  -5.160e-02  -2.948e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7136  1e-01   2  2  2 |  0  0
 6  -4.006e-02  -1.945e-01  +4e+00  7e-04  9e-06  2e-03  2e-02  0.5494  3e-01   2  2  2 |  0  0
 7  -2.504e-02  -1.143e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8901  5e-01   1  2  2 |  0  0
 8  -5.949e-03  -2.614e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8251  6e-02   1  2  1 |  0  0
 9  -1.991e-03  -9.455e-03  +2e-01  3e-05  4e-07  6e-05  9e-04  0.9890  4e-01   1  1  1 |  0  0
10  -4.652e-04  -1.901e-03  +4e-02  6e-06  8e-08  1e-05  2e-04  0.8723  7e-02   1  1  1 |  0  0
11  -1.432e-04  -6.635e-04  +1e-02  2e-06  3e-08  4e-06  6e-05  0.8969  3e-01   1  1  1 |  0  0
12  -3.074e-05  -1.276e-04  +2e-03  4e-07  5e-09  7e-07  1e-05  0.8801  8e-02   1  1  1 |  0  0
13  -1.151e-05  -3.886e-05  +7e-04  1e-07  2e-09  2e-07  3e-06  0.8309  1e-01   1  1  1 |  0  0
14  -5.918e-06  -1.607e-05  +3e-04  4e-08  6e-10  8e-08  1e-06  0.8413  3e-01   2  1  1 |  0  0
15  -3.260e-06  -4.577e-06  +3e-05  5e-09  7e-11  1e-08  2e-07  0.9150  5e-02   2  1  1 |  0  0
16  -2.916e-06  -3.171e-06  +6e-06  1e-09  1e-11  2e-09  3e-08  0.8418  4e-02   3  1  1 |  0  0
17  -2.867e-06  -2.960e-06  +2e-06  4e-10  5e-12  7e-10  1e-08  0.7999  2e-01   3  1  1 |  0  0
18  -2.849e-06  -2.883e-06  +8e-07  1e-10  2e-12  3e-10  4e-09  0.7889  2e-01   2  1  1 |  0  0
19  -2.840e-06  -2.844e-06  +1e-07  2e-11  3e-13  3e-11  5e-10  0.9000  4e-02   2  1  1 |  0  0
20  -2.839e-06  -2.840e-06  +4e-08  6e-12  9e-14  1e-11  2e-10  0.8118  2e-01   2  1  1 |  0  0
21  -2.839e-06  -2.839e-06  +1e-08  2e-12  3e-14  4e-12  6e-11  0.8003  1e-01   2  1  1 |  0  0
22  -2.839e-06  -2.839e-06  +5e-09  8e-13  1e-14  1e-12  2e-11  0.8485  3e-01   2  1  1 |  0  0

OPTIMAL (within feastol=7.9e-13, reltol=1.7e-03, abstol=4.8e-09).
Runtime: 0.011047 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================

(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.044e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.132e-08
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.044e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.077e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.002e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.803e-09
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.002e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.132e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.013e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 2.792e-10
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.013e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 1.095e-02 seconds
Reranking users:   0%|          | 10/2064 [00:03<11:04,  3.09it/s](CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.917e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 7.735e+00
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.917e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 7.551e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.694e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 4.019e-01
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.694e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.444e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.959e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.698e-02
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.959e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.587e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.967e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.347e-03
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.967e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.394e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.009e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 4.628e-04
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.009e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.207e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.510e+00  -1.160e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.449e-01  -2.811e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5569  2e-01   2  2  1 |  0  0
 2  -4.070e-01  -6.004e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7437  6e-02   2  2  2 |  0  0
 3  -1.508e-01  -1.181e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8257  5e-02   2  2  2 |  0  0
 4  -1.285e-01  -7.886e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4874  3e-01   2  2  2 |  0  0
 5  -5.203e-02  -2.955e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7127  1e-01   2  2  2 |  0  0
 6  -4.042e-02  -1.951e-01  +4e+00  7e-04  9e-06  2e-03  2e-02  0.5519  3e-01   2  2  2 |  0  0
 7  -2.508e-02  -1.138e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8951  5e-01   1  2  2 |  0  0
 8  -5.950e-03  -2.600e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8246  6e-02   1  2  1 |  0  0
 9  -2.031e-03  -9.545e-03  +2e-01  3e-05  4e-07  6e-05  9e-04  0.9890  4e-01   1  1  1 |  0  0
10  -4.252e-04  -1.737e-03  +3e-02  5e-06  7e-08  1e-05  2e-04  0.8835  7e-02   1  1  1 |  0  0
11  -1.293e-04  -5.890e-04  +1e-02  2e-06  3e-08  3e-06  6e-05  0.8592  2e-01   1  1  1 |  0  0
12  -2.813e-05  -1.228e-04  +2e-03  4e-07  5e-09  7e-07  1e-05  0.8777  1e-01   1  1  1 |  0  0
13  -7.808e-06  -3.210e-05  +6e-04  1e-07  1e-09  2e-07  3e-06  0.8235  1e-01   1  1  1 |  0  0
14  -2.762e-06  -1.182e-05  +2e-04  4e-08  5e-10  7e-08  1e-06  0.8456  3e-01   1  1  1 |  0  0
15  -3.316e-07  -1.336e-06  +2e-05  4e-09  6e-11  8e-09  1e-07  0.9318  5e-02   2  1  1 |  0  0
16  -7.810e-08  -2.934e-07  +5e-06  9e-10  1e-11  2e-09  3e-08  0.8181  4e-02   2  1  1 |  0  0
17  -4.132e-08  -1.363e-07  +2e-06  4e-10  5e-12  7e-10  1e-08  0.7106  2e-01   2  1  1 |  0  0
18  -2.524e-08  -7.008e-08  +1e-06  2e-10  2e-12  3e-10  5e-09  0.7328  3e-01   2  1  1 |  0  0
19  -1.319e-08  -1.898e-08  +1e-07  2e-11  3e-13  4e-11  7e-10  0.9115  4e-02   2  1  1 |  0  0
20  -1.171e-08  -1.279e-08  +3e-08  4e-12  7e-14  8e-12  1e-10  0.9890  2e-01   2  1  1 |  0  0
21  -1.144e-08  -1.167e-08  +6e-09  9e-13  2e-14  2e-12  3e-11  0.9162  1e-01   1  1  1 |  0  0

OPTIMAL (within feastol=9.4e-13, reltol=5.0e-01, abstol=5.7e-09).
Runtime: 0.010731 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.510e+00  -1.160e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.429e-01  -2.811e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5569  2e-01   2  2  1 |  0  0
 2  -4.074e-01  -6.004e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7437  6e-02   2  2  2 |  0  0
 3  -1.509e-01  -1.181e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8258  5e-02   2  2  2 |  0  0
 4  -1.285e-01  -7.887e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4874  3e-01   2  2  2 |  0  0
 5  -5.205e-02  -2.956e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7127  1e-01   2  2  2 |  0  0
 6  -4.044e-02  -1.951e-01  +4e+00  7e-04  9e-06  2e-03  2e-02  0.5520  3e-01   2  2  2 |  0  0
 7  -2.508e-02  -1.137e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8953  5e-01   1  2  2 |  0  0
 8  -5.950e-03  -2.600e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8245  6e-02   1  2  1 |  0  0
 9  -2.032e-03  -9.549e-03  +2e-01  3e-05  4e-07  6e-05  9e-04  0.9890  4e-01   1  1  1 |  0  0
10  -4.240e-04  -1.732e-03  +3e-02  5e-06  7e-08  1e-05  2e-04  0.8838  7e-02   1  1  1 |  0  0
11  -1.290e-04  -5.870e-04  +1e-02  2e-06  3e-08  3e-06  6e-05  0.8580  2e-01   1  1  1 |  0  0
12  -2.819e-05  -1.230e-04  +2e-03  4e-07  5e-09  7e-07  1e-05  0.8775  1e-01   1  1  1 |  0  0
13  -7.780e-06  -3.201e-05  +6e-04  1e-07  1e-09  2e-07  3e-06  0.8238  1e-01   2  1  1 |  0  0
14  -2.741e-06  -1.177e-05  +2e-04  4e-08  5e-10  7e-08  1e-06  0.8462  3e-01   2  1  1 |  0  0
15  -3.177e-07  -1.308e-06  +2e-05  4e-09  5e-11  7e-09  1e-07  0.9326  5e-02   2  1  1 |  0  0
16  -6.848e-08  -2.832e-07  +5e-06  9e-10  1e-11  2e-09  3e-08  0.8154  4e-02   1  1  1 |  0  0
17  -3.199e-08  -1.276e-07  +2e-06  4e-10  5e-12  7e-10  1e-08  0.7092  2e-01   1  1  1 |  0  0
18  -1.587e-08  -6.120e-08  +1e-06  2e-10  2e-12  3e-10  5e-09  0.7311  3e-01   2  1  1 |  0  0
19  -3.685e-09  -9.586e-09  +1e-07  2e-11  3e-13  4e-11  7e-10  0.9108  4e-02   2  1  1 |  0  0
20  -2.197e-09  -3.365e-09  +3e-08  5e-12  7e-14  9e-12  1e-10  0.9604  2e-01   1  1  1 |  0  0
21  -1.961e-09  -2.393e-09  +1e-08  2e-12  3e-14  3e-12  5e-11  0.7588  2e-01   3  1  1 |  0  0
22  -1.868e-09  -1.999e-09  +3e-09  5e-13  1e-14  1e-12  2e-11  0.8736  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=5.3e-13, reltol=1.7e+00, abstol=3.2e-09).
Runtime: 0.011118 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -2.510e+00  -1.160e+02  +7e+02  6e-01  2e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +3.421e-01  -2.811e+01  +4e+02  2e-01  4e-03  5e-01  2e+00  0.5569  2e-01   2  2  1 |  0  0
 2  -4.076e-01  -6.004e+00  +1e+02  3e-02  5e-04  1e-01  5e-01  0.7437  6e-02   2  2  2 |  0  0
 3  -1.509e-01  -1.181e+00  +2e+01  5e-03  7e-05  2e-02  1e-01  0.8258  5e-02   2  2  2 |  0  0
 4  -1.285e-01  -7.887e-01  +2e+01  3e-03  4e-05  1e-02  8e-02  0.4874  3e-01   2  2  2 |  0  0
 5  -5.206e-02  -2.956e-01  +6e+00  1e-03  1e-05  4e-03  3e-02  0.7127  1e-01   2  2  2 |  0  0
 6  -4.044e-02  -1.951e-01  +4e+00  7e-04  9e-06  2e-03  2e-02  0.5520  3e-01   2  2  2 |  0  0
 7  -2.508e-02  -1.137e-01  +2e+00  4e-04  5e-06  8e-04  1e-02  0.8954  5e-01   1  2  2 |  0  0
 8  -5.950e-03  -2.599e-02  +5e-01  8e-05  1e-06  2e-04  2e-03  0.8245  6e-02   1  2  1 |  0  0
 9  -2.033e-03  -9.551e-03  +2e-01  3e-05  4e-07  6e-05  9e-04  0.9890  4e-01   1  1  1 |  0  0
10  -4.235e-04  -1.730e-03  +3e-02  5e-06  7e-08  1e-05  2e-04  0.8840  7e-02   1  1  1 |  0  0
11  -1.288e-04  -5.862e-04  +1e-02  2e-06  3e-08  3e-06  6e-05  0.8575  2e-01   1  1  1 |  0  0
12  -2.822e-05  -1.231e-04  +2e-03  4e-07  5e-09  7e-07  1e-05  0.8774  1e-01   1  1  1 |  0  0
13  -7.771e-06  -3.198e-05  +6e-04  1e-07  1e-09  2e-07  3e-06  0.8239  1e-01   2  1  1 |  0  0
14  -2.735e-06  -1.175e-05  +2e-04  4e-08  5e-10  7e-08  1e-06  0.8465  3e-01   1  1  1 |  0  0
15  -3.144e-07  -1.299e-06  +2e-05  4e-09  5e-11  7e-09  1e-07  0.9329  5e-02   1  1  1 |  0  0
16  -6.692e-08  -2.815e-07  +5e-06  9e-10  1e-11  2e-09  3e-08  0.8143  4e-02   1  1  1 |  0  0
17  -3.054e-08  -1.263e-07  +2e-06  4e-10  5e-12  7e-10  1e-08  0.7090  2e-01   2  1  1 |  0  0
18  -1.440e-08  -5.989e-08  +1e-06  2e-10  3e-12  3e-10  5e-09  0.7305  3e-01   2  1  1 |  0  0
19  -2.174e-09  -8.114e-09  +1e-07  2e-11  3e-13  4e-11  7e-10  0.9105  5e-02   1  1  1 |  0  0
20  -6.999e-10  -1.944e-09  +3e-08  5e-12  7e-14  9e-12  2e-10  0.9412  2e-01   2  1  1 |  0  0
21  -4.486e-10  -9.107e-10  +1e-08  2e-12  3e-14  3e-12  6e-11  0.7511  2e-01   2  1  1 |  0  0
22  -3.490e-10  -4.896e-10  +3e-09  8e-13  1e-14  1e-12  2e-11  0.8929  2e-01   2  1  1 |  0  0

OPTIMAL (within feastol=7.7e-13, reltol=9.9e+00, abstol=3.5e-09).
Runtime: 0.010786 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.180e+01  -1.583e+02  +8e+02  6e-01  2e-02  1e+00  4e+00    ---    ---    1  1  - |  -  -
 1  +2.394e+00  -8.279e+01  +7e+02  3e-01  1e-02  1e+00  3e+00  0.2478  4e-01   1  2  2 |  0  0
 2  -2.373e+00  -2.236e+01  +3e+02  7e-02  2e-03  6e-01  1e+00  0.6442  1e-01   1  1  1 |  0  0
 3  -7.025e+00  -1.116e+01  +7e+01  1e-02  4e-04  1e-01  4e-01  0.7860  5e-02   2  2  2 |  0  0
 4  -7.542e+00  -9.267e+00  +3e+01  5e-03  2e-04  4e-02  2e-01  0.6809  2e-01   1  2  2 |  0  0
 5  -7.631e+00  -8.261e+00  +1e+01  2e-03  5e-05  1e-02  6e-02  0.6827  9e-02   1  2  2 |  0  0
 6  -7.707e+00  -7.865e+00  +3e+00  4e-04  1e-05  3e-03  2e-02  0.8074  8e-02   1  1  1 |  0  0
 7  -7.720e+00  -7.800e+00  +2e+00  2e-04  6e-06  1e-03  8e-03  0.7661  3e-01   1  1  1 |  0  0
 8  -7.734e+00  -7.741e+00  +1e-01  2e-05  6e-07  9e-05  7e-04  0.9124  4e-03   1  1  1 |  0  0
 9  -7.735e+00  -7.737e+00  +4e-02  5e-06  1e-07  2e-05  2e-04  0.8135  7e-02   1  1  1 |  0  0
10  -7.735e+00  -7.735e+00  +5e-03  6e-07  2e-08  2e-06  2e-05  0.9176  6e-02   1  1  1 |  0  0
11  -7.735e+00  -7.735e+00  +2e-03  2e-07  6e-09  6e-07  8e-06  0.8184  2e-01   2  1  1 |  0  0
12  -7.735e+00  -7.735e+00  +8e-05  1e-08  3e-10  3e-08  4e-07  0.9470  1e-03   2  1  1 |  0  0
13  -7.735e+00  -7.735e+00  +6e-06  7e-10  2e-11  2e-09  3e-08  0.9890  6e-02   2  1  1 |  0  0
14  -7.735e+00  -7.735e+00  +1e-07  1e-11  4e-13  4e-11  5e-10  0.9804  1e-04   1  1  1 |  0  0
15  -7.735e+00  -7.735e+00  +5e-09  7e-13  2e-14  2e-12  2e-11  0.9552  8e-04   2  1  1 |  0  0

OPTIMAL (within feastol=6.8e-13, reltol=6.4e-10, abstol=5.0e-09).
Runtime: 0.007517 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.458e+00  -1.086e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +2.246e+00  -4.488e+01  +4e+02  2e-01  2e-02  2e+00  2e+00  0.3267  4e-01   1  1  1 |  0  0
 2  +5.409e-01  -3.108e+00  +8e+01  2e-02  2e-03  9e-01  5e-01  0.9339  1e-01   1  1  1 |  0  0
 3  +4.278e-02  -2.261e+00  +5e+01  1e-02  9e-04  5e-01  3e-01  0.4556  2e-01   1  1  1 |  0  0
 4  -1.978e-01  -1.320e+00  +3e+01  5e-03  4e-04  2e-01  1e-01  0.5374  8e-02   1  1  2 |  0  0
 5  -3.171e-01  -8.510e-01  +1e+01  2e-03  2e-04  6e-02  7e-02  0.7260  3e-01   1  2  2 |  0  0
 6  -3.603e-01  -6.143e-01  +6e+00  1e-03  7e-05  3e-02  3e-02  0.5808  1e-01   1  1  1 |  0  0
 7  -3.647e-01  -5.841e-01  +5e+00  8e-04  6e-05  2e-02  3e-02  0.4349  6e-01   1  1  1 |  0  0
 8  -3.825e-01  -4.933e-01  +3e+00  4e-04  3e-05  7e-03  1e-02  0.5779  1e-01   1  1  1 |  0  0
 9  -3.960e-01  -4.204e-01  +6e-01  8e-05  6e-06  7e-04  3e-03  0.8991  1e-01   1  1  1 |  0  0
10  -4.001e-01  -4.063e-01  +1e-01  2e-05  2e-06  1e-04  7e-04  0.8390  1e-01   1  1  1 |  0  0
11  -4.016e-01  -4.026e-01  +2e-02  3e-06  2e-07  2e-05  1e-04  0.8886  5e-02   1  1  1 |  0  0
12  -4.018e-01  -4.021e-01  +8e-03  1e-06  8e-08  4e-06  4e-05  0.8435  2e-01   1  1  1 |  0  0
13  -4.019e-01  -4.019e-01  +7e-04  9e-08  7e-09  3e-07  3e-06  0.9293  2e-02   1  1  1 |  0  0
14  -4.019e-01  -4.019e-01  +1e-04  2e-08  1e-09  4e-08  6e-07  0.8881  8e-02   1  1  1 |  0  0
15  -4.019e-01  -4.019e-01  +1e-05  1e-09  1e-10  3e-09  5e-08  0.9511  4e-02   2  1  1 |  0  0
16  -4.019e-01  -4.019e-01  +3e-07  5e-11  4e-12  1e-10  2e-09  0.9694  3e-04   1  1  1 |  0  0
17  -4.019e-01  -4.019e-01  +1e-08  2e-12  2e-13  4e-12  7e-11  0.9735  2e-02   3  1  1 |  0  0
18  -4.019e-01  -4.019e-01  +1e-09  3e-13  5e-14  3e-13  6e-12  0.9192  7e-04   2  1  1 |  0  0

OPTIMAL (within feastol=3.0e-13, reltol=2.9e-09, abstol=1.2e-09).
Runtime: 0.008412 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.513e+00  -1.079e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.213e+00  -3.224e+01  +4e+02  2e-01  1e-02  1e+00  2e+00  0.4202  3e-01   1  1  1 |  0  0
 2  +6.060e-01  -2.706e+00  +7e+01  2e-02  8e-04  3e-01  4e-01  0.8924  8e-02   1  1  1 |  0  0
 3  +9.836e-02  -1.288e+00  +3e+01  6e-03  3e-04  1e-01  2e-01  0.6415  1e-01   1  2  2 |  0  0
 4  -2.146e-03  -9.166e-01  +2e+01  4e-03  2e-04  6e-02  1e-01  0.5164  3e-01   1  2  1 |  0  0
 5  -3.433e-02  -7.462e-01  +2e+01  3e-03  1e-04  3e-02  8e-02  0.5800  6e-01   1  2  2 |  0  0
 6  -5.086e-02  -2.350e-01  +4e+00  7e-04  3e-05  4e-03  2e-02  0.8865  2e-01   1  2  1 |  0  0
 7  -5.481e-02  -1.201e-01  +2e+00  2e-04  1e-05  1e-03  8e-03  0.7669  2e-01   1  2  2 |  0  0
 8  -5.436e-02  -9.019e-02  +8e-01  1e-04  5e-06  4e-04  4e-03  0.7405  4e-01   1  2  2 |  0  0
 9  -5.611e-02  -7.131e-02  +4e-01  5e-05  2e-06  1e-04  2e-03  0.7453  2e-01   1  2  2 |  0  0
10  -5.653e-02  -6.111e-02  +1e-01  2e-05  7e-07  3e-05  5e-04  0.8600  2e-01   1  1  1 |  0  0
11  -5.684e-02  -5.799e-02  +3e-02  4e-06  2e-07  7e-06  1e-04  0.9890  2e-01   1  1  1 |  0  0
12  -5.696e-02  -5.712e-02  +4e-03  6e-07  2e-08  9e-07  2e-05  0.8913  3e-02   1  1  1 |  0  0
13  -5.697e-02  -5.700e-02  +6e-04  9e-08  4e-09  2e-07  3e-06  0.8755  5e-02   1  1  1 |  0  0
14  -5.698e-02  -5.698e-02  +1e-04  2e-08  9e-10  3e-08  7e-07  0.9031  1e-01   1  1  1 |  0  0
15  -5.698e-02  -5.698e-02  +2e-05  2e-09  1e-10  4e-09  8e-08  0.8848  3e-03   2  1  1 |  0  0
16  -5.698e-02  -5.698e-02  +3e-06  5e-10  2e-11  8e-10  2e-08  0.9138  1e-01   1  1  1 |  0  0
17  -5.698e-02  -5.698e-02  +5e-07  8e-11  3e-12  1e-10  2e-09  0.8504  7e-03   2  1  1 |  0  0
18  -5.698e-02  -5.698e-02  +1e-07  2e-11  8e-13  3e-11  6e-10  0.8841  1e-01   1  1  1 |  0  0
19  -5.698e-02  -5.698e-02  +2e-08  3e-12  1e-13  5e-12  1e-10  0.8374  1e-02   1  1  1 |  0  0
20  -5.698e-02  -5.698e-02  +5e-09  7e-13  3e-14  1e-12  2e-11  0.8862  1e-01   2  1  1 |  0  0

OPTIMAL (within feastol=7.4e-13, reltol=8.7e-08, abstol=5.0e-09).
Runtime: 0.009554 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.764e+00  -1.106e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.462e+00  -3.009e+01  +4e+02  2e-01  8e-03  1e+00  2e+00  0.4487  3e-01   1  1  1 |  0  0
 2  +3.993e-01  -2.898e+00  +7e+01  2e-02  5e-04  2e-01  3e-01  0.8809  6e-02   1  1  1 |  0  0
 3  +3.948e-02  -1.121e+00  +3e+01  5e-03  1e-04  5e-02  1e-01  0.7298  2e-01   2  2  2 |  0  0
 4  +3.746e-03  -7.647e-01  +2e+01  3e-03  9e-05  3e-02  8e-02  0.4452  3e-01   1  2  2 |  0  0
 5  -1.185e-02  -6.714e-01  +1e+01  3e-03  8e-05  2e-02  7e-02  0.4136  7e-01   1  2  2 |  0  0

(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.786e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 4.343e-05
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.786e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.421e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.741e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 2.508e-06
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.741e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.034e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.031e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.450e-07
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.031e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.099e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.838e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 8.465e-09
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.838e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.778e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.989e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.032e-10
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.989e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.924e-03 seconds
Reranking users:   1%|          | 11/2064 [00:03<10:14,  3.34it/s](CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.027e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 9.368e+00
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.027e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.655e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.017e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.307e-01
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.017e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 7.999e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.011e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 6.622e-02
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.011e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.908e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS

-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.855e+00  -1.119e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.259e+00  -2.898e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4708  2e-01   1  1  1 |  0  0
 2  +2.320e-01  -3.018e+00  +6e+01  2e-02  5e-04  1e-01  3e-01  0.8802  6e-02   1  1  2 |  0  0
 3  +2.704e-02  -9.225e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.7882  1e-01   2  2  2 |  0  0
 4  -8.415e-03  -6.209e-01  +1e+01  3e-03  6e-05  2e-02  7e-02  0.4867  3e-01   2  2  2 |  0  0
 5  -2.150e-02  -4.762e-01  +1e+01  2e-03  4e-05  9e-03  5e-02  0.5550  5e-01   1  2  2 |  0  0
 6  -1.719e-02  -1.716e-01  +3e+00  6e-04  1e-05  2e-03  2e-02  0.8552  2e-01   1  2  2 |  0  0
 7  -2.655e-03  -5.787e-02  +1e+00  2e-04  5e-06  4e-04  6e-03  0.9517  3e-01   1  2  2 |  0  0
 8  -7.776e-04  -1.405e-02  +3e-01  5e-05  1e-06  9e-05  1e-03  0.8178  7e-02   1  2  2 |  0  0
 9  -3.327e-04  -4.730e-03  +1e-01  2e-05  4e-07  3e-05  5e-04  0.8288  2e-01   1  2  2 |  0  0
10  -9.439e-05  -2.234e-03  +5e-02  8e-06  2e-07  1e-05  2e-04  0.7648  3e-01   1  2  2 |  0  0
11  -5.931e-05  -5.255e-04  +1e-02  2e-06  4e-08  3e-06  5e-05  0.9339  2e-01   1  1  1 |  0  0
12  -4.461e-05  -1.465e-04  +2e-03  4e-07  9e-09  7e-07  1e-05  0.8405  7e-02   1  1  1 |  0  0
13  -4.380e-05  -6.193e-05  +4e-04  7e-08  2e-09  1e-07  2e-06  0.8954  8e-02   2  1  1 |  0  0
14  -4.353e-05  -4.942e-05  +1e-04  2e-08  5e-10  4e-08  7e-07  0.7940  1e-01   2  1  1 |  0  0
15  -4.347e-05  -4.524e-05  +4e-05  6e-09  2e-10  1e-08  2e-07  0.8016  1e-01   2  1  1 |  0  0
16  -4.343e-05  -4.351e-05  +2e-06  3e-10  7e-12  5e-10  9e-09  0.9696  2e-02   2  1  1 |  0  0
17  -4.343e-05  -4.343e-05  +6e-08  1e-11  2e-13  2e-11  3e-10  0.9689  1e-03   2  1  1 |  0  0
18  -4.343e-05  -4.343e-05  +8e-09  1e-12  4e-14  2e-12  4e-11  0.8668  6e-03   2  1  1 |  0  0

OPTIMAL (within feastol=1.3e-12, reltol=1.9e-04, abstol=8.3e-09).
Runtime: 0.009387 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.862e+00  -1.120e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.236e+00  -2.892e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4724  2e-01   1  1  1 |  0  0
 2  +2.265e-01  -3.071e+00  +6e+01  2e-02  5e-04  1e-01  3e-01  0.8776  6e-02   1  1  2 |  0  0
 3  +2.474e-02  -9.417e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.7856  1e-01   2  2  2 |  0  0
 4  -9.510e-03  -5.548e-01  +1e+01  2e-03  5e-05  1e-02  6e-02  0.5765  3e-01   2  2  2 |  0  0
 5  -1.955e-02  -3.941e-01  +8e+00  1e-03  3e-05  7e-03  4e-02  0.5918  5e-01   1  2  2 |  0  0
 6  -1.729e-02  -1.568e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.8668  3e-01   1  2  1 |  0  0
 7  -2.627e-03  -5.694e-02  +1e+00  2e-04  5e-06  4e-04  6e-03  0.9478  4e-01   1  2  2 |  0  0
 8  -9.620e-04  -1.644e-02  +3e-01  6e-05  1e-06  1e-04  2e-03  0.8151  1e-01   1  2  2 |  0  0
 9  -2.451e-04  -3.935e-03  +8e-02  1e-05  3e-07  2e-05  4e-04  0.8303  8e-02   1  2  2 |  0  0
10  -2.343e-05  -1.390e-03  +3e-02  5e-06  1e-07  9e-06  2e-04  0.9431  3e-01   1  1  1 |  0  0
11  -1.460e-05  -3.775e-04  +8e-03  1e-06  3e-08  2e-06  4e-05  0.8679  2e-01   1  1  1 |  0  0
12  -3.630e-06  -1.054e-04  +2e-03  4e-07  9e-09  7e-07  1e-05  0.8466  2e-01   1  1  1 |  0  0
13  -2.720e-06  -1.216e-05  +2e-04  3e-08  8e-10  6e-08  1e-06  0.9201  1e-02   2  1  1 |  0  0
14  -2.533e-06  -3.290e-06  +2e-05  3e-09  7e-11  5e-09  8e-08  0.9645  5e-02   2  1  1 |  0  0
15  -2.511e-06  -2.625e-06  +3e-06  4e-10  1e-11  7e-10  1e-08  0.8595  1e-02   2  1  1 |  0  0
16  -2.508e-06  -2.516e-06  +2e-07  3e-11  7e-13  5e-11  9e-10  0.9695  4e-02   2  1  1 |  0  0
17  -2.508e-06  -2.508e-06  +1e-08  2e-12  6e-14  4e-12  7e-11  0.9246  4e-03   2  1  1 |  0  0
18  -2.508e-06  -2.508e-06  +2e-09  2e-12  2e-14  6e-13  1e-11  0.8645  2e-02   2  1  1 |  0  0

OPTIMAL (within feastol=2.5e-12, reltol=8.6e-04, abstol=2.2e-09).
Runtime: 0.009001 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.864e+00  -1.120e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.231e+00  -2.890e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4728  2e-01   1  1  1 |  0  0
 2  +2.253e-01  -3.086e+00  +6e+01  2e-02  5e-04  1e-01  3e-01  0.8768  6e-02   1  1  2 |  0  0
 3  +2.409e-02  -9.470e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.7850  1e-01   2  2  2 |  0  0
 4  -9.742e-03  -5.399e-01  +1e+01  2e-03  5e-05  1e-02  6e-02  0.5969  3e-01   2  2  2 |  0  0
 5  -1.942e-02  -3.812e-01  +8e+00  1e-03  3e-05  6e-03  4e-02  0.5940  5e-01   1  2  2 |  0  0
 6  -1.712e-02  -1.556e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.8588  3e-01   1  2  1 |  0  0
 7  -2.810e-03  -5.801e-02  +1e+00  2e-04  5e-06  4e-04  6e-03  0.9597  4e-01   1  2  2 |  0  0
 8  -8.933e-04  -1.564e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.8252  1e-01   1  2  2 |  0  0
 9  -2.507e-04  -4.027e-03  +9e-02  1e-05  3e-07  3e-05  4e-04  0.8305  1e-01   1  2  2 |  0  0
10  -4.155e-05  -1.684e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8390  3e-01   1  1  1 |  0  0
11  -1.731e-05  -4.811e-04  +1e-02  2e-06  4e-08  3e-06  5e-05  0.8898  2e-01   1  1  1 |  0  0
12  -1.568e-06  -1.188e-04  +3e-03  4e-07  1e-08  8e-07  1e-05  0.8540  1e-01   2  1  1 |  0  0
13  -4.106e-07  -1.229e-05  +3e-04  4e-08  1e-09  8e-08  1e-06  0.9134  2e-02   2  1  1 |  0  0
14  -1.815e-07  -1.394e-06  +3e-05  4e-09  1e-10  8e-09  1e-07  0.9586  6e-02   2  1  1 |  0  0
15  -1.508e-07  -3.415e-07  +4e-06  7e-10  2e-11  1e-09  2e-08  0.8549  1e-02   2  1  1 |  0  0
16  -1.454e-07  -1.593e-07  +3e-07  5e-11  1e-12  9e-11  2e-09  0.9562  3e-02   2  1  1 |  0  0
17  -1.451e-07  -1.461e-07  +2e-08  4e-12  9e-14  6e-12  1e-10  0.9305  3e-03   2  1  1 |  0  0
18  -1.450e-07  -1.453e-07  +5e-09  6e-12  2e-14  1e-12  2e-11  0.7981  6e-03   2  1  1 |  0  0

OPTIMAL (within feastol=6.1e-12, reltol=3.2e-02, abstol=4.7e-09).
Runtime: 0.008888 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.864e+00  -1.120e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.229e+00  -2.889e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4729  2e-01   1  1  1 |  0  0
 2  +2.249e-01  -3.090e+00  +6e+01  2e-02  5e-04  1e-01  3e-01  0.8766  6e-02   1  1  2 |  0  0
 3  +2.395e-02  -9.480e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.7849  1e-01   2  2  2 |  0  0
 4  -9.799e-03  -5.369e-01  +1e+01  2e-03  5e-05  1e-02  6e-02  0.6011  3e-01   2  2  2 |  0  0
 5  -1.943e-02  -3.787e-01  +8e+00  1e-03  3e-05  6e-03  4e-02  0.5947  5e-01   1  2  2 |  0  0
 6  -1.707e-02  -1.552e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.8569  3e-01   1  2  1 |  0  0
 7  -2.840e-03  -5.821e-02  +1e+00  2e-04  5e-06  4e-04  6e-03  0.9618  4e-01   1  2  2 |  0  0
 8  -8.827e-04  -1.552e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.8271  1e-01   1  2  2 |  0  0
 9  -2.530e-04  -4.058e-03  +9e-02  1e-05  3e-07  3e-05  4e-04  0.8304  1e-01   1  2  2 |  0  0
10  -4.425e-05  -1.730e-03  +4e-02  6e-06  1e-07  1e-05  2e-04  0.8264  3e-01   1  1  1 |  0  0
11  -1.793e-05  -4.963e-04  +1e-02  2e-06  4e-08  3e-06  5e-05  0.8923  2e-01   1  1  1 |  0  0
12  -1.459e-06  -1.199e-04  +3e-03  4e-07  1e-08  8e-07  1e-05  0.8553  1e-01   2  1  1 |  0  0
13  -2.817e-07  -1.248e-05  +3e-04  4e-08  1e-09  8e-08  1e-06  0.9124  2e-02   2  1  1 |  0  0
14  -4.464e-08  -1.240e-06  +3e-05  4e-09  1e-10  8e-09  1e-07  0.9672  7e-02   2  1  1 |  0  0
15  -1.427e-08  -2.095e-07  +4e-06  7e-10  2e-11  1e-09  2e-08  0.8540  2e-02   2  1  1 |  0  0
16  -9.217e-09  -3.510e-08  +6e-07  9e-11  2e-12  2e-10  3e-09  0.8941  3e-02   2  1  1 |  0  0
17  -8.541e-09  -9.659e-09  +3e-08  4e-12  1e-13  7e-12  1e-10  0.9662  1e-02   2  1  1 |  0  0
18  -8.520e-09  -8.728e-09  +5e-09  8e-13  2e-14  1e-12  2e-11  0.8195  6e-03   2  1  1 |  0  0

OPTIMAL (within feastol=7.5e-13, reltol=5.5e-01, abstol=4.7e-09).
Runtime: 0.008743 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.864e+00  -1.120e+02  +6e+02  6e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.229e+00  -2.889e+01  +4e+02  2e-01  7e-03  9e-01  2e+00  0.4730  2e-01   1  1  1 |  0  0
 2  +2.249e-01  -3.090e+00  +6e+01  2e-02  5e-04  1e-01  3e-01  0.8766  6e-02   1  1  2 |  0  0
 3  +2.391e-02  -9.483e-01  +2e+01  4e-03  1e-04  3e-02  1e-01  0.7848  1e-01   2  2  2 |  0  0
 4  -9.813e-03  -5.361e-01  +1e+01  2e-03  5e-05  1e-02  6e-02  0.6022  3e-01   2  2  2 |  0  0
 5  -1.944e-02  -3.780e-01  +8e+00  1e-03  3e-05  6e-03  4e-02  0.5950  5e-01   1  2  2 |  0  0
 6  -1.706e-02  -1.551e-01  +3e+00  5e-04  1e-05  2e-03  2e-02  0.8564  3e-01   1  2  1 |  0  0
 7  -2.847e-03  -5.827e-02  +1e+00  2e-04  5e-06  4e-04  6e-03  0.9624  4e-01   1  2  2 |  0  0
 8  -8.799e-04  -1.548e-02  +3e-01  5e-05  1e-06  1e-04  2e-03  0.8276  1e-01   1  2  2 |  0  0
 9  -2.537e-04  -4.067e-03  +9e-02  1e-05  3e-07  3e-05  4e-04  0.8303  1e-01   1  2  2 |  0  0
10  -4.495e-05  -1.742e-03  +4e-02  6e-06  2e-07  1e-05  2e-04  0.8234  3e-01   1  1  1 |  0  0
11  -1.811e-05  -5.001e-04  +1e-02  2e-06  4e-08  3e-06  5e-05  0.8929  2e-01   1  1  1 |  0  0
12  -1.457e-06  -1.201e-04  +3e-03  4e-07  1e-08  8e-07  1e-05  0.8556  1e-01   1  1  1 |  0  0
13  -2.756e-07  -1.255e-05  +3e-04  4e-08  1e-09  8e-08  1e-06  0.9121  2e-02   1  1  1 |  0  0
14  -3.631e-08  -1.216e-06  +3e-05  4e-09  1e-10  8e-09  1e-07  0.9706  7e-02   2  1  1 |  0  0
15  -5.838e-09  -1.874e-07  +4e-06  7e-10  2e-11  1e-09  2e-08  0.8666  2e-02   2  1  1 |  0  0
16  -1.361e-09  -3.116e-08  +7e-07  1e-10  3e-12  2e-10  3e-09  0.8611  3e-02   2  1  1 |  0  0
17  -5.620e-10  -1.465e-09  +2e-08  3e-12  9e-14  6e-12  1e-10  0.9852  2e-02   2  1  1 |  0  0
18  -5.493e-10  -7.222e-10  +4e-09  1e-12  2e-14  1e-12  2e-11  0.8131  6e-03   2  1  1 |  0  0

OPTIMAL (within feastol=1.4e-12, reltol=7.1e+00, abstol=3.9e-09).
Runtime: 0.008890 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.756e+01  -1.561e+02  +9e+02  7e-01  2e-02  1e+00  5e+00    ---    ---    1  1  - |  -  -
 1  -1.124e+00  -7.672e+01  +8e+02  3e-01  1e-02  1e+00  4e+00  0.2495  4e-01   1  2  2 |  0  0
 2  -6.163e+00  -1.747e+01  +3e+02  4e-02  1e-03  4e-01  1e+00  0.7742  1e-01   1  1  1 |  0  0
 3  -8.496e+00  -1.303e+01  +1e+02  2e-02  4e-04  2e-01  6e-01  0.6764  2e-01   2  2  2 |  0  0
 4  -9.152e+00  -1.041e+01  +3e+01  4e-03  1e-04  4e-02  2e-01  0.7163  2e-02   2  2  2 |  0  0
 5  -9.290e+00  -9.856e+00  +2e+01  2e-03  4e-05  2e-02  8e-02  0.6179  1e-01   1  2  2 |  0  0
 6  -9.308e+00  -9.785e+00  +1e+01  1e-03  4e-05  1e-02  6e-02  0.3215  5e-01   1  2  2 |  0  0
 7  -9.356e+00  -9.463e+00  +3e+00  3e-04  8e-06  2e-03  1e-02  0.8197  6e-02   1  1  1 |  0  0
 8  -9.359e+00  -9.433e+00  +2e+00  2e-04  5e-06  1e-03  1e-02  0.4613  3e-01   1  2  2 |  0  0
 9  -9.365e+00  -9.389e+00  +7e-01  7e-05  2e-06  4e-04  3e-03  0.7638  1e-01   1  1  1 |  0  0
10  -9.366e+00  -9.380e+00  +4e-01  4e-05  1e-06  2e-04  2e-03  0.5443  2e-01   1  2  2 |  0  0
11  -9.367e+00  -9.371e+00  +1e-01  1e-05  3e-07  5e-05  6e-04  0.8117  1e-01   1  1  1 |  0  0
12  -9.368e+00  -9.369e+00  +4e-02  5e-06  1e-07  2e-05  2e-04  0.7175  1e-01   1  2  1 |  0  0
13  -9.368e+00  -9.368e+00  +1e-02  1e-06  3e-08  4e-06  6e-05  0.7984  8e-02   2  1  1 |  0  0
14  -9.368e+00  -9.368e+00  +2e-03  2e-07  5e-09  6e-07  1e-05  0.8936  7e-02   2  1  1 |  0  0
15  -9.368e+00  -9.368e+00  +4e-04  5e-08  1e-09  1e-07  2e-06  0.8051  4e-02   2  1  1 |  0  0
16  -9.368e+00  -9.368e+00  +5e-05  5e-09  1e-10  1e-08  2e-07  0.9623  7e-02   2  1  1 |  0  0
17  -9.368e+00  -9.368e+00  +6e-06  6e-10  2e-11  2e-09  3e-08  0.8781  7e-03   2  1  1 |  0  0
18  -9.368e+00  -9.368e+00  +4e-07  4e-11  1e-12  1e-10  2e-09  0.9842  5e-02   1  1  1 |  0  0
19  -9.368e+00  -9.368e+00  +2e-08  2e-12  6e-14  7e-12  1e-10  0.9388  6e-04   2  1  1 |  0  0

OPTIMAL (within feastol=2.4e-12, reltol=2.5e-09, abstol=2.3e-08).
Runtime: 0.009621 seconds.

-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.6.6
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------

ECOS 2.0.10 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -1.798e+00  -1.073e+02  +7e+02  7e-01  3e-02  1e+00  3e+00    ---    ---    1  1  - |  -  -
 1  +4.766e+00  -2.432e+01  +5e+02  1e-01  9e-03  1e+00  2e+00  0.4677  3e-01   1  1  1 |  0  0
 2  +7.633e-02  -3.023e+00  +9e+01  1e-02  7e-04  2e-01  5e-01  0.8589  7e-02   1  1  1 |  0  0
 3  -4.012e-01  -1.575e+00  +4e+01  5e-03  2e-04  8e-02  2e-01  0.6947  2e-01   2  2  2 |  0  0
 4  -4.703e-01  -8.413e-01  +1e+01  1e-03  6e-05  2e-02  6e-02  0.7175  7e-02   1  2  2 |  0  0
 5  -4.931e-01  -7.916e-01  +1e+01  1e-03  5e-05  1e-02  5e-02  0.4447  5e-01   1  1  1 |  0  0
 6  -5.169e-01  -6.066e-01  +3e+00  3e-04  1e-05  3e-03  2e-02  0.7546  8e-02   2  1  1 |  0  0
 7  -5.224e-01  -5.717e-01  +2e+00  2e-04  7e-06  1e-03  8e-03  0.7067  4e-01   1  2  2 |  0  0
 8  -5.295e-01  -5.373e-01  +3e-01  3e-05  1e-06  1e-04  1e-03  0.9063  7e-02   1  1  1 |  0  0
 9  -5.303e-01  -5.325e-01  +7e-02  8e-06  3e-07  2e-05  4e-04  0.8728  2e-01   1  1  1 |  0  0
10  -5.306e-01  -5.311e-01  +2e-02  2e-06  7e-08  5e-06  8e-05  0.8119  5e-02   1  1  1 |  0  0
11  -5.307e-01  -5.308e-01  +4e-03  4e-07  2e-08  9e-07  2e-05  0.8958  2e-01   1  1  1 |  0  0
12  -5.307e-01  -5.307e-01  +5e-04  5e-08  2e-09  1e-07  3e-06  0.8909  2e-02   2  1  1 |  0  0
13  -5.307e-01  -5.307e-01  +3e-05  3e-09  1e-10  6e-09  2e-07  0.9621  2e-02   1  1  1 |  0  0
14  -5.307e-01  -5.307e-01  +1e-06  1e-10  5e-12  2e-10  6e-09  0.9768  2e-02   2  1  1 |  0  0

(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 1.028e-02 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 5.978e-03
(CVXPY) Jun 21 07:40:16 PM: Compilation took 1.028e-02 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 8.043e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ECOS
(CVXPY) Jun 21 07:40:16 PM: Finished problem compilation (took 9.876e-03 seconds).
(CVXPY) Jun 21 07:40:16 PM: Invoking solver ECOS  to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Problem status: optimal
(CVXPY) Jun 21 07:40:16 PM: Optimal value: 1.172e-04
(CVXPY) Jun 21 07:40:16 PM: Compilation took 9.876e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Solver (including time spent in interface) took 9.522e-03 seconds
(CVXPY) Jun 21 07:40:16 PM: Your problem has 100 variables, 201 constraints, and 0 parameters.
(CVXPY) Jun 21 07:40:16 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 21 07:40:16 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 21 07:40:16 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jun 21 07:40:16 PM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jun 21 07:40:16 PM: Compiling problem (target solver=ECOS).
(CVXPY) Jun 21 07:40:16 PM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> ECOS
(CVXPY) Jun 21 07:40:16 PM: Applying reduction FlipObjective
(CVXPY) Jun 21 07:40:16 PM: Applying reduction Dcp2Cone
(CVXPY) Jun 21 07:40:16 PM: Applying reduction CvxAttr2Constr
(CVXPY) Jun 21 07:40:16 PM: Applying reduction ConeMatrixStuffing

In [ ]:
reranked_score_df = evaluator.evaluate(result_df, K=5)
reranked_score_df = evaluator.evaluate(reranked_score_df, K=10)
reranked_score_df = evaluator.evaluate(reranked_score_df, K=20)
reranked_score_df.describe()

,user,ndcg@5,recall@5,precision@5,ndcg@10,recall@10,precision@10,ndcg@20,recall@20,precision@20
count,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000
mean,35564.367733,0.228575,0.042411,0.094477,0.285809,0.078247,0.092442,0.335594,0.151584,0.092902
std,20797.975208,0.331606,0.087950,0.142984,0.305457,0.119547,0.110308,0.257568,0.162616,0.091146
min,75.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17798.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,35054.000000,0.000000,0.000000,0.000000,0.301030,0.036376,0.100000,0.336699,0.115832,0.050000
75%,53331.000000,0.500000,0.052632,0.200000,0.500000,0.111111,0.100000,0.500000,0.222222,0.150000
max,71534.000000,1.000000,1.000000,0.800000,1.000000,1.000000,0.600000,1.000000,1.000000,0.500000

In [ ]:
# from common.eval import Evaluator
# evaluator = Evaluator()
reranked_user_dpms_df = evaluator.evaluate_dpms_at_k(
    eval_df=result_df,
    feature_engineer=feature_engineer,
    ground_truth_dps_df=user_dps_df,
    k=20,
    actor_k=5,
    rare_threshold=5,
)

reranked_user_dpms_df.describe()

exploded 2064
extracting item features...
merging features...
interaction data count before merging: 41280
interaction data count after merging: 41280
done!
Transformed: Re-index user/item mapping
Transformed: Encoded idx for actorID
Transformed: Encoded idx for country
Transformed: Encoded idx for directorID
Transformed: Encoded idx for genre
encoded 2064

Calculating user diversity preference scale: 100%|██████████| 2064/2064 [00:03<00:00, 668.73it/s]

combined_df 2064
Calculating DPMS for each feature...

,userID,actorID_dpms,country_dpms,directorID_dpms,genre_dpms,avg_dpms
count,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000,2064.000000
mean,1031.500000,0.300113,0.991161,0.394626,0.959495,0.661349
std,595.969798,0.072029,0.010848,0.134547,0.019566,0.046398
min,0.000000,0.030438,0.799220,0.000000,0.762575,0.477504
25%,515.750000,0.253988,0.989440,0.320172,0.950511,0.633871
50%,1031.500000,0.304789,0.993768,0.410647,0.962659,0.666983
75%,1547.250000,0.349773,0.996482,0.486287,0.973283,0.694167
max,2063.000000,0.543348,0.999974,0.752244,0.992558,0.785857